### ISSUE TITLE
Non root run for sorry-cypress-dashboard

### ISSUE THREAD

**Issue by yannay000** [sorry-cypress/sorry-cypress#121]
Could you add non root run for this image

### dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

from docker-compose.full.yml, please?

**Comment by stobias123** [comment]
@yannay000  - what is your use case, are you on openshift?

**Comment by darko711** [comment]
@stobias123 i tried to get it running on OpenShift today, but have no chance due to some permission denied issues with /etc/nginx/* and /var/cache/nginx/*. 

do you have any infos if there is a way to get it running on OpenShift?

**Comment by agoldis** [comment]
@tico24 do you have any experience with Open Shift?

**Comment by tico24** [comment]
None I'm afraid @agoldis, but rootless would be nice 😄

**Comment by stobias123** [comment]
Yes I'm running on open shift. I'll see if I can add some docs.

**Comment by darko711** [comment]
@agoldis Could you provide containers which run non-root for OpenShift, please? Or too much hassle?

**Comment by agoldis** [comment]
@darko711 awesome, I'll merge your work with mine later this week

**Comment by darko711** [comment]
@agoldis i cloned your repo and rebuilt the dashboard. The Installation now fetches the Dashboard Image from my private OpenShift Registry. I replaced the FROM: nginx with -> 

FROM nginxinc/nginx-unprivileged

I got the container now up and running in OpenShift, but still something is missing as as i get an CORS Error when the Dashboard calls the API Server. "MissingAllowOriginHeader". Any ideas?

We'll get this working 👍

**Comment by agoldis** [comment]
@darko711 actually my previous comment was intended for a different issue :) 

I think CORS is missing on the dashboard side, it'd be added nginx configuration as described here https://enable-cors.org/server_nginx.html

**Comment by darko711** [comment]
@agoldis doesn't CORS rules need to be set on the apiServer to allow Requests from the Dashboard?

**Comment by agoldis** [comment]
@darko711 absolutely, you are right :) I was dreaming

**Comment by eric-hc** [comment]
Has anybody built & published a non-root image yet?

**Comment by agoldis** [comment]
I don't think so, probably @darko711 had had some success. Would be happy to help with a PR!

**Comment by agoldis** [comment]
please check out  https://docs.sorry-cypress.dev/cloud-setup/docker-images/running-sorry-cypress-dashboard-as-non-root-user  and https://github.com/sorry-cypress/sorry-cypress/pull/348.
Thanks @mathpaquette for the documentation
