### ISSUE TITLE
Update test instance view for Cypress 5.0

### ISSUE THREAD

**Issue by bradyolson** [sorry-cypress/sorry-cypress#125]
With Cypress 5.0.0, the results API has been changed to include information about retries. https://docs.cypress.io/guides/references/migration-guide.html#Module-API-results

The test view still shows the test title, state badge, and screenshot. However, the error message and stack trace are missing. GraphQL models and the instance view should be updated to display this information.

**Comment by gauravguptagit** [comment]
Hi @agoldis & Team,
First of all, congratulation on building such a good product alternative to the official cypress dashboard. Setup and configuration work like a charm, Thank you so much. :heart:

I would like to know the timeline for this issue, By when we could see the test view compatible with cypress 5 runs?

**Comment by agoldis** [comment]
I hope to have some time for that issue this weekend.

**Comment by gauravguptagit** [comment]
> I hope to have some time for that issue this weekend.

Great :relaxed:

**Comment by agoldis** [comment]
I have released V5+ compatible docker images:

```
agoldis/sorry-cypress-dashboard:cypress-v5
agoldis/sorry-cypress-director:cypress-v5
agoldis/sorry-cypress-api:cypress-v5
```

The source code is also available https://github.com/sorry-cypress/sorry-cypress/pull/137

Will make an actual release after some testing. You can grab the image today for your trial. It also supports multi-projects setup, thanks to @jhicken

**Comment by gauravguptagit** [comment]
Awesome @agoldis & @jhicken, I'll try these images.
