### ISSUE TITLE
'Aggregation project operator not supported' error from API component (when using AWS DocumentDB)

### ISSUE THREAD

**Issue by joe-carpenter** [sorry-cypress/sorry-cypress#133]
NB this deployment is currently configured using AWS DocumentDB (MongoDB 3.6 'api compatibility') - we have been running on-cluster Mongo up until now, but would like to make it a bit more stable and scalable as we are using `sorry-cypress` quite heavily.

All `sorry-cypress` components are latest versions.

When the frontend loads the main `All Runs` page, it sends a call to the API component with the following payload:

```
{"operationName":"getRunsFeed","variables":{"cursor":""},"query":"query getRunsFeed($cursor: String) {
  runFeed(cursor: $cursor) {
    cursor
    hasMore
    runs {
      runId
      createdAt
      meta {
        ciBuildId
        projectId
        commit {
          sha
          branch
          remoteOrigin
          message
          authorEmail
          authorName
          __typename
        }
        __typename
      }
      specs {
        spec
        instanceId
        claimed
        results {
          cypressConfig {
            video
            videoUploadOnPasses
            __typename
          }
          videoUrl
          tests {
            title
            state
            __typename
          }
          stats {
            tests
            pending
            passes
            failures
            skipped
            suites
            wallClockDuration
            wallClockStartedAt
            wallClockEndedAt
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
"}
```

which returns the following error:

```
{
    "errors": [
        {
            "message": "Aggregation project operator not supported: '$map'",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "runFeed"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "ok": 0,
                    "code": 305,
                    "name": "MongoError",
                    "stacktrace": [
                        "MongoError: Aggregation project operator not supported: '$map'",
                        "    at Connection.<anonymous> (/app/node_modules/mongodb/lib/core/connection/pool.js:451:61)",
                        "    at Connection.emit (events.js:198:13)",
                        "    at processMessage (/app/node_modules/mongodb/lib/core/connection/connection.js:452:10)",
                        "    at TLSSocket.<anonymous> (/app/node_modules/mongodb/lib/core/connection/connection.js:621:15)",
                        "    at TLSSocket.emit (events.js:198:13)",
                        "    at addChunk (_stream_readable.js:288:12)",
                        "    at readableAddChunk (_stream_readable.js:269:11)",
                        "    at TLSSocket.Readable.push (_stream_readable.js:224:10)",
                        "    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

I am absolutely not a Mongo expert, so this doesn't mean a huge amount to me... Do you know if there is something I can do to work around this? Or is this just not going to work?

**Comment by joe-carpenter** [comment]
Guessing its here: https://github.com/agoldis/sorry-cypress/blob/master/packages/api/src/datasources/runs.ts#L66 (NB I am not a JS dev either!!) this does not appear to work with supported aggregations in DocumentDB (see https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html#mongo-apis-dababase-aggregation) ... is there some other way of doing it that would work?

**Comment by joe-carpenter** [comment]
NB @agoldis... If I just delete [these lines](https://github.com/agoldis/sorry-cypress/blob/master/packages/api/src/datasources/runs.ts#L65-L71) and build and push the image locally, I can then see stuff on the dashboard, and the API error goes away... not sure what implications this really has though..

**Comment by agoldis** [comment]
@joe-carpenter glad you were able to resolve it! 
According to 
https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html#mongo-apis-aggregation-pipeline DocumentDB doesn't support `$map` aggregation stage. 


Some UI info might be missing. That can be fixed by modifying the query and avoid using $map. Alternatively you can switch to Atlas and use the original Mongo

**Comment by joe-carpenter** [comment]
@agoldis could you comment on how the query could be modified?... I've tried a few things, but my problem is that I don't really understand what that bit of the query is trying to do, and I am also a complete Mongo noob :'(

**Comment by agoldis** [comment]
Sorry for delayed response. This query generates and formats data for "Runs" that's used by the dashboard. It is well described [here](https://docs.mongodb.com/manual/reference/operator/aggregation/map/). 

```
const projectAggregation = {
  $project: {
    _id: 1,
    runId: 1,
    meta: 1,
    specs: 1,
    createdAt: 1,
    specsFull: {
      $map: {
        input: '$specs',
        as: 'spec',
        in: '$$spec.instanceId',
      },
    },
  },
};

const lookupAggregation = {
  $lookup: {
    from: 'instances',
    localField: 'specsFull',
    foreignField: 'instanceId',
    as: 'specsFull',
  },
};
```

Those two stages are applied one after another:
- `projectAggregation` extracts instance ids as a list field called `fullSpec`
- `lookupAggregation` replaces each member of the list with a full document from `instances` collection with based on the id

What can try to reshuffle that data at runtime using two separate queries. The idea is to populate `specsFull` with actual `spec` documents

**Comment by agoldis** [comment]
Closing this, please reopen if you need further assistance
