### ISSUE TITLE
Test execution timer never stops for manually terminated runs

### ISSUE THREAD

**Issue by gmkumar08** [sorry-cypress/sorry-cypress#134]
@agoldis excellent work.

I just started using this dashboard (minio version) and noticed that the test execution timer never stops for manually terminated runs. Could you kindly take a look.

![image](https://user-images.githubusercontent.com/46545923/93082984-77552580-f6af-11ea-9bc2-f04a997c6ef0.png)

**Comment by jhicken** [comment]
@gmkumar08 What would be your desired outcome? Right now the cypress test runner clients (can be in parallel) pick up spec files and when they finish they report the results to sorry-cypress. That report is what dictates that a spec file is complete. If cypress is shut down on the client, the report is never generated. So sorry-cypress thinks the spec file is still running.

Sorry-Cypress defines a spec as "claimed" when a client picks it up. We could mark spec files that having been claimed as not claimed after some time limit of no report(This report only happens after client finishes running a spec). Then we could declare the entire run as timed out after some time limit of no changes on specs. 

We could also just add a cancel button to spec and run views? This is interesting cause we could also add a retry button to these views as well.

I thought about this a little when I implemented this and I landed on just letting it do what its doing for simplicity.

Thoughs?

**Comment by gmkumar08** [comment]
@jhicken Thank you for your response and for your efforts in building this app.

Yes, a "Cancel" button sounds good. I was also wondering if it should be labelled just as "Cancel" or may be something like "Mark as Cancelled" or "Mark as Terminated". Selecting this should essentially stop the timer and mark the entire run as either "Cancelled" or "Terminated".  How does this sound?

If this is not so feasible, then as you mentioned: can we have a variable that would allow us to set the time out so that the users can set the time out based on their requirements. And once it hits the timeout, may be we can stop the timer and mark the entire run as "Timed Out".

Both of these implementations would work for us.

**Comment by jhicken** [comment]
Cool yeah this sounds like 2 new features. I think I see the use case for both individually.

On the cancel button. I think its pretty clear to just call it "Cancel" or "Stop". Im not sure the extra wording is needed. 

1. Introduce Run timeouts
2. Add cancel button to the Run and Spec views

@agoldis Does this sound good to you?

@gmkumar08 I would love to see a PR for this :)

**Comment by agoldis** [comment]
Nice analysis, @jhicken!

Indeed it seems like 2 separate issues.  The original cypress dashboard implements the timeout strategy for each run BTW.

**Comment by agoldis** [comment]
Resolved by https://github.com/sorry-cypress/sorry-cypress/pull/292
