### ISSUE TITLE
Github Integration

### ISSUE THREAD

**Issue by IvanBioRender** [sorry-cypress/sorry-cypress#14]
It would be nice to have a Github integration that reports test results as status checks.

**Comment by agoldis** [comment]
Hey @IvanBioRender, usually the CI environment where you are runnin the tests provides status updates for github / version control provider.

Any chance you can elaborate on your use cases so I can get more familiar with requirements?

**Comment by IvanBioRender** [comment]
Hey Andrew, ideally it would work the same way as Cypress does it:
https://docs.cypress.io/guides/dashboard/github-integration.html

The dashboard would have a Github token (or be installed as a Github app
into your repo), allowing it to use OctoKit to access the Github API. Once
it finishes a test run, it would report a status check for the
corresponding pull request, with a summary of the results (or a link to the
full report on the dashboard).

Thanks for this project btw, it's super useful! I don't have much time
right now, but I'd love to contribute in the future.

**Comment by agoldis** [comment]
Gotcha! Will give it a try

**Comment by agoldis** [comment]
After the initial exploration both Github Apps and Github OAuth integrations assumes an existence of integration "owner".

E.g. github app would be assigned a secret key and `appId`. Same for OAuth integration - it require creation of a distinct OAuth app for each `sorry-cypress` installation.

The on-premise nature of the project complicates the solution. 

May be sometime in future we can have a cloud-based cypress dashboard that can own those integrations, and allow access for different users. This model is problematic though - it is expensive (who'd pay for that?) and even if someone pays, it is kind of unethical - it would be a direct competition with cypress team.

For now I would suggest to keep this feature in backlog and try reconsider it in future.

**Comment by IvanBioRender** [comment]
You make a very good point! I've set up Github apps for personal projects,
and having to do it yourself is really tedious.

I think it's with well-written documentation on the setup it wouldn't be
too bad - I may try hacking this onto sorry-cypress at some point, if I do
I'll update you :)

Thanks again for the fast response to this request!

**Comment by agoldis** [comment]
@jhicken is you what you're trying to achieve with projects and hooks?

**Comment by jhicken** [comment]
Yarp.

I'm pretty close aswell. I'm introducing a couple kinds of hooks that you will define on you project. One of them is a github status set of hooks that will post the status of your tests to your github prs on run start, run finish, instance start, and instance finish.

**Comment by jhicken** [comment]
@IvanBioRender 
Have you tested this integration to see if it covers your use case?

**Comment by denis-domanskii** [comment]
@jhicken I have faced an issue with a GitHub hook: #196

**Comment by DeniDoman** [comment]
@agoldis I think we can close the issue.

**Comment by agoldis** [comment]
Resolved by #209
