### ISSUE TITLE
 Add URL that assertions failed at to the spec results page

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#141]
Extracted from https://github.com/sorry-cypress/sorry-cypress/issues/87
@jhicken can you elaborate pls, what's the idea?

**Comment by jhicken** [comment]
Yeah totally. So when an assertion fails. I would like to have a link to the place the cypress test failed. I use this all the time when I manually run the headed test suit on my machine. Its nice to just be able to click the url in the url bar and do some manual exploration at the exact url the test failed at.
