### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#143]
@jhicken I need your help here. Should it be a separate issue or bound to Github / slack ticket? 

Extracted from https://github.com/sorry-cypress/sorry-cypress/issues/87

**Comment by jhicken** [comment]
Good question. The hooks feature could be considered completely separate from github and slack. However its certainly a prerequisite for them.

And im kinda doing the generic hooks in tandem with the github status hooks right now. So its kinda connected to the github issue.
