### ISSUE TITLE
Project and Hooks documentation

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#149]
For easier adoption...

**Comment by pedrohyvo** [comment]
@agoldis I'd like to contribute and start working on this issue. Could you give me more details please

**Comment by agoldis** [comment]
@pedrohyvo Hi and welcome!
We have the documentation website at https://github.com/sorry-cypress/sorry-cypress.dev.
It is currently lacking and information about projects and hooks. 

It'd be cool to get some concise documentation about:
- how to create a new project
- when projects are created automatically 


Same for hooks:
 - how to setup hooks
- what types of hooks are supported
- what is the payload
- example

Most people are already familiar with project from the original cypress, so I'd put more focus on hooks.
You can use the source code for reference and ask myself or @jhicken when stuck.

How does it sound?

**Comment by agoldis** [comment]
@pedrohyvo FYI  #209

**Comment by agoldis** [comment]
Updated https://doc.sorry-cypress.dev
