### ISSUE TITLE
Can we show the test run start time as per the local time zone?

### ISSUE THREAD

**Issue by gmkumar08** [sorry-cypress/sorry-cypress#153]
# What is this feature about? (1 sentence)
As of now, the test run start time is displayed in GMT. Can we show it as per the user's local time zone?

# Why is it needed? What is the value? For whom do we build it?
It helps to easily identify when was the run scheduled if it's displayed in their respective local time.

# High-level overview of the feature
- Display Test Run Start Time as per the local time zone

**Comment by agoldis** [comment]
Absolutely!
