### ISSUE TITLE
Latest (1.0.0-beta.0) release tag not showing up on Docker hub

### ISSUE THREAD

**Issue by KyleThenTR** [sorry-cypress/sorry-cypress#157]
It looks like the latest release didn't tag properly on Docker. Typically I would expect the docker images to be tagged with the same version as the github tags, but I don't see 1.0.0-beta.0 in Docker hub.

**Comment by agoldis** [comment]
Fixed in #158

**Comment by agoldis** [comment]
`docker pull agoldis/sorry-cypress-director:1.0.0-beta.1`
