### ISSUE TITLE
Quickstart guide doesn't show screenshots

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#165]
Quickstart instructions do not show snapshots properly. Need to update `docker-compose.minio.yml` to allow accessing containerized minio from the host machine

**Comment by tellyo-patryk** [comment]
I can assist with creating documentation since I've overcome the issue so I can give back to the project in some way

**Comment by tellyo-patryk** [comment]
But I don't know whether there's a way to change uploadUrl in the current state of the project and it's crucial if we don't want to edit /etc/hosts or create an A record in DNS for "storage" that the uploadUrl is by default, it's perfectly fine to use that kind of url but only inside the network that is created with docker-compose for sorry-cypress

**Comment by agoldis** [comment]
Thanks @tellyo-patryk, that was just matter of configuration
