### ISSUE TITLE
Error: Your Record Key is not valid with this project

### ISSUE THREAD

**Issue by balachandra** [sorry-cypress/sorry-cypress#168]
Following instruction from here https://sorry-cypress.dev/quickstart, on cypress run i get following error. any idea whats happening please? thanks.

```
Your Record Key whate...tever is not valid with this project: cypressontestenv

It may have been recently revoked by you or another user.

Please log into the Dashboard to see the valid record keys.

https://on.cypress.io/dashboard/projects/cypressontestenv
```

**Comment by gmkumar08** [comment]
@balachandra The api_url in app.yml might still be pointing to "https://api.cypress.io/" instead of "http://localhost:1234"

**Comment by agoldis** [comment]
@balachandra
Please double-check what is  `api_url` in `app.yml` as @gmkumar08  suggested

**Comment by agoldis** [comment]
@balachandra Please feel free to reopen once you've confirmed, I am cleaning the backlog meanwhile
