### ISSUE TITLE
Delete video and screenshot in minIO and S3

### ISSUE THREAD

**Issue by gespispace** [sorry-cypress/sorry-cypress#169]
I deleted all runs, but i have very much video and screenshot. 
![image](https://user-images.githubusercontent.com/37763089/95701214-6376f200-0c62-11eb-8e76-3b274b483742.png)

**Comment by jhicken** [comment]
Yeah I knew about this one. I had the same issue on s3. I think durring upload of images and videos they should be  put in nested folders. "root/<projectid>/<runid>/filename"

At that point it should be trivial to clean up those resources on project deletion or on run deletion.

Right now clean up just isn't happening.

**Comment by BHunter2889** [comment]
What is the status of this? Presently not a huge issue though as the helm chart suggested configuration requires us to delete the PVC each time we redeploy so it cleans itself up in that regard anyway... 😄

**Comment by agoldis** [comment]
Still no progress :) I have been focusing on other issues meanwhile

**Comment by mathpaquette** [comment]
yes I agree this one is an important one. Could we flag it as important or critical ? We need an automated way to purge old runs and related videos and screenshots.

**Comment by mathpaquette** [comment]
@agoldis what are your thoughts ?

**Comment by agoldis** [comment]
@mathpaquette Yeah, seems like a reasonable request!

**Comment by mathpaquette** [comment]
> @mathpaquette Yeah, seems like a reasonable request!

personally, I'd like to keep the data in mongodb for generating statistics though.
