### ISSUE TITLE
Participation in Hacktoberfest

### ISSUE THREAD

**Issue by burtyish** [sorry-cypress/sorry-cypress#171]
Hi!

Would you be interested in taking part in [Hacktoberfest](https://hacktoberfest.digitalocean.com/faq)?

My organization has just started trying out sorry-cypress. I see you have some open issues, some even marked as `good first issue`. This could be a good opportunity, since I prefer to contribute to projects I work with.

Thank you very much

**Comment by agoldis** [comment]
Sure! That's a good idea!

**Comment by agoldis** [comment]
I have added the topic to the project's description as appears at https://hacktoberfest.digitalocean.com/hacktoberfest-update

```
PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

I think that should be enough to count the PR as valid for Hacktoberfest
