### ISSUE TITLE
Problem with grouping tests

### ISSUE THREAD

**Issue by Upgreydd** [sorry-cypress/sorry-cypress#177]
Hello @agoldis,
Have a question related to grouping tests by `--ci-build-id`. I have a lot of tests grouped by directories and tests in directories depend on each other, so they are started in a specific order. I'll try to show you an example. Multiple runs are specified with one command: 
```
cypress_integrationFolder=cypress/integration/test_name cypress run --parallel --headless --record --key xxx --ci-build-id $BUILD_NUMBER
``` 
As you can see each parallel run for a specific group of tests contains the same build id (which is good) but different `cypress_integrationFolder`. In my opinion, in the panel, I should see them under one run, but they all are split into separate runs (with the same `$BUILD_NUMBER`). Is there an option to merge them?

**Comment by Upgreydd** [comment]
Checked cypress documentation and there's `--group` parameter for parallel builds, but `sorry-cypress` generates runId by a joined list of spec files.

**Comment by Upgreydd** [comment]
@agoldis created PR: https://github.com/sorry-cypress/sorry-cypress/pull/178

**Comment by agoldis** [comment]
I think it is a duplication of #57. Definitely a good feature to support, I am closing this one if favour of #57, let's follow up there. 
Please feel free to reopen if you think #57 is unrelated

**Comment by Upgreydd** [comment]
@agoldis thanks. https://github.com/sorry-cypress/sorry-cypress/pull/181
