### ISSUE TITLE
[Bug] Hooks don't work

### ISSUE THREAD

**Issue by gespispace** [sorry-cypress/sorry-cypress#193]
## Summary

Sorry cypress does not send hook, but should send hook

## How to reproduce
I don't know, but it is error
```
director_1       | (node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'hookEvent' on boolean 'true'
director_1       |     at reportToGenericWebHook (/app/dist/lib/hooksReporter.js:143:28)
director_1       |     at /app/dist/lib/hooksReporter.js:174:16
director_1       |     at Array.forEach (<anonymous>)
director_1       |     at reportToHook (/app/dist/lib/hooksReporter.js:166:152)
director_1       |     at handleUpdateInstance (/app/dist/api/instances.js:103:35)
director_1       |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
and hook 
![image](https://user-images.githubusercontent.com/37763089/97125756-bec2dd00-1756-11eb-8264-24a2ee77cc1a.png)

## Environment

- sorry-cypress version: `latest`
- cypress version: `5.4.0`
- platform: `docker-compose.minio.yml`
- service: `director`

**Comment by gespispace** [comment]
what other information is needed to solve the problem?

**Comment by jhicken** [comment]
Odd Ill have a look at it in the morning.

**Comment by gespispace** [comment]
@agoldis bug not fix. 
![image](https://user-images.githubusercontent.com/37763089/97477676-ba264080-1971-11eb-9b26-7e65241d36b4.png)

**Comment by gespispace** [comment]
latest images
![image](https://user-images.githubusercontent.com/37763089/97477938-12f5d900-1972-11eb-8eb7-22396139d0f4.png)

**Comment by agoldis** [comment]
kk well fix later
