### ISSUE TITLE
Parallel tests all running on all Docker containers

### ISSUE THREAD

**Issue by CScharer** [sorry-cypress/sorry-cypress#194]
[Parallel tests all running on all Docker containers](https://github.com/cypress-io/cypress/issues/8912)
Sorry-Cypress: latest

**Comment by mathpaquette** [comment]
@CScharer what does it mean?

**Comment by agoldis** [comment]
@CScharer If i read https://github.com/cypress-io/cypress/issues/8912 correctly there's no parallelization - every agent runs the same set of tests? 

And you're cross-posting here because it happens on sorry-cypress and on cypress dashboard as well.

Is it correct?

**Comment by CScharer** [comment]
Correct.  When I run there's no parallelization on both.  It also appears to loop on the first test.

**Comment by agoldis** [comment]
I was able to run successfully with 5.5.0 (latest) and 5.4.0 http://sorry-cypress-195-532018670.us-east-1.elb.amazonaws.com/sorry-cypress/runs

I think cypress user would have reported a major issue if parallelization stopped working just like this. Looking at your example, I'd double-check that `"--ci-build-id", "${CI_BUILD_ID}"` and  `"--group", "${ENVIRONMENT}"` are similar for all runners

**Comment by CScharer** [comment]
The ci-build-id and group are the same as you can see, but ironically for some reason in Cypress Dashboard it appends a number to the second and third container that start?

cypress_1   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key ******** --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 643247,chrome,encappdevelopment,AzureAD
cypress_2   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key ******** --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 643247,chrome,encappdevelopment,AzureAD
cypress_3   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key ******** --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 643247,chrome,encappdevelopment,AzureAD

**Comment by CScharer** [comment]
I'm using the following command in my docker-compose.yml which would contain the same information for all three containers:
    command: [ "run",
               "--browser", "${BROWSER}",
               "--ci-build-id", "${CI_BUILD_ID}",
               "--group", "${ENVIRONMENT}",
               "--headless",
               "--key", "${CYPRESS_PROJECT_KEY}",
               "--record",
               "--parallel",
               "--spec", "${SPEC_FILTER}",
               "--tag", "${CI_COMMIT_SHA},${CI_BUILD_ID},${BROWSER},${ENVIRONMENT},${AUTH_TYPE}" ]

**Comment by CScharer** [comment]
[docker-compose.txt](https://github.com/sorry-cypress/sorry-cypress/files/5444360/docker-compose.txt)
This is the full docker-compose.yml file renamed as .txt so I could attach it.

**Comment by CScharer** [comment]
$CYPRESS_VERSION=5.4.0
$PARALLEL=3
$CI_BUILD_ID= 643247

**Comment by CScharer** [comment]
The Cypress Dashboard ends up with this...
![Uploading image.png…]()

**Comment by agoldis** [comment]
I see a small difference in the specs glob you've provided:
```
cypress/integration/SmokeTests//*.spec.ts
cypress/integration/SmokeTests//.spec.ts
cypress/integration/SmokeTests/**/.spec.ts
```
Does it resolve to the same list of specs?

**Comment by CScharer** [comment]
Good catch and I'm not sure how that's different, but the only difference between each of them is actually just the cypress number.  I must have accidentally changed them when trying to remove the key which probably doesn't matter because I revoked it after realizing I included it in my post.

cypress_1   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD
cypress_2   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD
cypress_3   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD

**Comment by CScharer** [comment]
I see in my previous post it's different too so it must be something with the way the post interprets the string.  They are all the same and are like this.

SPEC_FILTER_SMOKE='cypress/integration/SmokeTests/**/*.spec.ts'

**Comment by CScharer** [comment]
Anything else I can provide or any luck reproducing this?

**Comment by agoldis** [comment]
I couldn't reproduce I did run with two different versions of cypress and with / without groups - everything was fine. 
As noted, if parallelization stopped working for cypress they would patch it there would be a major bug reported in their issues list. 
May be there's a but that is only triggered by a specific combination of your specs and group.

I can suggest a few options:
1. Try to run with just 2 specific specs minimum required flags and see if parallelization works 
2. Try to add tags gradually until problem reproduced
3. Try to examine the cypress agent traces with `DEBUG=cypress:*` it dumps a lot of information
4. You can attache a debugger to a locally running version of sorry-cypress and troubleshoot why two separate runs are being created
5. You can try to send your tests to https://sorry-cypress-demo-director.herokuapp.com/ (dashboard is https://sorry-cypress-demo.herokuapp.com/), I will take a look at the data on the backend, may be I can see what's the problem.

**Comment by agoldis** [comment]
@CScharer hey, were you able to try any of suggestions? 👆🏻

**Comment by CScharer** [comment]
I removed the tags altogether and they appear to be run separately.  I believe the issue may be in that the line that was adding the tags begins with a numeric character and did not have any quotes around the tag.
"--tag", "${CI_COMMIT_SHA},${CI_BUILD_ID},${BROWSER},${ENVIRONMENT},${AUTH_TYPE}"
Trying with a single quote around the tag value.
"--tag", "'${CI_COMMIT_SHA},${CI_BUILD_ID},${BROWSER},${ENVIRONMENT},${AUTH_TYPE}'"

**Comment by CScharer** [comment]
I've tried several combinations and this is passing no ci-build-id or tag(s), but it still appears to create a separate Run URL for each container.

cypress_1   |   │ Cypress:        5.5.0                                                                          │
cypress_1   |   │ Browser:        Chrome 85 (headless)                                                           │
cypress_1   |   │ Node Version:   v12.14.1 (/usr/local/bin/node)                                                 │
cypress_1   |   │ Specs:          6 found (SmokeTests/108738_Smoke_Tests/agventure.spec.ts, SmokeTests/108738_Sm │
cypress_1   |   │                 oke_Tests/dairyland_seed.spec.ts, SmokeTests/108738_Smoke_Tests/hoegemeyer.spe │
cypress_1   |   │                 c.ts, SmokeTests/108738_Smoke_Tests/nutech.spec.ts, SmokeTests/108738_Smoke_Te │
cypress_1   |   │                 sts/pioneer.spec.ts, S...)                                                     │
cypress_1   |   │ Searched:       cypress/integration/SmokeTests/**/*.spec.ts                                    │
cypress_1   |   │ Params:         Tag: false, Group: encappdevelopment, Parallel: true                           │
cypress_1   |   │ Run URL:        https://dashboard.cypress.io/projects/zb4yp5/runs/424                          │
cypress_1   |   │ Experiments:    experimentalNetworkStubbing=true                                               │

cypress_2   |   │ Cypress:        5.5.0                                                                          │
cypress_2   |   │ Browser:        Chrome 85 (headless)                                                           │
cypress_2   |   │ Node Version:   v12.14.1 (/usr/local/bin/node)                                                 │
cypress_2   |   │ Specs:          6 found (SmokeTests/108738_Smoke_Tests/agventure.spec.ts, SmokeTests/108738_Sm │
cypress_2   |   │                 oke_Tests/dairyland_seed.spec.ts, SmokeTests/108738_Smoke_Tests/hoegemeyer.spe │
cypress_2   |   │                 c.ts, SmokeTests/108738_Smoke_Tests/nutech.spec.ts, SmokeTests/108738_Smoke_Te │
cypress_2   |   │                 sts/pioneer.spec.ts, S...)                                                     │
cypress_2   |   │ Searched:       cypress/integration/SmokeTests/**/*.spec.ts                                    │
cypress_2   |   │ Params:         Tag: false, Group: encappdevelopment, Parallel: true                           │
cypress_2   |   │ Run URL:        https://dashboard.cypress.io/projects/zb4yp5/runs/423                          │
cypress_2   |   │ Experiments:    experimentalNetworkStubbing=true                                               │

cypress_3   |   │ Cypress:        5.5.0                                                                          │
cypress_3   |   │ Browser:        Chrome 85 (headless)                                                           │
cypress_3   |   │ Node Version:   v12.14.1 (/usr/local/bin/node)                                                 │
cypress_3   |   │ Specs:          6 found (SmokeTests/108738_Smoke_Tests/agventure.spec.ts, SmokeTests/108738_Sm │
cypress_3   |   │                 oke_Tests/dairyland_seed.spec.ts, SmokeTests/108738_Smoke_Tests/hoegemeyer.spe │
cypress_3   |   │                 c.ts, SmokeTests/108738_Smoke_Tests/nutech.spec.ts, SmokeTests/108738_Smoke_Te │
cypress_3   |   │                 sts/pioneer.spec.ts, S...)                                                     │
cypress_3   |   │ Searched:       cypress/integration/SmokeTests/**/*.spec.ts                                    │
cypress_3   |   │ Params:         Tag: false, Group: encappdevelopment, Parallel: true                           │
cypress_3   |   │ Run URL:        https://dashboard.cypress.io/projects/zb4yp5/runs/425                          │
cypress_3   |   │ Experiments:    experimentalNetworkStubbing=true

**Comment by CScharer** [comment]
I'm not sure, but wondering if it could have anything to do with my cypress-entrypoint.sh

#!/bin/bash -x

# This entrypoint file is used/required if targeting local sorry-cypress or the cypress dashboard for master branch merges.
# Set api_url to desired host
sed -i -e 's|api_url:.*$|api_url: "'${CYPRESS_API_URL:-http://director:1234}'"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml

# Sleep briefly so starting N containers at once with --scale cypress=N doesn't overwhelm the system
sleep $((($RANDOM % 10) + 3))s

#PATH=./node_modules/.bin/:$PATH
#cypress install

#exec cypress "$@"
# Replaced with the following.
cypress "$@"
exit 0

**Comment by agoldis** [comment]
- What version of sorry-cypress are you running? 
- What's your sorry-cypress setup? 

---

Please try running the following 2 commands in two separate containers, while both containers use the same director instance (based on your entry point it is `http://director:1234`, by the way, is it the same single instance of director?).

Before running the command, please make sure your have access to director stdout and copy the traces while you're running this commands on two separate containers in parallel
```
cypress run --ci-build-id testing-sorrry-cypress-001 --key whatever --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts'
```

If possible, please also attach the dump of mongodb `run` records created for those two invocations.

Let's see if we can figure it out based on the logs.

**Comment by CScharer** [comment]
I was never able to figure out what the issue was with this, but while trying to upgrade to Cypress 6.8.0 I found other issues and now have it successfully working with Cypress 6.6.0.  I plan to work on upgrading to Cypress 6.8.0 next, but need to figure out the changes with SorryCypress.
