### ISSUE TITLE
Broken uploads when using cloudformation 

### ISSUE THREAD

**Issue by Zibby** [sorry-cypress/sorry-cypress#195]
## Summary

Cloud formation has created the s3 bucket, but all the uploads to the bucket seem to fail and create broken image links in the UI. 

From my jenkins stdout:
```
  (Uploading Results)
  - Failed Uploading (1/2) /app/cypress/screenshots/brands/new.spec.js/NewBrandView -- brand admin -- shouldn't be able to access new brand form via URL -- before each hook (failed).png
  - Failed Uploading (2/2) /app/cypress/screenshots/brands/new.spec.js/NewBrandView -- converser -- shouldn't be able to access new brand form via URL -- before each hook (failed).png
```

**Comment by agoldis** [comment]
I have just created a brand-new stack at http://sorry-cypress-195-532018670.us-east-1.elb.amazonaws.com/ using the default template at https://s3.amazonaws.com/agoldis.dev/sorry-cypress/sorry-cypress-stack.yml

It all works as expected. Can you please:
1. Share the S3 traces when running tests with  `DEBUG=cypress:*`
2. Your bucket configuration / policy

**Comment by agoldis** [comment]
Hey @Zibby I wasn't able to reproduce, feel free to reopen when you confirm the issue on your side.

**Comment by thomaswelton** [comment]
@agoldis I'm getting what I expected it the same issue. Looking through the debug logs I can see this under `cypress:server:record failed to upload artifact`
`Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.`
And can see I'm getting a 307 status code back on that request

**Comment by agoldis** [comment]
. Can you please:

1. Share the **full** S3 traces when running tests with `DEBUG=cypress:*`, there should be a specific trace with upload url and upload trace with an error
2. Your bucket configuration / policy

**Comment by thomaswelton** [comment]
Hope you don't mind but I've sent you to full logs via email to your gmail address

**Comment by agoldis** [comment]
No problem! It appears to be related to https://docs.aws.amazon.com/AmazonS3/latest/dev/Redirects.html#TemporaryRedirection
You're sending the results to https://justpark-cypress-test-results.s3.amazonaws.com but it gets redirected to justpark-cypress-test-results.s3.eu-west-2.amazonaws.com.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>TemporaryRedirect</Code>
<Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message>
<Endpoint>justpark-cypress-test-results.s3.eu-west-2.amazonaws.com</Endpoint>
<Bucket>justpark-cypress-test-results</Bucket>
<RequestId>390ACC709B4E6743</RequestId><HostId>YWR4rxeNLPkY4hlWajUhL7IC9DB1MuxU8hQIEktz3FkHL660XNOucj1tN0vrFv645aTWWQpm2ts=</HostId>
</Error>
```

It is some kind of AWS issue. I can suggest to use "region-aware" bucket name `justpark-cypress-test-results.s3.eu-west-2.amazonaws.com`, may be setting AWS region on cypress agent machines to `eu-west-2` would help.

There's also this https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/, but this one should only happen during the first 24 hours. And sorry-cypress cloudformation template does not create cloud front resources.

If none works, may be just try with another region?

**Comment by thomaswelton** [comment]
@agoldis Is it not possible for the sorry cypress agent to handle and follow the temporary redirect when uploading?

If not, could you also provide some more info on where and how the "region-aware" bucket name should be set or how to update the AWS region on the cypress agents generated with the cloudformation stack?

**Comment by thomaswelton** [comment]
In the cloud formation stack it looks like the `S3_REGION` env variable is missing, so it's defaulting to 
`us-east-1`

https://github.com/sorry-cypress/sorry-cypress/blob/aa1a1ecebb46191394a429df5155bc6295ba1376/packages/director/src/screenshots/s3/config.ts

https://github.com/sorry-cypress/sorry-cypress/blob/9735691bf9eccee7545023dbe10270591dc6b1d2/cloudfront/sorry-cypress.yml#L434

https://github.com/sorry-cypress/sorry-cypress/blob/aa1a1ecebb46191394a429df5155bc6295ba1376/packages/director/src/screenshots/s3/s3.ts

I've made an update to the template to add this to the environment variables, can submit a PR if this resolves it

```
- Name: S3_REGION
   Value: !Join ['-', [!Ref 'AWS::StackName', 'test-results']]
```

**Comment by asimhon** [comment]
@agoldis is there an option to specific aws credentials for using S3 bucket upload? I'm trying to avoid public S3 access with local aws credentials but seems like using DEBUG=cypress* it uses anonymous?
[sorry-cypress.log](https://github.com/sorry-cypress/sorry-cypress/files/8598943/sorry-cypress.log)

**Comment by agoldis** [comment]
@asimhon https://docs.sorry-cypress.dev/configuration/faq#can-i-use-a-private-aws-s3-bucket-with-sorry-cypress
