### ISSUE TITLE
Retrying Jobs in CI leads to false positives

### ISSUE THREAD

**Issue by ChristianPe** [sorry-cypress/sorry-cypress#197]
Hello there,

first of all, thanks for all the great effort you put in this project. Its working great so far, I just have one question or maybe feature request.
We are running our tests in gitlab ci and calling them by cypress run --parallel --record --key xxx --ci-build-id=xxx on 4 ci runners. This works great and reduces the execution time greatly. If one of those tests fails, the process returns an error and everything is fine.
Now, when im retrying the gitlab ci job, cypress runs with the same args for key and ci-build-id, the failed test is not tried again and cypress run returns a non error status code, leading to a succeeding build job.

In my opinion it would be great, if the director would still return the failed specs after all tasks are distributed/executed. This way it would be possible to retry ci jobs and only rerun failed tests.

**Comment by agoldis** [comment]
Thanks for submitting this proposal.

Do you know if original cypress dashboard behaves differently? In general, I'd like to avoid having a different behavior from the original cypress (that would make easier to use the alternative)

When I deal with re-runs I just generate a new ci-build-id - that creates a new run.
Another alternative is to use cypress5 retries - it will retry individual specs mutliple times. 

Would any of those solutions work for you?

**Comment by ChristianPe** [comment]
Thanks for your quick reply! :) First of all I dont know how the original cypress dashboard behaves in this matter, sorry :/ 

The problem of the proposed solutions is, that i cannot prevent gitlab ci to offer to rerun the jobs manually. If someone in the team (accidentaly) clicks on retry, the failed job always succeeds, because the director says this pipeline-id was already tested. Therefore all depending stages like prod deployment get executed. 

But you are right and my problem might be more a gitlab ci or even vanilla cypress issue and would be resolved with for example this: https://gitlab.com/gitlab-org/gitlab/-/issues/27589 and a ci_job_retried variable which could be appended to the pipeline_id to distinguish those retries.
Im going to close the issue then, thanks for your time :)

**Comment by maxfriedmann** [comment]
@ChristianPe we're running into the exact same issue, I even didn't realize that for a week now. Did you eventually get this fixed? https://gitlab.com/gitlab-org/gitlab/-/issues/27589 is not progressing at all unfortunately...

**Comment by Aeolun** [comment]
@maxfriedmann What we do is have each test generate a file (in this case code coverage), and if that file does not exist after execution (e.g. zero cases were executed), we fail the test.
