### ISSUE TITLE
Add timeout for test execution.

### ISSUE THREAD

**Issue by gespispace** [sorry-cypress/sorry-cypress#199]
## What is this feature about (1 sentence)
Add the ability to set a timeout to start a test, and if the tests have not ended after the timeout, then mark it as not passed.
## Why is it needed? What is the value? For whom do we build it?
In my case, cypress crashes at runtime and I want to know what the tests ran.
## High-level feature overview
I thinking it is should field in settings of project for set timeout in seconds.

**Comment by jhicken** [comment]
https://github.com/sorry-cypress/sorry-cypress/issues/142

Its on the todo list. Thanks!

**Comment by gespispace** [comment]
@jhicken Thanks you. Can you add in form for create feature request checkbox that user tried searching similar this feature request .

**Comment by jhicken** [comment]
im going to close this for now. If you think it should be reopened just let me know.
