### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#201]
If you've actively and significantly contributed or plan to contribute, please consider creating an account and joining https://opencollective.com/sorry-cypress.

Not only coding is accepted - documentation, tutorials, videos also count. 

Keep in mind that our budget is 0$ 😄 but who knows?

@jhicken @dlavrenuek @StefanS-O @xtroncode  @tico24 @coreyshirk

**Comment by tico24** [comment]
@agoldis - it's early here so forgive me! You're asking us to sign up to claim expenses? I realy don't think I've contributed enough to warrant that. Thanks though.

**Comment by agoldis** [comment]
@tico24 it's more like - if you want to or plan to do something related to sorry-cypress, consider this
