### ISSUE TITLE
Average duration shows "0 sec" for all specs

### ISSUE THREAD

**Issue by TomaszG** [sorry-cypress/sorry-cypress#202]
## Summary

The average duration shows "0 sec" for all specs instead of the correct value. I wonder how it's calculated, what's the base for grouping? If it's grouped by spec name(path) then I believe it should be working? I couldn't find any docs on how it's calculated :(

## How to reproduce

??

## Environment

- sorry-cypress version: `1.0.0-beta7`, I will check it on the latest beta to make sure.
- cypress version: `5.3.0`
- platform: `docker`
- service: `dashboard`

**Comment by agoldis** [comment]
Tested with the latest build - works fine.

<img width="1451" alt="Screen Shot 2020-11-02 at 10 17 58 PM" src="https://user-images.githubusercontent.com/1637928/97954774-4ad99380-1d59-11eb-8c96-9ad5d97fd05c.png">

It is calculated on client side:

https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/dashboard/src/views/RunDetailsView.tsx#L97:L97
https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/dashboard/src/views/RunDetailsView.tsx#L12:L12

Here's the query: 
https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/dashboard/src/views/getRunsByProjectIdLimitedToTiming.graphql#L5:L5

@TomaszG  it would be useful if you could share the query result.

@jhicken Do you have an idea?

**Comment by TomaszG** [comment]
So the query runs for 36 seconds and returns 5.3MB JSON, the size and time of execution may be the issue here. Maybe the query should limit results to e.g. last X runs.

Also, I noticed that API call form dashboard to that query ends up with 502 :(

**Comment by agoldis** [comment]
wow!! thanks for that new info, will see how to optimize it

**Comment by jhicken** [comment]
Wow yeah I think thats what we need to dig in on it.
