### ISSUE TITLE
sorry-cypress director is unable to coordinate parallel tests across two different machines

### ISSUE THREAD

**Issue by phao5814** [sorry-cypress/sorry-cypress#203]
I'm currently running Jenkins across two different machines running two different OSs. Machine A is running MacOS and Machine B is running Ubuntu.

When I try to run my cypress tests in parallel mode across these two machines, the sorry-cypress director does not coordinate tests across these two machines. Instead, both machines run the full suite of my cypress test with no knowledge of each other, which is not the expected behaviour.

For some context, the cypress tests on Machine A and Machine B are run inside a docker container using the exact same official Cypress docker image. Below is the cypress command that I run in my docker container. I make sure the BUILD_NUMBER used by cypress commands are always identical across both machines.

```
NODE_ENV=test $(npm bin)/cypress run --config video=false --browser chrome --headless --record --key xxx --parallel --ci-build-id $BUILD_NUMBER
```

I was under the impression that if `--ci-build-id` was the same across both machines, the sorry-cypress director would be able to coordinate tests in parallel across both machines; however, this does not appear to be the case.

I can confirm that my sorry-cypress director is set up correctly and does not appear to be the cause of my issues. When I run multiple cypress tests in parallel mode on Machine A, the sorry-cypress director is able to coordinate those tests as expected. The same is true when I run multiple cypress tests in parallel mode on Machine B.

**Why is it that sorry-cypress is unable to coordinate parallel tests across my two machines when I make sure I pass the same --ci-build-id to both machines?**

I did some digging and I have a suspicion that it relates to the fact that maybe the sorry-cypress director uses other parameters to determine a "run hash"? Can you confirm if this is the case?

For example, I saw the below comment in [another thread](https://github.com/sorry-cypress/sorry-cypress/pull/181#issuecomment-709804641).

> when creating a new run sc calculates a hash that is based on ciBuildId + commit.sha + projectId + specs.join(' '). If two machines send identical parameters, they will be associated with the same run. To support the scenario above we need to get rid of specs list while building that hash.

I also saw that platform.osName and platform.osVersion is used to generate a groupId of sorts in the [source code](https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/lib/hash.ts#L5). Is this related to the issue I'm facing?

**Comment by CScharer** [comment]
I wonder if this is related to the issue that I'm having?
https://github.com/sorry-cypress/sorry-cypress/issues/194#issuecomment-719181711

**Comment by jhicken** [comment]
@phao5814 Hey question. Do you see 2 different runs created in the sorry-cypress UI? Or is there just 1 when you start the tests?

The way unique runs are created is by this piece of code.

https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/lib/hash.ts#L9

**Comment by agoldis** [comment]
Seems like a bug, when no explicit group specified, we generate a "default" group https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/lib/hash.ts#L12

The default group is dependent on OS, have no idea why did I do that 🤷🏻‍♂️

@phao5814 as a workaround, just specify the same group name explicitly. 

@jhicken do you think about having just `ci-build-id` as the default group?

**Comment by jhicken** [comment]
Does group need a default? Like could we leave it null or undefined if group is not provided? I don't remember if there was anywhere that the group was being used in a different way that required us to have it.

Just looking at this for cypress-dashboard. https://docs.cypress.io/guides/guides/parallelization.html#Grouping-by-browser

**Comment by CScharer** [comment]
I see three different runs but I'm also running with three containers.  Everything being passed in is the same too, Group, CI-Build-ID, etc.

**Comment by agoldis** [comment]
> Does group need a default? Like could we leave it null or undefined if group is not provided? I don't remember if there was anywhere that the group was being used in a different way that required us to have it.
> 
> Just looking at this for cypress-dashboard. https://docs.cypress.io/guides/guides/parallelization.html#Grouping-by-browser

Sorry for delayed response, was busy with life. 

I have recently added groups support and group name is been displayed on spec results list. Also, the parallelization happens on per-group level, so having a default group which isn't nil would simplify
