### ISSUE TITLE
Failed on uploading videos locally

### ISSUE THREAD

**Issue by adrianchan12** [sorry-cypress/sorry-cypress#208]
I followed the Quickstart guide and was able to get the dashboard running locally showing the tests but when the tests are trying to upload the videos, it just failed.  I tried going to http://localhost:9000/minio/sorry-cypress/ but cannot see any screenshots or videos uploaded from the tests.  

Am I missing a step or do I need additional configuration?
Any help is much appreciated. 

Thanks

**Comment by ChristianIvicevic** [comment]
I see you have closed this issue, has this issue been resolved for you? Personally I am running into the same issue right now with both failed screenshots and the videos of the test runs.

**Comment by hallowatcher** [comment]
I'm running into the same issue sadly, can you please reopen this?

**Comment by adrianchan12** [comment]
I had the issue on when runing the docker-compose.minio.yml. In order to solve this for me, I had to do an additional step mentioned [here]( https://sorry-cypress.dev/director/storage#minio-driver) to configure my local host file.

**Comment by lucasltinoco** [comment]
@adrianchan12 I've followed that extra step that you mentioned and it worked! Thank you! 

Just opened a PR to reference that in the quickstart section of the docs.

**Comment by agoldis** [comment]
Thanks @lucasltinoco, https://github.com/sorry-cypress/sorry-cypress.dev/pull/7 should help with the setup

**Comment by lucasltinoco** [comment]
Happy to help this awesome project, @agoldis ! I'm currently trying to run on Heroku using MongoDB Atlas instead of the mLab add-on, since it's been discontinued. As soon as I can get it working, I plan to open a PR to update that section of the docs. Have you already tried something like that? Any tips?

**Comment by agoldis** [comment]
@lucasltinoco I have a working heroku setup:
sorry-cypress-demo.herokuapp.com
sorry-cypress-demo-api.herokuapp.com
sorry-cypress-demo-director.herokuapp.com

it uses Atlas.

I can add you to the project, please send me you email on slack / agoldis at gmail

**Comment by lpanger** [comment]
I'm having trouble getting local uploading working. I'm running on Windows and I've updated my host file at c:\windows\system32\drivers\etc

From the command line I can resolve localhost -> 127.0.0.1

No error messages in the docker-compose terminal. Any tips on how to debug this?

**Comment by agoldis** [comment]
> I'm having trouble getting local uploading working. I'm running on Windows and I've updated my host file at c:\windows\system32\drivers\etc
> 
> From the command line I can resolve localhost -> 127.0.0.1
> 
> No error messages in the docker-compose terminal. Any tips on how to debug this?

Run cypress with `DEBUG=cypress:*` to see upload error details

**Comment by lpanger** [comment]
Ah, found it! Cypress process couldn't resolve `storage`. I'm assuming this is pulled from `MINIO_ENDPOINT` in the yaml. Should this be configured to be an address resolvable outside of docker or should it be added to the hosts file? I tested the hosts file method and it worked.

**Comment by agoldis** [comment]
@lpanger  please take a look at https://docs.sorry-cypress.dev/configuration/director-configuration#minio-configuration `MINIO_ENDPOINT` section
