### ISSUE TITLE
Internal Server error on dashboard

### ISSUE THREAD

**Issue by AshTappin** [sorry-cypress/sorry-cypress#211]
When I go to https://sorry-cypress-demo.herokuapp.com/ , a 500 response is returned. Our CI build which runs parallel cypress tests is returning a 503. Not sure if that is related.

**Comment by agoldis** [comment]
Thanks for reporting that! mLab was EOLd and didn't have a chance to migrate to a different platform

**Comment by agoldis** [comment]
Migrated to Atlas
