### ISSUE TITLE
Add a custom project name for a GitHub status

### ISSUE THREAD

**Issue by denis-domanskii** [sorry-cypress/sorry-cypress#212]
## What is this feature about (1 sentence)
Add a custom project name for a GitHub status.

## Why is it needed? What is the value? For whom do we build it?
At now a GitHub status is always contains "Sorry-Cypress-Tests" which is not convenient in case when several test packs exist and user needs to differ them (e.g. E2E tests, Component Tests, Screenshot tests).

![image](https://user-images.githubusercontent.com/61494460/99959059-70c3e800-2d9b-11eb-8a8a-be2bd8348ee0.png)
_(current status representation on a GitHub.com)_

## High-level feature overview
I propose to add a new field into a hook setup screen, where user can define a custom project name which will be used instead of "Sorry-Cypress-Tests" text in a GitHub status. 

![image](https://user-images.githubusercontent.com/61494460/99959238-af59a280-2d9b-11eb-86a1-6e202025a911.png)
_(current hook setup screen)_

## Other
I'll try to contribute into it in a nearest month.

**Comment by agoldis** [comment]
Resolved in https://github.com/sorry-cypress/sorry-cypress/releases/tag/v1.0.0-beta.11 via #222
