### ISSUE TITLE
Return Run URL from API call

### ISSUE THREAD

**Issue by tim-sendible** [sorry-cypress/sorry-cypress#213]
- [x] I have seached issues for similar feature requests

## What is this feature about (1 sentence)
Provide a way to save the autogenerated run URL as a Jenkins variable so that I can use it in internal reporting.

## Why is it needed? What is the value? For whom do we build it?
My Jenkins job outputs the results to slack. At the moment, all I can produce is a pass/fail result, but I'd like to be able to provide the user with a direct link to the dashboard results. If I can extract the value as a variable, I can pass it through to slack.

## High-level feature overview
At the moment, the run URL is punted into the jenkins console in this manner:
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:      5.3.0                                                                            │
  │ Browser:      Chrome 86 (headless)                                                             │
  │ Specs:        1 found (cc/yy.feature)                                                                   │
  │ Params:       Tag: false, Group: false, Parallel: true                                         │
  │ Run URL:      https://domain.tld/run/08bb75579333b3cc51c70eb189949ff2            │
  │ Experiments:  experimentalFetchPolyfill=true,experimentalNetworkStubbing=true                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
But I can't find a sane way to scrape that from the jenkins logs.

Instead. Is there an API call I can do that returns just that URL value.. perhaps based on the build ID?

**Comment by agoldis** [comment]
```
curl 'https://sorry-cypress-demo-api.herokuapp.com/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://sorry-cypress-demo-api.herokuapp.com' --data-binary '{"query":"query getRuns($filters: [Filters]){\n  runs (filters: $filters) {\n    runId\n  }\n}","variables":{"filters":[{"key":"meta.ciBuildId","value":"cypress-test-0050"}]}}' --compressed
```
