### ISSUE TITLE
Is mongodb the only supported DB?

### ISSUE THREAD

**Issue by mnovich** [sorry-cypress/sorry-cypress#217]
Was looking to leverage this but the org doesnt support mongo - postgres, couchbase or anything OOB from amazon.
would  any of those work or is there a driver to drop in to use something else similar to the minio driver for storage? (we will likely use s3)

**Comment by agoldis** [comment]
Only mongo is supported at this time. Check out https://github.com/sorry-cypress/sorry-cypress/issues/133 as well
