### ISSUE TITLE
Problems in save runs in AWS 

### ISSUE THREAD

**Issue by guidiego** [sorry-cypress/sorry-cypress#218]
## Summary
I have deployed a AWS Cloudformation today, I change the API from Cypress to hit my dashboard. When I run this command:

`yarn cypress run --record --key test1` I have no saves at the end

When I run this command: 

`yarn cypress run --parallel --record --key test1 --ci-build-id test-run-001`

I get this error:

<img width="888" alt="Screenshot 2020-12-07 at 21 11 47" src="https://user-images.githubusercontent.com/10289071/101420412-d7cfb980-38d0-11eb-8b0d-fb79c6cc97e0.png">

## How to reproduce
- Deploy AWS Cloud Formation
- Change you api_url to the Cloud Formation ones
- Run the previous comment that I've done

## Environment

- sorry-cypress version: latest
- cypress version: 5.6
- platform: AWS Cloud Formation
- service: all

**Comment by agoldis** [comment]
Seems like the some service returns 302.
Please make sure you're using director service url when configuring cypress agents.
You can also run the agents with `DEBUG=cypress:*` to see what specific request is triggering that error 302. 

Please share your results, we'll follow up with next steps

**Comment by guidiego** [comment]
@agoldis In case I need to add Director URL in some place? Docs ask only to add API url in app.yml

**Comment by agoldis** [comment]
Right, updated the docs
