### ISSUE TITLE
wiki(s3-setup): update CORS config from XML to JSON

### ISSUE THREAD

**Issue by lucasltinoco** [sorry-cypress/sorry-cypress#219]
[In the new S3 console, the CORS configuration must be JSON.](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html)

Here's the configuration I have working in JSON, just need to update [this page](https://github.com/sorry-cypress/sorry-cypress/wiki/S3-screenshot-bucket-setup-instructions): 

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "POST",
            "GET",
            "PUT",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by agoldis** [comment]
Awesome! https://sorry-cypress.dev/installation/aws#manually-setup-s3-bucket-for-screenshots-and-videos

**Comment by agoldis** [comment]
@all-contributors please add @lucasltinoco for documentation
