### ISSUE TITLE
Sorry cypress Dashboard is defaulted to 8080, I want to change it to something else such as 5000. 

### ISSUE THREAD

**Issue by preetibellad** [sorry-cypress/sorry-cypress#224]
## Summary
@agoldis 
Sorry cypress Dashboard is defaulted to 8080, I want to change it to something else such as 5000. 
How can I do it?

- platform: `docker r`
- service: `dashboard`

**Comment by agoldis** [comment]
Sure! Just make sure to provide `PORT` environment variable when starting the dashboard:
https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/dashboard/server/config.js#L3:L3

**Comment by preetibellad** [comment]
![image](https://user-images.githubusercontent.com/72126464/102114719-8ee3ac00-3e60-11eb-8e49-ae9b2c6b7d93.png)

When I do the same, below are the port exposed and dashboard listens on 8080 instead of 5000 and th dasboard does not open on localhost:5000
![image](https://user-images.githubusercontent.com/72126464/102114868-bcc8f080-3e60-11eb-8dbb-1c23775725ec.png)
