### ISSUE TITLE
Continuing from issue#224

### ISSUE THREAD

**Issue by preetibellad** [sorry-cypress/sorry-cypress#227]
https://github.com/sorry-cypress/sorry-cypress/issues/224#issue-765268413

![image](https://user-images.githubusercontent.com/72126464/102114719-8ee3ac00-3e60-11eb-8e49-ae9b2c6b7d93.png)

@agoldis When I do the same, below are the port exposed and dashboard listens on 8080 instead of 5000 and th dasboard does not open on localhost:5000
![image](https://user-images.githubusercontent.com/72126464/102114868-bcc8f080-3e60-11eb-8dbb-1c23775725ec.png)

_Originally posted by @preetibellad in https://github.com/sorry-cypress/sorry-cypress/issues/224#issuecomment-744595899_

**Comment by agoldis** [comment]
What service are you setting the port for?
It's supposed to be `dashboard` service https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.full.yml#L36

**Comment by preetibellad** [comment]
@agoldis I am setting 5000 for dashboard service
![image](https://user-images.githubusercontent.com/72126464/102170902-65a43980-3ebb-11eb-975b-4b2e6f27c9fa.png)
and I am executing docker-compose.mini.yml
![image](https://user-images.githubusercontent.com/72126464/102170999-8f5d6080-3ebb-11eb-9384-af339e93e507.png)

**Comment by agoldis** [comment]
@preetibellad you need to define `PORT` environment variable, like this:

```yml
dashboard:
  environment:
    PORT: 5000
```

**Comment by preetibellad** [comment]
@agoldis Previously I was running `Run docker-compose -f docker-compose.minio.yml` up now updated the `port `value as per your suggestion and ran `Run docker-compose -f docker-compose.full.yml` up. This worked, thanks.
Does mini and full version of the docker file make any difference?

**Comment by agoldis** [comment]
This is not `mini`, it is `minio`, please refer https://min.io/ for details, those are different in terms of storage being used.
