### ISSUE TITLE
Reduce dashboard memory usage

### ISSUE THREAD

**Issue by slinstaedt** [sorry-cypress/sorry-cypress#230]
Just for curiosity i monitored the memory usage of the cypress docker setup and was a little bit surprised, seeing the dashboard using around 200-250MB, while all the other are fine with 50-60MB. From my understanding the dashboard is only serving the client application (aka static files) to the browsers. Normally one would expect this is a job, a simple nginx with 5MB usage can handle. As infrastructure costs is mostly related to memory usage for sorry-cypress I would like to ask, if there is a chance to reduce the memory usage.

Could you give some insights, what the dashboard docker service is actually doing?

I have searched for similar issues. There is only one (#46) mentioning the high memory usage, but basically dealing with another topic.

**Comment by slinstaedt** [comment]
Sorry, had a duplicate post due to browser timeout.

**Comment by agoldis** [comment]
You're right, the service is very simple - it's just a node server that server pre-compiled assets.
How are you measuring the memory? One random idea is that the docker image is bigger than needed because of node modules or leftovers from the build process.

**Comment by slinstaedt** [comment]
Though I was talking about the runtime memory consumption, having a smaller image is also almost a nice idea ;) 

for the runtime memory I was using both classical `top`, and `docker stats`. Even though they might not be accurate, they will give you an idea especially in comparison to other processes.

Have you thought about using a multi-stage build for your images? They can potentially dramatically reduce the their size and depending on the runtime base image, you choose, also the memory usage.

**Comment by agoldis** [comment]
@slinstaedt sorry about slow response, I have been afk a lot last few weeks.

**Comment by slinstaedt** [comment]
Used some spare time during lockdown... feedback is welcome #249

**Comment by agoldis** [comment]
I guess this was resolved by #249
