### ISSUE TITLE
Projects settings are wiped after docker-compose images update 

### ISSUE THREAD

**Issue by denis-domanskii** [sorry-cypress/sorry-cypress#238]
## Summary

Projects settings are wiped after docker-compose restart. The reason is: proposed in Quickstart section docker-compose config named docker-compose.minio.yml doesn't contain persistent storage for mongo-db image. Therefore, we loose all database data after image update. 

In the same time, storage image in the same config have a persistent volume in config:
```
    volumes:
      - ./data/data-minio-cypress:/data
```

Moreover, k8s config is already have a volume config for mongo-db:
```
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
```

To fix the issue, we need to update relevant docker-compose configs and add volume setup into it.

## How to reproduce

Just stop services, pull new images and run updated version. 

## Environment

- sorry-cypress version: `v1.0.0-beta.11`
- cypress version: `6.1.0`
- platform: `docker`
- service: `all`

**Comment by denis-domanskii** [comment]
@agoldis I'll update yaml files if you fine with it. Updated setup will be look like:

```
  mongo:
    image: mongo:4.0
    volumes:
      - ./data/data-mongo-cypress:/data/db
```

**Comment by agoldis** [comment]
@DeniDoman sure! go ahead!
