### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by jpike88** [sorry-cypress/sorry-cypress#243]
- [x] I have seached issues for similar feature requests

## What is this feature about (1 sentence)
https://github.com/flotwig/cypress-log-to-output
https://github.com/bahmutov/cypress-failed-log
https://github.com/archfz/cypress-terminal-report

## Why is it needed? What is the value? For whom do we build it?
https://github.com/cypress-io/cypress/issues/448

This thread has been open forever about a better way to handle error reporting.

Cypress plugins are easy to develop, they're typically just one javascript file.

I think this is add HEAPS of value to the project:

- A simple plugin that attempts to send onerror, unhandledException promise errors to the dashboard
- Show the logs alongside the relevant test

Thoughts?

**Comment by agoldis** [comment]
Thanks a lot for reporting that @jpike88. 

To make sure I understand properly, you are suggesting to capture console.logs from cypress runner and display it in the dashboard together with test results?

**Comment by jpike88** [comment]
Correct

**Comment by agoldis** [comment]
@jhicken is that somehow related to #140 and #141 ?

**Comment by jhicken** [comment]
Yup #140 for sure. This was the type of thing I was wanting to do with this.
