### ISSUE TITLE
Expose Prometheus metrics

### ISSUE THREAD

**Issue by tico24** [sorry-cypress/sorry-cypress#244]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Optionally expose Prometheus metrics to facilitate devops process improvement

## Why is it needed? What is the value? For whom do we build it?
As a devops engineer, I would like to analyse metrics from my CI test runs to pinpoint common failure points and to improve internal processes over time. I also want to keep Sorry Cypress running at its optimum within my Kubernetes cluster.

Prometheus is now the de-facto application metrics gathering tool in the container land, especially in Kubernetes. In order to integrate, applications expose a /metrics endpoint and the data can be scraped by Prometheus and exposed in Grafana. Aside from exposing the metrics in a defined syntax, there are no other dependencies to add to the product.

Traditionally, metrics would include resource usage information from the container (cpu/memory etc), but also information about runs. Pass/fail information, as well as number of runs and specific test failure counts.

## High-level feature overview
This is fairly well documented on the net, so I won't re-invent the wheel. To give you an example to look at, I'm assuming you use Jenkins... install the [Prometheus Plugin](https://plugins.jenkins.io/prometheus/) for Jenkins and navigate to https://jenkins-url/prometheus

Ironically, because I use Jenkins for my CI, this already gives me some information for my Sorry Cypress jobs (pass/fail information), but won't be of use to people not using Jenkins, and the data should really come from the source if possible.

## Other
I'm nowhere near skilled enough to do the actual metrics gathering and exposure, but more than happy to help improving the helm chart with a Prometheus endpoint, and producing sample Grafana graphs.

**Comment by agoldis** [comment]
@tico24 interesting, that area is quite new to me.

It seems like it can be used as a generic metrics tools - not only to monitor infrastructure health and http responses. Am I right? 

In that case that's super-cool because it can simplify implementing testing analytics (one of the major features people want based on my survey)

**Comment by tico24** [comment]
Yeah that's exactly right. Personally I care less about the infra metrics in this case, but test metrics would be brilliant.
