### ISSUE TITLE
Test duration time continuous to count

### ISSUE THREAD

**Issue by Donaab** [sorry-cypress/sorry-cypress#245]
## Summary

Sorry cypress does X, but should do Y

## How to reproduce

- Go to https://sorry-cypress-demo.herokuapp.com/sorry-cypress/runs
- Confirm for several runs like for example cypress-test-0055
- Test duration is Duration: 6475 min, 7 sec
- 
<img width="1417" alt="Sorry-cypress dashboard 2020-12-24 19-56-28" src="https://user-images.githubusercontent.com/18293528/103103622-98b89c80-4622-11eb-8fec-b51741738e64.png">

## Environment

- sorry-cypress version: `<here>`
- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by agoldis** [comment]
thanks for opening that, there're few related issues #215 #142 #134. Hope to fix that soon

**Comment by agoldis** [comment]
Resolved in https://github.com/sorry-cypress/sorry-cypress/pull/292
