### ISSUE TITLE
is there a way to turn off the webhook functionality?

### ISSUE THREAD

**Issue by mnovich** [sorry-cypress/sorry-cypress#247]
internal information security wants us to disable it so curious if there is an easy way to do that.

**Comment by jhicken** [comment]
Yeah not right now. But it should be pretty easy to implement an env var that would turn them off or application setting.

**Comment by agoldis** [comment]
@mnovich isn't removing all webhooks enough?

**Comment by mnovich** [comment]
yes - that's what we plan to do in the easiest way possible.

**Comment by agoldis** [comment]
@mnovich so you want to hard-disable it and disallow the UI as well? That should be quite an easy task @jhicken thank for adding #firstissue label

**Comment by mnovich** [comment]
correct - disable UI and ability to have them altogether.
