### ISSUE TITLE
Enhance Generic WebHook

### ISSUE THREAD

**Issue by guidiego** [sorry-cypress/sorry-cypress#248]
Related: #149

## What is this feature about (1 sentence)
Give to people who wants use Generic Hook more data.

## Why is it needed? What is the value? For whom do we build it?
Recently I started to research about how could I use Sorry Cypress hooks to enhance my reporters in company Google Chats. I didn't found a documentation for it so I started to take a code look and find it:

https://github.com/sorry-cypress/sorry-cypress/blob/a082fb5f974c8ac6f74fb56edd541b079a49052a/packages/director/src/lib/hooks/genericReporter.ts#L6-L36

The hook only send useless informations. I think that we could send informations such as: 
- How many specs, failed or passed
- How many time a spec take at all
- If a spec fail the message that we print in Dashboard could be sent too

## High-level feature overview
- RUN_START
  - How many specs are running
- RUN_END
  - How many specs were runned
  - How many fails run get
  - How many success run get
- INSTANCE_START
  - Spec name in this instance
  -  How many specs were runned

## Other
We need to implement RUN_END because I only found RUN_START in code

**Comment by agoldis** [comment]
thanks for opening this issue, webhooks as is are actually pretty useful, but of course there's a lot of space for improvement.

> We need to implement RUN_END because I only found RUN_START in code

Please check out #215 

I am planning to invest some time into hooks after the holidays.

**Comment by guidiego** [comment]
@agoldis We are using SorryCypress here in my company and this enhances/RUN_END will be a great thing for us (we want to implement a bot that alert when switches fail). Let me know if I could help in something!

**Comment by xwchris** [comment]
> thanks for opening this issue, webhooks as is are actually pretty useful, but of course there's a lot of space for improvement.
> 
> > We need to implement RUN_END because I only found RUN_START in code
> 
> Please check out #215
> 
> I am planning to invest some time into hooks after the holidays.

Is this in progress?

**Comment by agoldis** [comment]
@xwchris yes, still working on that

**Comment by agoldis** [comment]
Wow, seems like the hook information was completely wiped out during a merge... fixing that and adding tests to avoid embarrassment

**Comment by olup** [comment]
Any progress on reverting the wipe ? I'd love webhooks with some data - right now it's just empty

**Comment by agoldis** [comment]
Resolved in https://github.com/sorry-cypress/sorry-cypress/pull/292
