### ISSUE TITLE
Reported by @michaelpistrang-vetro CI_URL on cloudformation

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#261]
I'm having some issues running the recent sorry-cypress code via cloudformation, and I believe it may be related to this change. (see stack trace below).

In my case it looks like CI_URL is a non-empty value since it makes it passed the validation but isn't in a tuple format so calling split() on it yields undefined for the url part.

Where do you expect CI_URL to be set in the scenario where sorry-cypress is being run via cloudformation, and the CI workflow is run via github actions cypress-io/github-action@v2?

If it would be appropriate I can open a new issue for this, but I'm not yet certain if I understand the correct usage for my scenario.

Thank you in advance for the help!

react-dom.production.min.js:209 TypeError: Cannot read property 'replace' of undefined
    at jr (ci.tsx:27)
    at Go (react-dom.production.min.js:153)
    at mu (react-dom.production.min.js:261)
    at cl (react-dom.production.min.js:246)
    at ul (react-dom.production.min.js:246)
    at Zu (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Vi (react-dom.production.min.js:122)
    at Wi (react-dom.production.min.js:123)

**Comment by agoldis** [comment]
@michaelpistrang-vetro I have updated the template, it's an env var for dashboard https://github.com/sorry-cypress/sorry-cypress/blob/master/cloudformation/sorry-cypress.yml#L476

**Comment by michaelpistrang-vetro** [comment]
Thank you!
