### ISSUE TITLE
Error when viewing a project

### ISSUE THREAD

**Issue by tico24** [sorry-cypress/sorry-cypress#264]
## Summary

When trying to view a project or runs, I just get noise.

## How to reproduce
Install a brand new sorry-cypress stack (using the docker:latest images). Run a test.
Go to view the run.

## Environment

- sorry-cypress version: `latest`
- cypress version: `6.1.0`
- platform: `docker (k8s)`
- service: `all`

Here is the error (I have obfuscated our sorry-cypress url)

Error:
kr@https://my-domain.com/index.mjs?f0270c0d0295183bc519:61:162937
Go@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:57930
mu@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:104169
cl@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:96719
ul@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:96642
Zu@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:93672
Wi/<@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:45314
t.unstable_runWithPriority@https://my-domain.com/index.mjs?f0270c0d0295183bc519:53:3844
Vi@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:45023
Wi@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:45261
qi@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:45194
Gu@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:90457
va@https://my-domain.com/index.mjs?f0270c0d0295183bc519:45:62276

**Comment by tico24** [comment]
Turns out this is caused by the CI_URL environment variable. 
If I set it to anything other than "" then the above occurs.

**Comment by tico24** [comment]
Even with the CI_URL set to "", if I go to edit a project and click "add hooks", I get the error as above.

**Comment by agoldis** [comment]
@tico24 should have been resolved by https://github.com/sorry-cypress/sorry-cypress/commit/d8c577593d43819072d44743ebc7dd915effa49c

**Comment by tico24** [comment]
@agoldis  Tested again by pulling down the latest docker images. This has now resolved both issues (valid and blank CI URL). Thanks
