### ISSUE TITLE
alternative for runners

### ISSUE THREAD

**Issue by mnovich** [sorry-cypress/sorry-cypress#274]
im strongly considering using kubernetes jobs to actually be my "agents" - one thing i thought was possible and is - you can override host files entries for a specific pod, https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/so thinking to simply  do that for pointing api.cypress.io to my sorry cypress https endpoint - that is slightly annoying only in that i was preferring to use the non-https internal cluster address but (and not mess make haproxy do any work)   Has anyone else tried that?

**Comment by agoldis** [comment]
I think you can absolutely do that! I did try to do that Google Cloud, but didn't have time to actually complete the experiment. 

Maybe @tico24 and @fsmaia can comment on this approach?

**Comment by tico24** [comment]
You should be able to do that, yes. It might be easier to add a rewrite rule to your coredns configmap that points that url to your relevant kubernetes service.  This would then work across your whole cluster.

**Comment by agoldis** [comment]
@mnovich I am closing this one as it doesn't imply any action at the time. If you want to explore that further please consider joining our slack channel.
