### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by stobias123** [sorry-cypress/sorry-cypress#277]
## Summary
Getting timeouts trying to upload in k8s.

s3 driver per the docs, minio backend.

Cypress returns 504. and seeing the below error in director logs.

```
(node:1) UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at Timeout.connectTimeout [as _onTimeout] (/app/node_modules/aws-sdk/lib/http/node.js:69:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by agoldis** [comment]
To make sure, you're using minio as a gateway to S3? 
If that's the case, you'd use minio driver https://docs.sorry-cypress.dev/configuration/director-configuration#remote-storage-configuration

I will update helm charts to reflect that

**Comment by agoldis** [comment]
Oh, it's actually already in-progress: https://github.com/sorry-cypress/charts/pull/41/files

**Comment by stobias123** [comment]
I'm not using minio as an s3 gateway. 

Minio is my object store.

**Comment by agoldis** [comment]
@stobias123 Fixed Slack link. Thanks for pointing out!

**Comment by agoldis** [comment]
Did you manage with minio setup?

**Comment by stobias123** [comment]
@agoldis  - Yes but using minio driver. 

We can close this issue, I misunderstood, thinking the above might be an issue with s3 driver, but I should've been using minio driver. I made some tweaks to my deployment to match docker compose and things worked out.

FWIW - I'm running cypress outside of cluster, and had to use `kubefwd` to get uploads to work, since the `MINIO_ENDPOINT` is an in-cluster service url. Very similar to host file hack mentioned in docs.

Once https://github.com/sorry-cypress/charts/pull/41/files is closed out I'll revisit and validate.

**Comment by agoldis** [comment]
@stobias123 I was trying to resolve this issue. The challenge is that signed urls for image uploads have the hostname encoded in signature. Director get signed URL from minio using internal hostname - and cypress agents are forced to use the same hostname.
