### ISSUE TITLE
Parallelization stopped working after update to CY 6.3.0 or higher

### ISSUE THREAD

**Issue by E7ranger** [sorry-cypress/sorry-cypress#278]
Sorry cypress stopped working after update to 6.3.0 or higher. Still working on 6.2.1.

I'm using cypress with docker using cypress included images and one liner for re-routing to sorry cypress director service
`sed -i -e 's|api_url:.*$|api_url: "http://10.11.12.13:1234/"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml`

Then after run started in jenkins with `docker run cypress/included:6.4.0 run test -- --browser chrome --headless --parallel --record --key XXXX --ci-build-id XX` I see in logs message that says that I'm trying to connect to cypress-dashboard instead sorry-cypress.
`You passed the --record flag but did not provide us your Record Key.`

Could you please advise what can be the reason?

- sorry-cypress version: latest
- cypress version: 6.3.0 +
- platform: docker
- service: all

**Comment by agoldis** [comment]
I was able to run with 6.3.0 - 6.5.0. Please double check your configuration.
