### ISSUE TITLE
Add bitbucket hooks

### ISSUE THREAD

**Issue by stobias123** [sorry-cypress/sorry-cypress#281]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Send build status hooks to bitbucket
## Why is it needed? What is the value? For whom do we build it?
For me and other bitbucket users.
## Other
Already implemented in #279  - just creating the issue for tracking, discussion and others to see.

**Comment by agoldis** [comment]
Resolved in https://github.com/sorry-cypress/sorry-cypress/pull/292
