### ISSUE TITLE
Changing name might improve adoption

### ISSUE THREAD

**Issue by kirtangajjar** [sorry-cypress/sorry-cypress#282]
Hey there :wave: 

Absolutely love the work done here. Just had a small suggestion, the current name sometimes scares people a little bit(happened today with my manager), gives a hacky-side-project feel and seems a little risky as cypress.io could jinx this project because of trademark/copyright violations, especially since there is also a cloud based paid service.

So just thought to put it out here. LMK your thoughts :smiley:

**Comment by agoldis** [comment]
Good point. It is indeed a provocative name that was picked at random just when the project started. Having a more conventional term would help.

I am moving this issue to a discussion board. Mid / long term we'll probably change the name. I am also looking for legal advice on that manner.
