### ISSUE TITLE
Director service is ready at http://0.0.0.0:1234

### ISSUE THREAD

**Issue by debbiehawkes** [sorry-cypress/sorry-cypress#284]
I'm testing out sorry-cypress on my local machine and when I try to run it, is saying that the Director server is ready at http://0.0.0.0:1234/. 

```
docker run agoldis/sorry-cypress-director
🚀 Director service is ready at http://0.0.0.0:1234/...
```

**How to reproduce**
Execute the following command: docker run agoldis/sorry-cypress-director

**Environment**
sorry-cypress version: latest version
cypress version: 6.5.0
platform: docker
service: director

**Comment by muhkuh2005** [comment]
I am not affiliated to the dev's but I must admit that I don't see anything wrong with that.
0.0.0.0 is pretty common and defines that it is running on "all interfaces". So any ip/domain that points to your server.

The Director itself is only where your cypress runner asks for jobs to do.
It does not offer the API nor Webinterface. If you'd like to run the entire "standalone ecosystem" you'll have to use more than just the director.
An example can be seen at the `docker-compose.minio.yml`. It uses MinIO as the filestorage and mongodb as it's database.

**Comment by agoldis** [comment]
@debbiehawkes yeah, what's the actual problem :) ?

**Comment by debbiehawkes** [comment]
Human error here! Thanks for replying!
