### ISSUE TITLE
Enable CORS configuration on api

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#286]
A follow up from https://github.com/sorry-cypress/sorry-cypress/issues/121

**Comment by darko711** [comment]
@agoldis actually i don't have issues with CORS in OpenShift anymore. It was an issue with a wrong configured mongodb container, which then throw an error with the CORS errorMsg. For me this issue can be closed.

**Comment by agoldis** [comment]
Closing in favor of https://github.com/sorry-cypress/sorry-cypress/discussions/306
