### ISSUE TITLE
AWS ECS tasks not starting up on beta 16

### ISSUE THREAD

**Issue by KyleThenTR** [sorry-cypress/sorry-cypress#290]
## Summary

Tried to upgrade to beta 16 this morning and none of the AWS ECS tasks are starting up. They get stuck in pending and then end up stopping. Attached are the logs in cloudwatch for the tasks.

[log-mongo-task.xlsx](https://github.com/sorry-cypress/sorry-cypress/files/6084376/log-mongo-task.xlsx)
[log-dashboard-task.xlsx](https://github.com/sorry-cypress/sorry-cypress/files/6084377/log-dashboard-task.xlsx)
[log-director-task.xlsx](https://github.com/sorry-cypress/sorry-cypress/files/6084378/log-director-task.xlsx)
[log-api-task.xlsx](https://github.com/sorry-cypress/sorry-cypress/files/6084379/log-api-task.xlsx)

## Environment

- sorry-cypress version: `<here>`
- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by agoldis** [comment]
@KyleThenTR  I was able to run it on my AWS account: http://sc-0304-676789617.us-east-1.elb.amazonaws.com/
What do ECS events log say? Cloudwatch logs are all normal

**Comment by KyleThenTR** [comment]
@agoldis got it working today, it was because I was missing these environment variables for the dashboard https://github.com/sorry-cypress/sorry-cypress/commit/f6a9beadd75962fef474abaf8b5c85e1ccdeae36#diff-41f75e90b625dfc507e373eb71520efa754fbfcc6524df70b8fb8002ce1d0419R474-R477 (I was upgrading from beta 10). Wonder if there should be a changelog to track these types of changes that are required when upgrading versions?

**Comment by agoldis** [comment]
Yeah, good point, I am not disciplined enough to keep organized commits, but changelog would be useful for sure!
