### ISSUE TITLE
Getting MongoNetworkError: failed to connect to server [localhost:27017] on latest image of sorry-cypress director

### ISSUE THREAD

**Issue by pnilesh10** [sorry-cypress/sorry-cypress#293]
## Summary

With the latest release, when I start director image and do cypress run

23:46:44 (node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
23:46:44 (Use `node --trace-deprecation ...` to show where the warning was created)
23:46:44 (node:1) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
23:46:44     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
23:46:44   name: 'MongoNetworkError'
23:46:44 }]
23:46:44     at Pool.<anonymous> (/app/node_modules/mongodb/lib/core/topologies/server.js:438:11)
23:46:44     at Pool.emit (events.js:315:20)
23:46:44     at /app/node_modules/mongodb/lib/core/connection/pool.js:562:14
23:46:44     at /app/node_modules/mongodb/lib/core/connection/pool.js:995:11
23:46:44     at /app/node_modules/mongodb/lib/core/connection/connect.js:32:7
23:46:44     at callback (/app/node_modules/mongodb/lib/core/connection/connect.js:280:5)
23:46:44     at Socket.<anonymous> (/app/node_modules/mongodb/lib/core/connection/connect.js:310:7)
23:46:44     at Object.onceWrapper (events.js:422:26)
23:46:44     at Socket.emit (events.js:315:20)
23:46:44     at emitErrorNT (internal/streams/destroy.js:106:8)
23:46:44 (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

## How to reproduce
docker pull agoldis/sorry-cypress-director
docker run --name sorry-cypress-director -p 127.0.0.1:1234:1234/tcp agoldis/sorry-cypress-director
Cypress run command

## Environment
Cypress v 5.3.0
Ubuntu 14 & Ubuntu 18

- sorry-cypress version: `latest tag`
- cypress version: `5.3.0`
- platform: `docker`
- service: `director`

**Comment by agoldis** [comment]
@pnilesh10 sorry I was messing with the release, should be fixed now
