### ISSUE TITLE
After cypress upgrade to 6.6.0 version, it is not taking key values

### ISSUE THREAD

**Issue by dinuemani** [sorry-cypress/sorry-cypress#298]
## Summary

After cypress upgrade to 6.6.0 version, it is not taking key values
error message:
_**

> yarn run v1.22.5
> $ CYPRESS_APP_ENV=qa cypress run --env grep=non-registration --record --key 11 --parallel --ci-build-id firstrun1
> You passed the --record flag but did not provide us your Record Key.
> 
> You can pass us your Record Key like this:
> 
>   cypress run --record --key <record_key>
> 
> You can also set the key as an environment variable with the name CYPRESS_RECORD_KEY.
> 
> https://on.cypress.io/how-do-i-record-runs
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**_

## How to reproduce

1. upgrade cypress to 6.6.0 version and run the parallel command
## Environment

- sorry-cypress version: `1.0.0-rc.1`
- cypress version: `6.6.0`
- platform: `docker `
- service: `api | director | dashboard | all`

**Comment by agoldis** [comment]
@dinuemani we have users running cypress 6.8.0 and up, it must be something with how you're running cypress. e.g.
```
cypress run --record --key xxx --parallel --ci-build-id firstrun1
```
works

**Comment by dinuemani** [comment]
i tried to start the director from sorry-cypress and it shows this.. am i doing anything wrong in starting the server?
this with sorry-cypress rcbuild("version": "1.0.0-rc.1"):
$ docker run -p 1234:1234 agoldis/sorry-cypress-director
🚀 Director service is ready at http://0.0.0.0:1234/...

but when i run with beta version("version": "1.0.0-beta.16"):
when i run this command, it works (docker-compose -f docker-compose.minio.yml up)

please let me know if ddocker-compose is needed for rc build asawell

**Comment by agoldis** [comment]
@dinuemani 

It's really up to you to decide how do you want to run the service. When running docker-compose you start all the services together. Running only `docker run -p 1234:1234 agoldis/sorry-cypress-director` only starts the director service - without the dashboard, persistence etc...
