### ISSUE TITLE
Build the uploadUrl without port specification

### ISSUE THREAD

**Issue by tpott519** [sorry-cypress/sorry-cypress#300]
- [x ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Allow the uploadUrl to be built without specifying a port.

## Why is it needed? What is the value? For whom do we build it?
Currently, it appears that the uploadUrl is built using the MINIO_PORT value. If a MINIO_PORT value is not provided then it appears to be defaulted to 9000. Unlike the readUrl, the uploadUrl cannot be overridden so it will _always_ contain a port number.  

In my stack, I have traefik setup with the docker provider. Any traffic being directed to _storage.mydomain.com_ will automatically be redirected to the 9000 port on the cypress-director container. Since the upload url is currently being constructed as _storage.mydomain.com:9000_ traefik will not properly direct this request. To get around this problem I run all of my gitlab runners on the same VM as the director container - and I put the runners in the same docker network as the directory container - then the runners are able to access minio via the container hostname:port (MINIO_ENDPOINT set to container hostname).

The benefit of allowing no port specification is that it provides more flexibility for stack integration. In my case, it would allow me to run my runners on a different server than minio.

## Other
I have tried setting MINIO_PORT to "" in the docker-compose but this also gets reset to 9000.

**Comment by agoldis** [comment]
Thanks for reporting that issue @tpott519 

I am wondering if setting the port to `443` or `80` would be a quick workaround? I can remove the port from the configuration of course. 

---

Also, does `traefik` allows generating signed upload URL with `storage.mydomian.com` hostname? 

The upload URL signature embodies `minio` the hostname, so cypress agents and director should be using the same hostname, otherwise the upload fails.

**Comment by tpott519** [comment]
Hmmmm - not sure. Good question. I can look into and ask the gurus I know :)

I currently have traefik setup to not accept any ports - so for me 80 and 443 won't work. I am sure there is a way to have it stripped off or ignored via traefik and this can be a work-around (I already have a work-around that is doing great - running the gitlab-runners in the same docker network as minio).

**Comment by agoldis** [comment]
Interesting... traefik should have **some** port open to be able to accept connections

**Comment by tpott519** [comment]
I apologize @agoldis  80 and 443 do accept traffic. Sorry for the confusion. I tried with 80 and it worked fine.

**Comment by agoldis** [comment]
@tpott519 np! Can I close the issue?

**Comment by tpott519** [comment]
Absolutely - I'll close it myself :)

Thanks for your help @agoldis !
