### ISSUE TITLE
Is there a way to set the `uploadUrl` for S3? I might be missing something, but since there is `S3_READ_URL_PREFIX`, I would expect there to be one for upload URL as well.

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#302]
Is there a way to set the `uploadUrl` for S3? I might be missing something, but since there is `S3_READ_URL_PREFIX`, I would expect there to be one for upload URL as well.

https://github.com/sorry-cypress/sorry-cypress/blob/97f69d3b4ff0a31e75ef016496027a6210bd0017/packages/director/src/screenshots/s3/s3.ts#L51-L52

However, it looks like that is not the case, and `uploadUrl` is hardcoded

https://github.com/sorry-cypress/sorry-cypress/blob/97f69d3b4ff0a31e75ef016496027a6210bd0017/packages/director/src/screenshots/s3/s3.ts#L14

_Originally posted by @eric-hc in https://github.com/sorry-cypress/sorry-cypress/discussions/301_

**Comment by testn** [comment]
So this can be closed now?
