### ISSUE TITLE
Missing data for runs in dashboard

### ISSUE THREAD

**Issue by bagedevimo** [sorry-cypress/sorry-cypress#310]
## Summary

Sorry cypress dashboard showing "No run found" when viewing the list of runs, despite me creating a run (the project was just created)

## How to reproduce

I just updated to 1.0.0rc2 and nuked my MongoDB database (and recreated)

## Environment

- sorry-cypress version: `1.0.0rc2`
- cypress version: `7.0.0`
- platform: `docker via heroku`
- service: `dashboard`
- 
![image](https://user-images.githubusercontent.com/1319813/113807478-50c81a80-97b8-11eb-8177-9b0babb2669d.png)

<img width="819" alt="image" src="https://user-images.githubusercontent.com/1319813/113807508-5d4c7300-97b8-11eb-8d83-c9d743bc0116.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1319813/113807522-689f9e80-97b8-11eb-8aa1-5f11750fb7ed.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/1319813/113807592-8a008a80-97b8-11eb-9d57-05d188950d54.png">

**Comment by bagedevimo** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/1319813/113807676-b3211b00-97b8-11eb-9971-b94cc6ec03dd.png">

Just found this in the console - investigating if I've got a version mismatch.

**Comment by agoldis** [comment]
@bagedevimo thanks for reporting that! Please let me know what you've found.
- Is `run.meta.ciBuildId` present? 
- Confirmed cypress 7.0.0 works as usual https://sorry-cypress-demo.herokuapp.com/run/bc3a8ba7fd7307f408d73623c773612a
- Please make sure that the you have indexes recreated properly as in https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/lib/mongo.ts

**Comment by bagedevimo** [comment]
Huh - the indexes are missing! Is there a simple way I have the director recreate these?

**Comment by bagedevimo** [comment]
![image](https://user-images.githubusercontent.com/1319813/113940033-f038ec00-9850-11eb-9d6b-47e3c8a2eaa7.png)

We are indeed missing run.meta.ciBuildId! I'm invoking via cy2, could this be the cause?

**Comment by agoldis** [comment]
> Huh - the indexes are missing! Is there a simple way I have the director recreate these?

Restarting the director should trigger indexes recreation

> We are indeed missing run.meta.ciBuildId! I'm invoking via cy2, could this be the cause?

Shouldn't be, it just passes down all the arguments to `cypress`, also it's been used by quite a few orgs already - they'd file an issue. 
For some reason `ciBuildId` wasn't populated while creating a run. 

Let me ask a few more questions:
- Is it reproducible?
- What exact command are you using to create a run?
- Are other `meta` props missing?
- Do you have logs trace handy?

**Comment by bagedevimo** [comment]
* It's happening on every new build

* Here are the commands we use to create builds, run via GitLab CI
```CYPRESS_API_URL=https://de-sorry-cypress.herokuapp.com/ yarn cy2 run --browser chromium --headless -c numTestsKeptInMemory=0,retries=3 --record --key <censor> --parallel ````

Note that before this step, I do the following:

```
    - rm -rf .git # Prevents cypress sending secrets to dashboards
    - mount -o remount,size=2G /dev/shm # Fixes a bug with docker
    - cd /app
    - yarn cypress verify
    - bundle exec rake db:create db:schema:load
    - bundle exec rails db:fixtures:load FIXTURES_PATH=spec/fixtures
    - nohup bundle exec rails server &
    - yarn wait-on --interval=5000 --timeout=120000 "http://localhost:3000/"
```

* Other meta values seem to be present

![image](https://user-images.githubusercontent.com/1319813/113942387-d00b2c00-9854-11eb-8867-c66d19bd8121.png)


* We're on Heroku, which I'm not super familiar with, but might check into it now. I can definitely get live logs and reproduce, if necessary.

**Comment by agoldis** [comment]
@bagedevimo when you look at director logs on heroku, you'd see something like:

```
>> Machine is joining / creating  a run { ciBuildId: '1617834710', group: null }
```

Would be helpful to see this output

**Comment by bagedevimo** [comment]
```
2021-04-07T22:34:33.910120+00:00 app[web.1]: >> Machine is joining / creating  a run { ciBuildId: null, group: null }

2021-04-07T22:34:33.944514+00:00 app[web.1]: << Responding to machine {

2021-04-07T22:34:33.944516+00:00 app[web.1]:   groupId: 'null',

2021-04-07T22:34:33.944517+00:00 app[web.1]:   machineId: '353deb69-5150-4b33-ab98-9ee6f697204f',

2021-04-07T22:34:33.944518+00:00 app[web.1]:   runId: 'b513adb52089c12c14e53bca51b73f30',

2021-04-07T22:34:33.944518+00:00 app[web.1]:   runUrl: 'https://de-sorry-cypress-dashboard.herokuapp.com/run/b513adb52089c12c14e53bca51b73f30',

2021-04-07T22:34:33.944519+00:00 app[web.1]:   isNewRun: true,

2021-04-07T22:34:33.944520+00:00 app[web.1]:   warnings: []

2021-04-07T22:34:33.944520+00:00 app[web.1]: }
```

**Comment by agoldis** [comment]
ok, so probably it is `cy2` :) looking into

**Comment by bagedevimo** [comment]
Where is the ciBuildId derived from? I am nuking my .git dir, but I can't see how that'd be derived from that.

**Comment by agoldis** [comment]
> Where is the ciBuildId derived from? I am nuking my .git dir, but I can't see how that'd be derived from that.

`cypress` agent derives it from the environment, unless it is set explicitly https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/packages/server/lib/util/ci_provider.js#L643

**Comment by bagedevimo** [comment]
I can probably just set it manually as a workaround for now, then. Weird tho! It's like cy2 isn't letting cypress inherit the env var.

**Comment by agoldis** [comment]
If you can confirm that it works without cy2, it'd be awesome. You can use this command to rewrite cypress config:

```
sed -i -e 's|api_url:.*$|api_url: "https://yourmahcine>/"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml

```

**Comment by bagedevimo** [comment]
This is odd - even with a manually specified ci-build-id I still got no ciBuildIn.

![image](https://user-images.githubusercontent.com/1319813/113946799-5a578e00-985d-11eb-8a83-64c394c20ba7.png)

**Comment by bagedevimo** [comment]
Huh! Cancel that, it seems to be working with a manually specified ci-build-id - the URL in GitLab is weirdly broken up.

Checking without the manual specification and without cy2 now.

**Comment by bagedevimo** [comment]
![image](https://user-images.githubusercontent.com/1319813/113948144-55480e00-9860-11eb-9b52-9fc31b6aa94f.png)

```
    - "sed -i -e 's|api_url:.*$|api_url: \"https://de-sorry-cypress.herokuapp.com/\"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml"
    - yarn cypress run --browser chromium --headless -c numTestsKeptInMemory=0,retries=3 --record --key 7530ffec-c4db-41c5-a1df-a73c23af5e57 --parallel
```

![image](https://user-images.githubusercontent.com/1319813/113948218-7e689e80-9860-11eb-9e55-d63203c8c0e4.png)

**Comment by agoldis** [comment]
That's weird. 
```
 Machine is joining / creating  a run { ciBuildId: null...
```

Is the first log entry - it logs `ciBuildId` as is, as soon as the request received. That means that cypress sends the request with `ciBuildId=null`.

One thing you can do it to run cypress with `DEBUG=cypress:*` - that generates tons of data, but among the first few dozen lines should be the request as being sent by cypress.

**Comment by bagedevimo** [comment]
Sorry for the delay:

```
request to url: POST https://de-sorry-cypress.herokuapp.com/runs with params: {"body":{"ci":{"params":{"ciPipelineId":"283013736","ciPipelineUrl":"https://gitlab.com/delivereasy/delivereasy/-/pipelines/283013736","ciBuildId":"1161433352","ciJobId":"1161433352","ciJobUrl":"https://gitlab.com/delivereasy/delivereasy/-/jobs/1161433352","ciJobName":"cypress_integration 1/3","ciProjectId":"15646093","ciProjectUrl":"https://gitlab.com/delivereasy/delivereasy"
 ```

**Comment by bagedevimo** [comment]
Pretty sure this is the relevant record from Mongo

![image](https://user-images.githubusercontent.com/1319813/113950303-136d9680-9865-11eb-843b-32e42d93f633.png)

**Comment by agoldis** [comment]
@bagedevimo confirmed - it's a bug, just use explicit `ciBuildId`, I am working on a fix..

**Comment by agoldis** [comment]
https://github.com/sorry-cypress/sorry-cypress/releases/tag/v1.0.0-rc.3

**Comment by agoldis** [comment]
@bagedevimo did you have a chance to use rc-3?
