### ISSUE TITLE
Requesting a way to prioritize the test cases assigned to each thread 

### ISSUE THREAD

**Issue by natumkur** [sorry-cypress/sorry-cypress#316]
In order to achieve minimum time required to run complete test suite, it would be great to have a feature which helps us to specify the order in which test cases are assigned to the spawned threads.

**Comment by tbhi** [comment]
To clarify, is the request to specify the order manually or to have sorry cypress try and optimize for minimum run time?

**Comment by pedromateo** [comment]
I think "minimum run time" could be easily implemented by executing first those specs having a higher avg. duration; this data is already available in sorry-cypress DB. That way both "alphabetical order" (current) and "minimum runtime" options will be provided to users. 
I also see this feature critical to make the most of our CIs. 
@tbhi @natumkur

**Comment by t00** [comment]
What would also help is to have new and recently failed tests executed before recently passed tests, both also ordered by the average time to finish. Average duration should be stored per project per test name and recalculated every build with the current duration test so it won't deviate too far and the latest test will have equal weight as the previous average - to quickly adjust run time after fixes and regressions.

In short:
testDuration Table:
Project | Test | Duration | LastFailed

2 options:
Sort order: Name / Duration
☒ Run new and failed tests first

Every build:
1. When starting, for each project's test check if it exists in testDuration table. Depending on options order by duration/new (not present in testDuration table)/possibly move failed at the beginning.
2. Run tests and for each, when finished, update testDuration table entry: testDuration.duration = Average(testDuration.duration, current.duration) and a current test result
