### ISSUE TITLE
Cannot run parallel tests with cypress version above 6.6.0

### ISSUE THREAD

**Issue by Zaista** [sorry-cypress/sorry-cypress#318]
## Summary

Running parallel tests with cypress version 7.1.0 ends with the following error:

We encountered an unexpected error talking to our servers.
Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.
The --ciBuildId flag you passed was: test-1
The server's response was:
**StatusCodeError: 404** - `"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>**Cannot POST** /instances/94351169-79e6-442f-907f-b172b8e5fha2/tests</pre>\n</body>\n</html>\n"`

Last working cypress version 6.6.0

## How to reproduce

Run the tests normally like you would for older cypress versions

## Environment

- sorry-cypress version: latest
- cypress version: 7.1.0
- platform: docker
- service: director, api

## Example code:

-- Dockerfile
```
FROM cypress/included:7.1.0

COPY <test files>

RUN npm install
RUN sed -i -e 's|api_url:.*$|api_url: "http://host.docker.internal:1234/"|g' /*/.cache/Cypress/*/Cypress/resources/app/packages/server/config/app.yml

ENTRYPOINT ["npm", "run", "cy:test"]
```

-- package.json script
`"cy:test": "cypress run --parallel --record --key xxx --ci-build-id $CI_BUILD_ID",`

-- docker run command
`docker run --rm -e CI_BUILD_ID=test-1 cypress.image`

**Comment by agoldis** [comment]
@Zaista most likely you're not running the most recent version of sorry-cypress. Support for cypress 6.7.0+ was added in [1.0.0-rc.2](https://docs.sorry-cypress.dev/development/changelog#1-0-0-rc-2)

Here's an example run with cypress 7.1.0:
https://sorry-cypress-demo.herokuapp.com/run/82a054a91158b9837fff9d6159b32009

**Comment by Zaista** [comment]
I'm using the latest docker-compose.minio.yml file (ver 3.6) to spawn all the image: sorry-cypress:latest services.
I'm fairly certain it's up to date.
Could there be something else that I'm missing?

**Comment by CScharer** [comment]
I would suggest installing the cy2 (https://www.npmjs.com/package/cy2) package and using that rather than the sed command.  That's what I believe resolved my issue with this.

**Comment by Zaista** [comment]
Thanks for the suggestion. I tried it, tho I get the same error.

**Comment by agoldis** [comment]
> I'm using the latest docker-compose.minio.yml file (ver 3.6) to spawn all the image: sorry-cypress:latest services.
> I'm fairly certain it's up to date.
> Could there be something else that I'm missing?

Would you mind double checking the dashboard version - it's it the bottom left corner.

Also may be sharing the logs from director service

**Comment by Zaista** [comment]
You were right, I was running an older version. After I removed the built sorry-cypress images explicitly, it worked without issues.
Thanks a lot for the support.
