### ISSUE TITLE
Dashboard index.mjs MIME Type Blocked by Chrome

### ISSUE THREAD

**Issue by kevinmstephens** [sorry-cypress/sorry-cypress#321]
## Summary

- Sorry cypress dashboard returns `index.mjs` with `Content-Type: application/octet-stream`. 
- This file should be set as `Content-Type: application/javascript` so that browser MIME type checking doesn't block it.

Error seen in browser console:

"Refused to execute script from 'https://{hostname}/index.mjs?ABC123}' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled."

## How to reproduce

- You can run docker up per the instructions here: https://docs.sorry-cypress.dev/guide/dashboard-and-api#persisting-test-results
- Enter the localhost URL for the dashboard. In networking in chrome dev tools you can see the content type response headers. I do not get the MIME type error when running locally. But we do get it on our deployed service on AWS Fargate.

## Environment

- sorry-cypress version: `v1.0.0-rc.5`
- cypress version: `unknown`
- platform: `docker | aws fargate`
- service: `dashboard`

**Comment by agoldis** [comment]
Related https://semisignal.com/serving-mjs-files-with-nginx/

**Comment by agoldis** [comment]
Closed in #322

**Comment by kevinmstephens** [comment]
@agoldis Thanks!!!!
