### ISSUE TITLE
tests failing on cypress 7.1.0 while running parallel 

### ISSUE THREAD

**Issue by dinuemani** [sorry-cypress/sorry-cypress#323]
## Summary

our tests are failing when we upgraded to cypress 7.1.0 with below error. it was working fine with 6.6.0 while running them parallel using sorry-cypress

## How to reproduce

1. upgraded to cypress 7.1.0
2. changed the production url in app.yml under 7.1.0 version too
3. Ran this command locally "docker-compose -f docker-compose.minio.yml up"
4. ran this command to run cypress tests ""**_cy:run-parallel_grep": "CYPRESS_APP_ENV=qa CYPRESS_RECORD_KEY=11 cypress run --env grep=critical --parallel --record --ci-build-id first_run6522_**"
5. In dashboard it show tests are running but it does nothing and duration of test execution doesnot stop

error:
 **_Running:  data-quality/vertical/dataquality-create-range-spec.js                         (2 of 32)
        Just tests tagged with: critical
We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: first_run6522

The server's response was:

StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /instances/96918c47-0759-4e49-8587-72110106b105/tests</pre>\n</body>\n</html>\n"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._**

## Environment

- sorry-cypress version: `"version": "1.0.0-rc.1 and "1.0.0-rc.7""`
- cypress version: `7.1.0`
- platform: `docker / running locally` 
- service: `all`

**Comment by dinuemani** [comment]
is there anything iam missing in the steps? i was running them locally.. i tried with rc-7 too

**Comment by agoldis** [comment]
What's your cypress configuration? Are you using the correct endpoint?

Check out cy2 npm package - it might help

**Comment by dinuemani** [comment]
i tried with cy2 package, still seeing same error. below are steps and configurations

here is my configuration:
~/Library/Caches/Cypress/7.1.0/Cypress.app/Contents/Resources/app/packages/server/config
cat app.yml 
default:
  cdn_url: https://cdn.cypress.io
  desktop_url: https://download.cypress.io/desktop
  desktop_manifest_url: https://download.cypress.io/desktop.json
  chromium_url: https://download.cypress.io/chromium
  chromium_manifest_url: https://download.cypress.io/chromium.json
development:
  api_url: http://localhost:1234/
  on_url: http://localhost:8080/
test:
  api_url: http://localhost:1234/
  on_url: http://localhost:8080/
staging:
  api_url: https://api-staging.cypress.io/
  on_url: https://on.cypress.io/
production:
  api_url: http://localhost:1234/
  on_url: https://on.cypress.io/

steps:
1. install cy2 "**yarn add -D -W cy2**"
2. typed "**export CYPRESS_API_URL=http://localhost:1234/**"
3. ran this command :   "**cy:run-parallel_grep": "CYPRESS_APP_ENV=qa CYPRESS_RECORD_KEY=11 cy2 run --parallel --record --env grep=critical --ci-build-id `date +%s`**"

this is i see in sorry-cypress log:
director_1       | >> Machine is joining / creating  a run { ciBuildId: '1619125349', group: null }
director_1       | << RUN_START hook called
director_1       | << Responding to machine {
director_1       |   groupId: '1619125349',
director_1       |   machineId: '29b5894a-9efa-4c3a-9710-db849ceda187',
director_1       |   runId: '10452bbdd47052c6e3c87600a329d2c0',
director_1       |   runUrl: 'http://localhost:8080/run/10452bbdd47052c6e3c87600a329d2c0',
director_1       |   isNewRun: true,
director_1       |   warnings: []
director_1       | }
director_1       | >> Machine is requesting a new task {
director_1       |   runId: '10452bbdd47052c6e3c87600a329d2c0',
director_1       |   machineId: '29b5894a-9efa-4c3a-9710-db849ceda187',
director_1       |   groupId: '1619125349'
director_1       | }
director_1       | << INSTANCE_START hook called 675d12a8-64cf-44a7-afa1-983fbb0c4369
director_1       | << Sending new task to machine {
director_1       |   spec: 'exchange-e2e/integration/data-quality/vertical/dataquality-create-not-null-spec.js',
director_1       |   instanceId: '675d12a8-64cf-44a7-afa1-983fbb0c4369',
director_1       |   claimed: false,
director_1       |   groupId: '1619125349'
director_1       | }

**Comment by agoldis** [comment]
Please try running cypress in debug mode, e.g.:
```sh
DEBUG=cypress:server:api CYPRESS_API_URL=http://<sorry-cypress>/ cy2 run --record --key xxxx --parallel --ci-build-id `date +%s`
```

And look for strings like:
```
request to url: POST http://<sorry-cypress>/instances/f8547ca2-a2e0-4eea-963e-236af23896fa/tests with params:
...
request to url: POST http://<sorry-cypress>/instances/f8547ca2-a2e0-4eea-963e-236af23896fa/results with params:
```

`http://<sorry-cypress>` should be your server running sorry-cypress, it should be rc-2 or newer to support 7.1.0

**Comment by dinuemani** [comment]
thanks for quick replies, i was able to fix the issue.. looks like i had docker images with rc1 and when i updated it to rc7, for some reason it was taking rc1 images(mongo was taking 4.1 version instead of 4.2). when i deleted all the images(minio/mc, minio/minio, agoldis/sorry-cypress-dashboard, agoldis/sorry-cypress-api, agoldis/sorry-cypress-director, redis, mongo) and rerun the "**docker-compose -f ./docker-compose.minio.yml up**" it fixed the issue.

**Comment by agoldis** [comment]
Awesome
