### ISSUE TITLE
Automate release documentation

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#332]
- enforce conventional commits via eslint / gh actions
- build release notes from commits / PRs
- sync gitbook releases with GH releases

**Comment by aneeshrelan** [comment]
Can I take a stab at enforcing conventional commit? I was thinking to add pre-commit hooks and checking using commitlint? Can add Github actions (should it be on a pull_request?)

**Comment by agoldis** [comment]
@aneeshrelan sure! Please go ahead! Also take a look at release-it - seems quite handy
