### ISSUE TITLE
Regression run is getting stuck in between after sometime

### ISSUE THREAD

**Issue by vishnuprabhu-95** [sorry-cypress/sorry-cypress#333]
## Summary
Regression run is getting stuck in between after sometime

## How to reproduce
I have spec files which run more than 2hour and some spec files which run less than 1 hour. 
It's getting stopped inbetween the run. 
Can you please help with the same

- sorry-cypress version: R7
- cypress version: 7.1.0
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by vishnuprabhu-95** [comment]
![image](https://user-images.githubusercontent.com/63766633/116347943-c862f580-a80a-11eb-9e7d-11566b80c52f.png)

**Comment by vishnuprabhu-95** [comment]
Please provide solution.

**Comment by agoldis** [comment]
@vishnuprabhu-95 
The run being marked as timedout has been tracked in https://github.com/sorry-cypress/sorry-cypress/issues/299.
