### ISSUE TITLE
Cant easily docker run sorry-cypress-dashboard under unprivileged user

### ISSUE THREAD

**Issue by mathpaquette** [sorry-cypress/sorry-cypress#335]
## Summary

Should easily run nginx under unprivileged user
```
docker run --user 1000:998 --name dashboard cead3f3b1ed5
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: ERROR: /etc/nginx/templates exists, but /etc/nginx/conf.d is not writable
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/05/01 11:09:14 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2021/05/01 11:09:14 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

## How to reproduce

docker run --user `<unprivileged user>` --name dashboard sorry-cypress-dashboard

## Environment

- sorry-cypress version: `1.0.0.0-rc9`
- cypress version: `6.9`
- platform: `docker`
- service: `dashboard`

**Comment by mathpaquette** [comment]
@agoldis if you agree. Ill investigate and create a PR

**Comment by agoldis** [comment]
@mathpaquette of course :) Feel free to reach for any help!

**Comment by mathpaquette** [comment]
well, this is a bit more tricky than I initially thought... basically if I remove the user directive from /etc/nginx/nginx.conf, it will become insecure for those not running the container using unprivileged user. I dont want to force that in docker run, it looks like a bad decision. I might just end up providing a way for others to manage that in a README file or something. Any thoughts?

**Comment by agoldis** [comment]
Hmm... Why would it become insecure? 

Seems like using https://hub.docker.com/r/nginxinc/nginx-unprivileged and changing the ports is the most discoverable solution. May be just documenting the process would be enough. 

P.S.
I am not too familiar with best security practices for docker images, but why are is there a need for non-priveleged setup?  I mean, nginx starts as root and then switches to `nginx` user, it seems fine.

**Comment by mathpaquette** [comment]
@agoldis yes in theory there's no problem. The default implementation is fine. The problem happens when your docker daemon doesn't run as root and you need to run docker image unprivileged like in my case. Only root can listen on ports < 1024 and other security issues. Anyway, I dont really want change your setup I think its fine in 95% of cases. I have a workaround. Ill document it for others facing the same issue.

**Comment by agoldis** [comment]
@mathpaquette hey, did you have any chance to write down your discoveries?

**Comment by mathpaquette** [comment]
Documentation added here: https://docs.sorry-cypress.dev/cloud-setup/docker-images/running-sorry-cypress-dashboard-as-non-root-user
