### ISSUE TITLE
Dashboard run url

### ISSUE THREAD

**Issue by vaibhavi-jas** [sorry-cypress/sorry-cypress#346]
Once cypress test runs on the pipeline it gives a cypress run if we click on that link it gives false result..
If we take out the port number 8080 than its correct.
I have attach the screenshort ..Please have a look
<img width="1041" alt="Screenshot 2021-05-13 at 17 28 23" src="https://user-images.githubusercontent.com/79643177/118155983-bbe8ba80-b410-11eb-9494-546e5144879f.png">

**Comment by agoldis** [comment]
Please refer to https://docs.sorry-cypress.dev/configuration/director-configuration#common-configuration `DASHBOARD_URL` configuration
