### ISSUE TITLE
Cannot browse spec result on dashboard: Uncaught Invariant Violation: 3

### ISSUE THREAD

**Issue by ioana-gln** [sorry-cypress/sorry-cypress#357]
## Summary
When trying to open a spec result it hangs in the "Loading..." state. 

![image](https://user-images.githubusercontent.com/50579445/119236452-2f40a980-bb40-11eb-893f-2911e03aae52.png)

## How to reproduce
Run Docker compose with:  https://raw.githubusercontent.com/sorry-cypress/sorry-cypress/master/docker-compose.minio.yml on the local machine running docker.
## Environment

- sorry-cypress version: `1.0.0-rc.11`
- cypress version: `6.8.0`
- platform: `docker Engine 20.10.5| Docker Compose  1.29.0 | macOS Big Sur`
- service: `dashboard/api`

**Comment by ioana-gln** [comment]
Downgrading api and dashboard to 1.0.0-rc9 works fine.

**Comment by agoldis** [comment]
@ioana-gln apologizes, my bad. Fixed in rc.12
