### ISSUE TITLE
Screenshots and videos are not uploaded to the local minio storage

### ISSUE THREAD

**Issue by mivanov1989** [sorry-cypress/sorry-cypress#361]
## Summary

Screenshots and videos are not uploaded to the local minio storage. We use docker-compose.minio.yml.
Minio storage is empty:

![image](https://user-images.githubusercontent.com/39117346/119629342-9dbe8980-be16-11eb-9603-621b62469a5e.png)

Here's the docker-compose content:

version: '3.6'

services:
  mongo:
    image: mongo:4.2
    volumes:
      - ./data/data-mongo-cypress:/data/db

  redis:
    image: redis:alpine

  director:
    image: agoldis/sorry-cypress-director:1.0.0-rc.12
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'storage'
      MINIO_URL: 'http://sorry-cypress.nmdevsqa.com'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      ALLOWED_KEYS: 'wug'

      REDIS_URI: 'redis://redis:6379'
    ports:
      - 9644:1234
    depends_on:
      - mongo
      - storage
      - redis

  api:
    image: agoldis/sorry-cypress-api:1.0.0-rc.12
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:1.0.0-rc.12
    environment:
      GRAPHQL_SCHEMA_URL: http://sorry-cypress.nmdevsqa.com:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    hostname: 'storage'
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data
    ports:
      - 9000:9000

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add myminio http://storage:9000 MW32h3gd6HvjBEgTRx t6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc policy set download myminio/sorry-cypress;
      /usr/bin/mc policy set public myminio/sorry-cypress;
      exit 0;
      "

## How to reproduce

1. Run tests as usual on test hosts

ER: screenshots and videos are available for ran tests
AR: screenshots and videos are NOT available for ran tests

## Environment

- sorry-cypress version: 1.0.0-rc.12
- cypress version: 4.12.1
- platform: docker
- service: all

**Comment by agoldis** [comment]
Please attach logs from cypress agent and director.
Director should print snapshots URL and running cypress agent with `DEBUG=cypress:*` would show you errors for upload attempts

**Comment by mivanov1989** [comment]
@agoldis , director's log in the portainer shows nothing but only "[run-timeout] Checking run timeouts...". Here's cypress artifacts upload log for a test case in the attached file.
[ArtifactsUploading.txt](https://github.com/sorry-cypress/sorry-cypress/files/6551420/ArtifactsUploading.txt)

**Comment by mivanov1989** [comment]
I am trying with changed the storage hostname from "storage" to actual one:

![image](https://user-images.githubusercontent.com/39117346/119775878-e2a4f780-becc-11eb-9fcc-b1b95cf4a9f0.png)

**Comment by agoldis** [comment]
@mivanov1989 
I took a look at the logs, there're those lines:
```
cypress:server:api response { screenshotUploadUrls: [], videoUploadUrl: 'http://storage:9000/sorry-cypress/00d10a60-8e5b-41a6-8704-84bcb963e2ed.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MW32h3gd6HvjBEgTRx%2F20210526%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210526T211817Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=ad39394e0b9ffb03267f856a219eb71cc1afbdea9ac72022f67459ca96c43dab' }

2021-05-26T21:18:17.858Z cypress:server:record failed to upload artifact { file: 
```

a. You'd be able to review the log file and reproduce the network call, then figuring out why cypress agents are not able to reach your minio instance
b. Please read carefully `MINIO_ENDPOINT` configuration documentation at https://docs.sorry-cypress.dev/configuration/director-configuration#minio-configuration. Specifically

> Hostname or IP address that **both director and cypress agents** will use to communicate with minio service.

**Comment by lslavkov** [comment]
Maybe related to this issue but I am experiencing similar issue where I can't upload video and screenshots
```
director_1       | [run-timeout] Checking run timeouts...
director_1       | [run-timeout] Checking run timeout for runId: d3bd77d47ee778e86007f474ca455595, task id: 612f8858989f6d49c39edc94
director_1       | [run-timeout] Error checking run timeout for runId: d3bd77d47ee778e86007f474ca455595, task id: 612f8858989f6d49c39edc94
director_1       | AppError: AppError
director_1       |     at allRunSpecsCompleted (/app/packages/director/dist/execution/mongo/runs/run.controller.js:181:11)
director_1       |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
director_1       |     at async maybeSetRunCompleted (/app/packages/director/dist/execution/mongo/runCompletion/runCompletion.js:17:7)
director_1       |     at async checkRunCompletionOnTimeout (/app/packages/director/dist/execution/mongo/runCompletion/runCompletion.js:31:7)
director_1       |     at async /app/packages/director/dist/execution/mongo/runCompletion/runCompletion.js:56:7 {
director_1       |   code: 'RUN_NOT_EXISTS'
director_1       | }
```
