### ISSUE TITLE
Docker Image version that can be used in an isolated environment

### ISSUE THREAD

**Issue by michaelocomer** [sorry-cypress/sorry-cypress#363]
- [x ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Need to be able to run sorry-cypress tests in an environment that has no outside internet access.

## Why is it needed? What is the value? For whom do we build it?
Some UI elements (fonts, css, etc.) are not accessible within an isolated environment and cause issues with setting up sorry-cypress docker images

**Comment by agoldis** [comment]
@michaelocomer can you please elaborate on what issues are you seeing? AFAIK only fonts are being pulled externally. What else is missing?

**Comment by michaelocomer** [comment]
As I understand, there are google fonts, normalize.min.css (used in the dashboard), and someone that looked at it thought that they saw some javascript file being pull.  I did not see it but I'm not a UI developer so it's very possible I'm just not seeing it.

**Comment by agoldis** [comment]
Verified it is google fonts and normalize.css
