### ISSUE TITLE
Parallel Runs are added twice to mongodb (and shown in the dashboard)

### ISSUE THREAD

**Issue by Roemer** [sorry-cypress/sorry-cypress#371]
## Summary

Runing tests in parallel creates multiple runs with the same runId.

## How to reproduce

Run cypress tests with --parallel.
Open the dashboard
-> You see the same run multiple times, even in mongodb the run is in there twice.

## Environment

- sorry-cypress version: `1.0.2`
- cypress version: `6.6.0`
- platform: `docker / kubernetes`
- service: `all`

**Comment by agoldis** [comment]
@Roemer Can you please share your indexes from mongo - seems like indexes are missing thus duplicated entries are being created

**Comment by Roemer** [comment]
In the runs collection I see the following indexes:
![image](https://user-images.githubusercontent.com/393641/121133619-dc027280-c832-11eb-9b3b-17082f6acb2e.png)

**Comment by agoldis** [comment]
hm... not sure how the rest of indexes got removed. Please make sure you have those indexes in place

https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/mongo/src/db.ts#L51

**Comment by Roemer** [comment]
I deleted the sorry-cypress collection in mongodb, run the test again (parallel) and it recreated the collection but it only created the `_id_` index.

**Comment by Roemer** [comment]
I now stopped the director completely (scaled down to 0), deleted the database and restarted the director (scaled up to 1) and now it recreated the database correctly with the all indexes (4 of them in the run collection). So I think there is some combination of configuring / restarting the director that does not create the database initially and therefore the database is created implicitly when a testset is run and therefore of course without indexes.

**Comment by Roemer** [comment]
Ok i did play around with it more, I think the issue is that when director starts and mongodb is not available, it will not create the database but start anyway. In that case, I had to stop the director, wait until mongodb is ready, then start director and then director would create the database. So maybe director should not start if mongodb is not available?
