### ISSUE TITLE
Spec duration time is not valid 

### ISSUE THREAD

**Issue by mivanov1989** [sorry-cypress/sorry-cypress#372]
## Summary

Spec duration time is not valid - with the latest release 1.0.2 we see spec duration equals hours and days, whereas the whole run time is about an hour (valid). Also, the average spec run time looks valid as well. (please see attached screenshot and MongoDB dump).

![image](https://user-images.githubusercontent.com/39117346/121007265-811d3c80-c79a-11eb-8f76-4d46423b6624.png)

We also tried open the dashboard of different time zones but looks like it does not play the role.

## How to reproduce

Install the latest SC release 1.0.2 and run the Cypress test with it.

## Environment

- sorry-cypress version: `1.0.2`
- cypress version: `4.12.1`
- platform: `docker`
- service: `all`

MongoDB dump: [6072021.zip](https://github.com/sorry-cypress/sorry-cypress/files/6608350/6072021.zip)

**Comment by mivanov1989** [comment]
[](url)

**Comment by agoldis** [comment]
Resolved in https://github.com/sorry-cypress/sorry-cypress/pull/375
