### ISSUE TITLE
Move stateless director to a different repo

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#374]
The build process and code maintenance have diverged a lot.

**Comment by carlos0202** [comment]
@agoldis can you help me out to run stateless director or the steps to use example dashboard service until a valid solution for stateless director is found?

I'm currently trying to run it but got an unexpected error while testing using the example sorry-cypress Heroku app:
![image](https://user-images.githubusercontent.com/8674703/121066951-7792d500-c798-11eb-97f7-7d17528ff692.png)

**Comment by agoldis** [comment]
@carlos0202 sure, sorry just saw your message recently. You need to define environment variable CYPRESS_API_URL with an accessible director URL, for example `https://sorry-cypress-director.herokuapp.com`
