### ISSUE TITLE
Dashboard run url when we click leads to empty page instead of dashbord

### ISSUE THREAD

**Issue by vaibhavi-jas** [sorry-cypress/sorry-cypress#376]
<img width="1008" alt="Screenshot 2021-06-08 at 11 31 01" src="https://user-images.githubusercontent.com/79643177/121170457-25f85200-c84d-11eb-8f41-65fcc09c9f2b.png">
When cypress test run it gives dashboard run url. When we click that url than it lead to empty page instead of dashboard.
I have share the screen shot below.
can u please help me with this.

Sorry cypress does X, but should do Y

## Environment

- sorry-cypress version: `<here>`
- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`
[
<img width="1792" alt="Screenshot 2021-06-01 at 22 59 29 (1)" src="https://user-images.githubusercontent.com/79643177/121169416-e4b37280-c84b-11eb-96c0-4ceede67cbc0.png">
<img width="1792" alt="Screenshot 2021-06-01 at 22 59 29" src="https://user-images.githubusercontent.com/79643177/121169422-e715cc80-c84b-11eb-90eb-d53dd2dfa4a6.png">
<img width="1792" alt="Screenshot 2021-06-01 at 23 02 48" src="https://user-images.githubusercontent.com/79643177/121169433-ea10bd00-c84b-11eb-88c3-93075cb6d5a9.png">

](url)

**Comment by vaibhavi-jas** [comment]
<img width="1008" alt="Screenshot 2021-06-08 at 11 31 01" src="https://user-images.githubusercontent.com/79643177/121170557-4a542e80-c84d-11eb-9da2-80cfdda79fb5.png">
This is the dashboard run url

**Comment by agoldis** [comment]
@vaibhavi-jas 

Please make sure that you copy the whole run url, looking at your screenshot, the runId is too short - it is supposed to be 32 characters

<img width="992" alt="Screen Shot 2021-06-10 at 5 02 36 PM" src="https://user-images.githubusercontent.com/1637928/121612257-e4afa000-ca0e-11eb-97fc-219945eb8755.png">

For example, my terminal break the url in two parts, so I have to copy it all from the second line:
<img width="1150" alt="Screen Shot 2021-06-10 at 5 02 49 PM" src="https://user-images.githubusercontent.com/1637928/121612309-00b34180-ca0f-11eb-9316-5d769f2f7efb.png">

If you cmd-clicking the url, it won't consider the part after the line break
