### ISSUE TITLE
API  container now requires mongo env vars otherwise it fails

### ISSUE THREAD

**Issue by tico24** [sorry-cypress/sorry-cypress#380]
## Summary

Using `:latest`, the API deployment fails to load properly if you don't provide the mongodb information in the environment variables. Logs looks like this:
```
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/app/packages/mongo/dist/index.js:18783:34)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```
If I repeat the same using `:0.6.1`, I don't get an error.

The documentation implies that these should not be mandatory, and we wrote the sorry-cypress helm chart tests with this in mind. The tests now fail due to this. So I need to know if we should update the helm chart and it's tests (and the sorry-cypress documentation), or if this is a bug. Cheers.

## Environment

- cypress version: `n/a`
- platform: `docker`
- service: `api`

**Comment by tico24** [comment]
After discussion with @agoldis, this is intentional. In fact the previous way it worked was a bug.
We are updating our helm chart tests to accommodate now.

I wonder if it's worth updating the sorry-cypress documentation to make this clear though? So I'm not closing this issue yet.

**Comment by agoldis** [comment]
Updated the documentation, thanks @tico24
