### ISSUE TITLE
Slack notification with run finish event is not sent

### ISSUE THREAD

**Issue by zuzana-m** [sorry-cypress/sorry-cypress#383]
## Summary

Hello, I have configured a slack webhook in our sorry cypress dashboard. I have chosen **run finish** event for obtaining test results. I expect it to sent me a notification with summary of passed and failed tests after tests are finished. Unfortunately I have not received any.
When I select different event for sending notification like **run start** or **instance finished** I receive my messages.

## How to reproduce

Setup:

![screenshot 2021-06-17 o 9 35 37](https://user-images.githubusercontent.com/43915675/122355163-faaeea80-cf51-11eb-8ac3-60d1e6ce0d34.png)

## Environment

- sorry-cypress version: `1.0.3`
- cypress version: `6.6.0`
- platform: `docker`
- service: `api`

**Comment by agoldis** [comment]
Thanks @zuzana-m. Can you please share try to examine the associated run and see if https://github.com/sorry-cypress/sorry-cypress/blob/0ff44646fe6564cb6255bc9ea64b69578f23ee9b/packages/director/src/api/instances.ts#L154 can cause any trouble?

**Comment by zuzana-m** [comment]
Thank you for your reply @agoldis 

I've run tests again and looked to the logs of sorry-cypress_director.

Seems like all the tests finished, but RUN_FINISH event was not emitted. 

<img width="498" alt="screenshot 2021-07-05 o 19 38 34" src="https://user-images.githubusercontent.com/43915675/124505219-49b9a400-ddc9-11eb-8a6d-da967a919bb8.png">

```
[hooks] Reporting INSTANCE_FINISH for 0ae058cd0db6b9cfd1f2d849425002f6...
>> [not implemented] Received stdout for instance { instanceId: '11086aa9-fc5b-428b-a2c4-6ee46be66dde' }
>> Machine is requesting a new task {
  runId: '0ae058cd0db6b9cfd1f2d849425002f6',
  machineId: '97425030-ef30-48f2-a8a5-11f5fa1986cb',
  groupId: '6'
}
<< All tasks claimed {
  runId: '0ae058cd0db6b9cfd1f2d849425002f6',
  machineId: '97425030-ef30-48f2-a8a5-11f5fa1986cb',
  groupId: '6'
}
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeout for runId: 0ae058cd0db6b9cfd1f2d849425002f6, task id: 60e3427ba7ed34ea566d5a25
[run-completion] Run 0ae058cd0db6b9cfd1f2d849425002f6 timed out after 180 seconds. Created: 2021-07-05T17:33:47.973Z, now: 2021-07-05T17:36:57.524Z
[hooks] Reporting RUN_TIMEOUT for 0ae058cd0db6b9cfd1f2d849425002f6...
[run-timeout] Checking run timeouts...
>> Received instance result { instanceId: '2558390e-6a92-4be3-be78-017150f28984' }
<< Sending assets upload URLs {
  instanceId: '2558390e-6a92-4be3-be78-017150f28984',
  screenshotUploadUrls: [],
  videoUploadInstructions: null
}
>> [not implemented] Received stdout for instance { instanceId: '2558390e-6a92-4be3-be78-017150f28984' }
[hooks] Reporting INSTANCE_FINISH for 0ae058cd0db6b9cfd1f2d849425002f6...
>> Machine is requesting a new task {
  runId: '0ae058cd0db6b9cfd1f2d849425002f6',
  machineId: 'bce68f09-32b4-4466-ada1-97988962a5f8',
  groupId: '6'
}
<< All tasks claimed {
  runId: '0ae058cd0db6b9cfd1f2d849425002f6',
  machineId: 'bce68f09-32b4-4466-ada1-97988962a5f8',
  groupId: '6'
}
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
[run-timeout] Checking run timeouts...
```

Do you have any idea what could cause a problem?

**Comment by denis-domanskii** [comment]
@zuzana-m , bump Cypress version from 6.6.0 to 6.7.0 (better 6.9.1).

**Comment by agoldis** [comment]
Most chances related to #412

**Comment by zuzana-m** [comment]
Thanks so much! Increasing version to 6.7.0 has helped.
