### ISSUE TITLE
Feature Request: Test Analysis

### ISSUE THREAD

**Issue by mohsenny** [sorry-cypress/sorry-cypress#385]
- [x] I have searched issues for similar feature requests

## What is this feature about
What tests fail the most

## Why is it needed? What is the value? For whom do we build it?
To find out the most common failing test cases across certain branches, to get a sense of which tests are being the flakiest to fix.

## High-level feature overview
A `Test Analysis` option. After navigating into it we see a list of all failing test cases, sortable by
- Failure rate
- Failure count

And searchable by
- Branch name

**Comment by ImanMahmoudinasab** [comment]
I'm interested in this feature too with more useful info like:

- New failing tests compare to the last run
- Let users compare failing tests of any two test run results

@agoldis, any comment? What are the areas that would be involved? I may get some time to work on this feature.

**Comment by agoldis** [comment]
That mostly required saving the data in appropriate form that would fetching and presenting. Some form of aggregation per-test would would I think. 

Interesting problems to solve would be:

- Identifying a test. E.g. when we get a new test result, we need to "associate" it with existing test results. But that might be tricky. A naive approach would be to just use project + spec file name + test name.
- Keeping the data in form that would allow analysis and deriving metrics. In theory we can just keep all of the results individually,  in practice, after a few months of intense usage it'll bloat and the system will become slow. Some type of bucketing (in terms of mongo) with aggregated metrics seem like one of appropriate solutions.
- Presenting the data. This can simple or complex charts with drilldowns, don't really have any strong opinion. 

When I started the project I didn't think through about additional use cases except from parallelization as the result, the data isn't organized in optimal way.

**Comment by testingJava2** [comment]
Hello @ImanMahmoudinasab, @agoldis,

What do you guys think about adding some flakiness analysis here too?

Can be an average # of retries per spec; even better if maybe with the latest or, if even possible, the most common Error that is encountered during the retries(?) - if not possible, at least the average number of retries per spec would be great

Let me know your thoughts 🙂

**Comment by agoldis** [comment]
That seems useful, will take a look after v2
