### ISSUE TITLE
Add Tags field at Spec level , as a new column, next to the Group column

### ISSUE THREAD

**Issue by alexniculae** [sorry-cypress/sorry-cypress#388]
## What is this feature about (1 sentence)
Adding a Tags field at Spec level , as a new column, next to the Group column

## Why is it needed? What is the value? For whom do we build it?
Will allow user to add more context to the specs ran

## High-level feature overview
Add Tags field at Spec level , as a new column, either before or after the Group column

![sorry-cypress](https://user-images.githubusercontent.com/64204907/123438882-73a4e680-d5d1-11eb-9d3c-aeeb5a8d208b.png)

**Comment by ImanMahmoudinasab** [comment]
@agoldis, does the director record tags for specs on the DB? This is useful feature, and we need it too, also it is good idea to save browser name, version, screen size, ... as tags.

**Comment by alexniculae** [comment]
Hello,

Are we still interested in this, is it being considered as a feature for a future release, or should I allow the bot to close it next time it’s marked as stale?
