### ISSUE TITLE
Rollback in AWS Setup

### ISSUE THREAD

**Issue by GabRog** [sorry-cypress/sorry-cypress#389]
I tried to create setup in AWS like in [docs](https://docs.sorry-cypress.dev/cloud-setup/aws#cloud-formation). 
I have no idea, why setup ends with status ROLLBACK_COMPLETE instead of CREATE_COMPLETE.

**Comment by agoldis** [comment]
@GabRog Please share the events log, it's be an entry with specific configuration step failure

**Comment by agoldis** [comment]
@GabRog please let me know if you were able to get more details. Closing meanwhile
