### ISSUE TITLE
Reset groupId after "All tasks claimed" status received

### ISSUE THREAD

**Issue by alexneo2003** [sorry-cypress/sorry-cypress#390]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Consider dumping 'buildId' after gaining status "All tasks claimed"
```javatscript
<< All tasks claimed {
   runId: 'c2fd38c72fce524beff2fa8c31f6f36f',
   machineId: '0fc177d6-d9b3-4e29-825c-36515b37574d',
   groupId: '13'
}
```

## Why is it needed? What is the value? For whom do we build it?
I'm using multibranch Jenkins job 
For --ci-build-id i'm using env.BUILD_NUMBER and if i'm running build number coincides in different branches - sorry-cypress tells me that all specs is done in current build.
Of course i'm can combine, for example, env.BUILD_URL + env.BUILD_NUMBER but if i'm running task locally i'm needed always to change --ci-build-id in my command and it should be different than previously used

**Comment by agoldis** [comment]
That's going to be a breaking change, you can  prevent this problem by augmenting the unique build id with branch name or commit sha
