### ISSUE TITLE
Exclude a branch from a hook using wildcard characters

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [sorry-cypress/sorry-cypress#400]
-  [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Will allow users to exclude branches from a hook using a wildcard.

## Why is it needed? What is the value? For whom do we build it?
Some times instead of saying which branches should trigger a hook you need to say all branches except one or more specific branches should trigger the hook. 
This can for example help us to send slack messages in different channels base on the branch. (e.g. send test run result of `develop` branch on separate branch than tests of feature branches)

**Comment by ImanMahmoudinasab** [comment]
@agoldis I can work on this if you point out where is those wildcard checkers.

**Comment by agoldis** [comment]
https://github.com/sorry-cypress/sorry-cypress/blob/0d1cd14a4b9fa8556f3977207783fdb3b1ef687e/packages/director/src/lib/hooks/reporters/slack.ts#L185

**Comment by agoldis** [comment]
Thanks @ImanMahmoudinasab ! Please let me know if you need any help with that

**Comment by ImanMahmoudinasab** [comment]
My initial idea is to let users exclude branches using a `!` character at the begging of the filter:
```
!develop
!*-test
!release-20??-*
```

 `!` characters not in the begging of the filters would be ignored.

What do you think?

**Comment by agoldis** [comment]
@ImanMahmoudinasab sounds good. I'd stick to convention of glob patterns, e.g. https://www.npmjs.com/package/micromatch

**Comment by ImanMahmoudinasab** [comment]
@agoldis Please review the changes on #406 and let me know if anything could be improved.
