### ISSUE TITLE
🙏🏻 Help Needed: boldui -> Material-UI

### ISSUE THREAD

**Issue by YeonV** [sorry-cypress/sorry-cypress#401]
As part of Sorry Cypress v2.0, we are planning to migrate the dashboard to material UI as requested.

That's quite a big effort and I need your help. I believe that gradually we can migrate the whole project to Material UI. If you are interested in helping with migration, please comment below and start working on the corresponding screen.
 
@YeonV @conantteo @ImanMahmoudinasab @fsmaia 

## Development guide

- Add a comment below your GH nickname and what component would you like to work on
- Please fork off https://github.com/sorry-cypress/sorry-cypress/tree/feat/v2.0
- See [Development Guide](https://docs.sorry-cypress.dev/development/development-guide) to bootstrap the project
- Wrap the modified component in `WithMaterial` HOC. [Example](https://github.com/sorry-cypress/sorry-cypress/blob/feat/v2.0/packages/dashboard/src/project/projectsView.tsx)
- Open a PR to https://github.com/sorry-cypress/sorry-cypress/tree/feat/v2.0

## List of screens / components + volume of work
- [x] ~Update to material ui v5 (@agoldis)~
- [x] ~Layout (sm) (@ImanMahmoudinasab)~
- [x] ~Navbar (sm) (@ImanMahmoudinasab)~
- [x] ~Projects List (sm) (@ImanMahmoudinasab)~
- [ ] Projects Edit (md) (@karimould)
- [ ] Edit / Create Hooks (lg) (@karimould)
- [x] Runs Feed Screen (sm) (@ImanMahmoudinasab) 
- [x] Run Summary Component (md) (@ImanMahmoudinasab)
- [x] Run Details Screen (lg) (@ImanMahmoudinasab)
- [x] Spec Details Screen (md) (@ImanMahmoudinasab)
- [x] Test Details Screen (md) (@ImanMahmoudinasab)
- [x] Run / Spec / Test status badges (sm) (@ImanMahmoudinasab)
- [x] Run Progress Component (sm) (@ImanMahmoudinasab)
- [ ] Landing Page (sm) (@ImanMahmoudinasab)

p.s.
Sorry @YeonV I am piggybacking this issue.

**Comment by agoldis** [comment]
Thanks for opening the issue, I am totally down for moving to a better framework, please, Material UI or any other popular. It'd required some significant amount of refactoring though. Any help appreciated

**Comment by ImanMahmoudinasab** [comment]
here are some new designs, feedbacks appreciated:

![Web 1920 – 7](https://user-images.githubusercontent.com/5295554/131313736-73f0bf24-dcd8-4e99-875b-222ca75cc6db.png)

![Web 1920 – 8](https://user-images.githubusercontent.com/5295554/131313849-e28d0162-5aee-4e5c-9739-8d6380286865.png)

![Web 1920 – 3](https://user-images.githubusercontent.com/5295554/131313937-2aeeee80-79e0-47b8-afe3-857297621f23.png)

![Web 1920 – 9](https://user-images.githubusercontent.com/5295554/131314055-80baa4d9-e3ef-4c37-ac98-11197833164b.png)

**Comment by agoldis** [comment]
@ImanMahmoudinasab that looks great 🎉👍🏻🐬!!
 Are those just mocks or actually implemented screens? Don't be shy opening a PR with the work you've done already.

**Comment by ImanMahmoudinasab** [comment]
Thank you.😎🤘🤝

They are mocks. As the cost of changing mocks is less than the implementation, I will continue creating mocks for other pages/scenarios. and then would start implementation.

**Comment by agoldis** [comment]
@ImanMahmoudinasab hey, how is it going? Do you need any help? May be it worth starting with incremental implementation of the screens that are ready?

**Comment by ImanMahmoudinasab** [comment]
@agoldis, Hey, Everything is going well! spending my weekend in Victoria and working on the sidebar and header in my spare time! :) 

I finished the design of the screens, and you can see the last version [here 🎨](https://xd.adobe.com/view/63718818-7736-4686-be0d-45dcf4a42671-3622/).

I have started the implementation of the sidebar. I need couple more days to wrap it up (making it mobile-friendly).

<br>

> Do you need any help?

I want to let users pick a color for every project and use that color in different areas (check mocks 🎨). It would be good to have that field on the database and get it from the projects hook, and being able to save it on the DB.

**Comment by agoldis** [comment]
Thanks @ImanMahmoudinasab 

I think I am going to move ahead with the rollout of v2 - I want to get feedback about the new version because there's a backlog of PR I am gonna need to port onto v2.

**Comment by ImanMahmoudinasab** [comment]
> I think I am going to move ahead with the rollout of v2

Good idea! We can update material UI to the latest version (they have changed the package name) before more folks using it on their branches in order to migrate sorry cypress to MUI.



> re: pick color, I will try helping with that after I finished with v2 rollout

Thank you!

**Comment by jdileonardo** [comment]
@ImanMahmoudinasab 

At the risk of feature creep I mention ; https://github.com/sorry-cypress/sorry-cypress/issues/362#issuecomment-851695996
However, it seems the new side nav could be in-line with the desired improvements required for the above. 

Just an FYI ; mocks look good tho.

**Comment by ImanMahmoudinasab** [comment]
> re: pick color, I will try helping with that after I finished with v2 rollout

I'm working on it and almost done.

**Comment by agoldis** [comment]
@ImanMahmoudinasab did you join our slack? https://join.slack.com/t/sorry-cypress/shared_invite/zt-eis1h6jl-tJELaD7q9UGEhMP8WHJOaw

**Comment by ImanMahmoudinasab** [comment]
> * [ ] Runs Feed Screen (sm)
> * [ ]  Run Summary Component (md)
> * [ ]  Run Details Screen (lg)

I started working on these items in the task list. 🎯

**Comment by karimould** [comment]
I opend a PR for the status badges

https://github.com/sorry-cypress/sorry-cypress/pull/461

**Comment by ImanMahmoudinasab** [comment]
> I opend a PR for the status badges
> 
> #461


Hey @karimould, thank you for your time and effort. As you can see on the list of tasks, I'm working on the Run Summary Component and unfortunately, I already implemented the chips.

> 
> * [ ]  Runs Feed Screen (sm) (@ImanMahmoudinasab)
> * [ ]  Run Summary Component (md) (@ImanMahmoudinasab)
> * [ ]  Run Details Screen (lg) (@ImanMahmoudinasab)

You can join the slack channel for cypress 2 and there we talk about the latest state of implementation of each feature.
