### ISSUE TITLE
After 1.0.3 -> 1.1.0 upgrade, director service gets MongoError

### ISSUE THREAD

**Issue by KyleThenTR** [sorry-cypress/sorry-cypress#407]
## Summary
I'm upgrading from 1.0.3 to 1.1.0 and when I try to run tests, it gets a 504 gateway timeout to the director when running tests. Looking at the AWS Cloudwatch logs, it looks like there is an authentication error on startup of the director.

Director logs:
![image](https://user-images.githubusercontent.com/52414395/127393480-0adaadb6-3ba7-4539-becf-13b6e4be5379.png)

My director image has several of the mongo env vars defined
```
            - Name: EXECUTION_DRIVER
              Value: ../execution/mongo/driver
            - Name: SCREENSHOTS_DRIVER
              Value: ../screenshots/s3.driver
            - Name: MONGODB_DATABASE
              Value: sorry-cypress
            - Name: MONGODB_URI
              Value: mongodb://sorry-cypress:sorry-cypress@127.0.0.1:27017
```

- sorry-cypress version: `1.1.0`
- cypress version: `7.3.0`
- platform: `aws`
- service: `director`

**Comment by agoldis** [comment]
@KyleThenTR that's weird, lets try to debug your setup. I checked it on https://sorry-cypress-demo.herokuapp.com/ and it works for heroku setup. 


- Are you using AWS ECS? Is task definition defined properly?
- Are you able to log `MONGODB_URI` at runtime?

**Comment by KyleThenTR** [comment]
@agoldis yep using AWS ECS. I haven't changed the task definition in a while so unless anything changed that the director needed in the release, it should be fine. Don't know how to log the variable at runtime since I'm just using the docker image you create, but on the ECS page those env variables show up 
![image](https://user-images.githubusercontent.com/52414395/127492103-a36a3070-8923-4529-8ba2-3ab929e9cb09.png)

**Comment by KyleThenTR** [comment]
Looking at the logs, it looks like the director may be trying to sign in to Mongo before the Mongo container creates the sorry cypress user

Here is from the director, timestamp: 2021-07-29T08:07:49.081-05:00
![image](https://user-images.githubusercontent.com/52414395/127522243-9b3ab1ae-1b3a-4661-af05-ee68f80856f6.png)

Here is from the mongo container, timestamp: 2021-07-29T08:07:49.297-05:00
![image](https://user-images.githubusercontent.com/52414395/127522297-16bcc7a2-e1b8-4e0b-8bdf-857ae3ee876a.png)

**Comment by KyleThenTR** [comment]
Downgrading to 1.0.3 works but still get this error in the director service logs
![image](https://user-images.githubusercontent.com/52414395/127528665-2d513fd3-3d7b-4803-a7f1-d68a601b2ba6.png)

**Comment by KyleThenTR** [comment]
@agoldis any ideas on what I could try?

**Comment by agoldis** [comment]
@KyleThenTR I am afraid I run out of ideas :(

**Comment by KyleThenTR** [comment]
@agoldis interestingly enough, it works on 1.1.1 so I'm going to close this.
