### ISSUE TITLE
1.1.0 is partially portuguese?

### ISSUE THREAD

**Issue by tico24** [sorry-cypress/sorry-cypress#408]
## Summary

View a completed run (all passed) and hide successful steps. You see the message `Nenhum registro encontrado` instead of `No records found`

## How to reproduce
Start a run. View the run in the dashboard.

## Environment
- sorry-cypress version: `1.1.0`
- platform: `docker`

**Comment by agoldis** [comment]
That's a big in bold-ui implementation :( should replace this library with a mature UI framework, but it would require rewriting the whole UI

**Comment by ImanMahmoudinasab** [comment]
This issue will be fixed by replacing the Bold-UI data table with MUI data grid.
I'm working on this and will address this issue.

**Comment by ImanMahmoudinasab** [comment]
@agoldis This issue can be closed.

**Comment by agoldis** [comment]
Resolved in v2
