### ISSUE TITLE
Link run to CI build

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#414]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Expose link to CI build for a run

## Why is it needed? What is the value? For whom do we build it?

Be able to access the build on CI from the run

## High-level feature overview

Add a link that points to CI build. The data is in `run.meta.ci`.

**Comment by aneeshrelan** [comment]
Is this still open? If you can add some more details on the work required here, I can try implementing this

**Comment by agoldis** [comment]
@aneeshrelan  

New runs have CI information in request body, but we simple don't save it. It quite straightforward:
- Keep CI information in run entity when a run is created
- Updated schemas ang GQL queries to include CI data for `runsFeed` and `runSummary`
- Update the UI to show CI data 

Here's an example of CI data:
```
"ci": {
            "params": {
                "ciPipelineId": "383385038",
                "ciPipelineUrl": "https://gitlab.com/agoldis/sorry-cypress-demo/-/pipelines/383385038",
                "ciBuildId": "1653817792",
                "ciJobId": "1653817792",
                "ciJobUrl": "https://gitlab.com/agoldis/sorry-cypress-demo/-/jobs/1653817792",
                "ciJobName": "test 43/50",
                "ciProjectId": "25729682",
                "ciProjectUrl": "https://gitlab.com/agoldis/sorry-cypress-demo",
                "ciRepositoryUrl": "https://gitlab-ci-token:NNwUpSNyPo-4NNP8AcFz@gitlab.com/agoldis/sorry-cypress-demo.git",
                "ciDefaultBranch": "main"
            },
            "provider": "gitlab"
        },
```
