### ISSUE TITLE
Dashboard doesn't show projects on version 1.1.1

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [sorry-cypress/sorry-cypress#416]
## Summary

![image](https://user-images.githubusercontent.com/5295554/128548556-057e573e-76c2-44e7-862d-257f5e9c254c.png)
I have this issue on my local as well.

## Environment

- sorry-cypress version: `1.1.1`
- platform: `docker`
- service: `dashboard`

**Comment by ImanMahmoudinasab** [comment]
Looks like something was wrong with Mongodb after restarting it everything works like a charm.

**Comment by tvamev** [comment]
I am also facing this issue when running docker-compose.

**Comment by kimtiago** [comment]
same problem here...

**Comment by jovanz-getbgd** [comment]
Getting the same error when using docker-compose.
Restarting the stack helps, but the problem disappears on its own at random.
I'm not finding anything in the logs which could indicate what the issue is.

**Comment by nicolasprnt** [comment]
> Hello, I have the same issue, how did you resolve please
> 
> ![image](https://github.com/sorry-cypress/sorry-cypress/assets/23661657/be3620c3-fe30-4565-bb3f-24e9c43a9a97)

I've got the exact same issue ...
