### ISSUE TITLE
Webhooks to Github (maybe other hooks) stops reporting back at around 2600 tests

### ISSUE THREAD

**Issue by KyleThenTR** [sorry-cypress/sorry-cypress#417]
## Summary
When using the webhook to github, it seems to stop around ~2600 some tests. We have ~3700 tests that run so the webhook never reports that the run is complete. 

On github:
![image](https://user-images.githubusercontent.com/52414395/128550886-a53ff608-e864-4701-a409-200041ca3d23.png)
![image](https://user-images.githubusercontent.com/52414395/128550992-ed79aafc-bb06-449c-9dec-be189053e0d3.png)

On the dashboard:
![image](https://user-images.githubusercontent.com/52414395/128550954-c0ce9585-ca40-4550-a986-acf6883551f9.png)

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `8.2.0`
- platform: `aws`
- service: `api | director | dashboard | all`

**Comment by ImanMahmoudinasab** [comment]
@KyleThenTR It may be because of timeout setting. check the timeout setting of the project.
![2021-08-06 at 10 53 AM](https://user-images.githubusercontent.com/5295554/128552274-c7cfc595-d3df-4d9e-8579-d4194bc90068.png)

![image](https://user-images.githubusercontent.com/5295554/128552341-a8d47987-61ab-4c80-b058-8a58b2064f34.png)

**Comment by KyleThenTR** [comment]
> @KyleThenTR It may be because of timeout setting. check the timeout setting of the project.
> ![2021-08-06 at 10 53 AM](https://user-images.githubusercontent.com/5295554/128552274-c7cfc595-d3df-4d9e-8579-d4194bc90068.png)
> 
> ![image](https://user-images.githubusercontent.com/5295554/128552341-a8d47987-61ab-4c80-b058-8a58b2064f34.png)

I thought that was the case, initially it was only at 5 minutes but I changed it to 20 minutes and it still didn't finish.

**Comment by agoldis** [comment]
@KyleThenTR probably a rate limit issue from GH. It's quite tricky to troubleshot without any access to the data / logs. If you can share / provide either I'd be happy to help! 
,

**Comment by KyleThenTR** [comment]
@agoldis here is the error that starts popping up in the director logs when the webhooks start to not report for a run.

![image](https://user-images.githubusercontent.com/52414395/128710800-c4198139-3f31-400a-9af9-8f3eee094e63.png)

**Comment by agoldis** [comment]
oh that's a nasty error! 

We're storing too much information in the DB and the document exceeds 16MB size. Will issue a fix ASAP!

**Comment by KyleThenTR** [comment]
@agoldis appears to be working on v2, thanks!
