### ISSUE TITLE
Have separate URLs for the director to access storage and for cypress to access storage

### ISSUE THREAD

**Issue by mastacheata** [sorry-cypress/sorry-cypress#423]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
I'd like to have the director node access the storage at a differet URL than the cypress runner, because both are on separate networks.

## Why is it needed? What is the value? For whom do we build it?
If you have a web application that has separate nodes for frontend and backend and communication between the two happens through the browser (i.e. the public facing side), you usually want to run cypress in host networking mode.
Now if we add sorry-cypress into the picture, the director node is not running on host networking mode and must access minio using the internal docker hostname (i.e. storage) for the node. Cypress however has no access to the internal docker network and thus can't use that hostname to talk with minio and must use the public-facing URL instead.
One can access the docker network from host network, but the DNS names aren't automatically published to these.

## High-level feature overview
Add two separate environment variables for internal and external communication to storage
Use the internal one for director to communicate with minio
Use the external one to manipulate the upload and read URLs provided by minio

**Comment by mastacheata** [comment]
After playing around with minio for half an hour, I'm wondering: Is this possible at all? The signature for the upload URL takes into account the hostname as it seems and thus it might be impossible to rewrite the URL.

**Comment by agoldis** [comment]
Please tell me if that piece of configuration explains the issue:

https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration#caveats-of-using-minio

**Comment by mastacheata** [comment]
It explains the issue, but doesn't provide a solution. 😟
After reeading up on the signature thing in minio, I don't think there is a solution, though. At least none that you or the code in this project could provide.

Either I add a reverse proxy/nameserver into the mix or minio would need an option to use different addresses for the connection and for the signature / link generation part.

**Comment by namnhcntt** [comment]
I faced the same issue. I have a traefik proxy and minio service is behind this. My public domain is https://cypress-storage.xxx.com (access from internet), but when run cypress agent, the director service return address is http://storage:9000, and the uploading failed. 

Can we have any solution for public and access minio storage behind proxy?
Thanks

**Comment by agoldis** [comment]
@namnhcntt Please refer to https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration#caveats-of-using-minio

Specifically, 

> The  implications of this flow (and where most people are getting confused) are:
Director and cypress agents have to use the same hostname to access minio
Director and cypress should be able to access minio service using the hostname and port you've defined

**Comment by namnhcntt** [comment]
Thanks, After some hours for trying, I configured success.
