### ISSUE TITLE
Jenkins agent is assigned all tests when joining the run later than others 

### ISSUE THREAD

**Issue by binhpv** [sorry-cypress/sorry-cypress#435]
## Summary

I have my tests running on 4 Jenkins agent. If all agents has available executor, then no problem. However if one agent is busy and can only execute the tests after finishing some of its current build job, then it get assigned all the tests and has to run them all. This happen even though the other agents haven't finish running tests yet (not even half the number of tests). 
This make the test time as slow as before since the busy agent has to run everything again.

In the dashboard screenshot you can see that spec are claimed again, and the same build-id appear 3 times.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/1096734/132845535-80d549a1-75a5-4833-ae18-9030afb0b2a4.png">

## How to reproduce
Sadly my code and environment is not public to share a reproducible environment. I guess you can reproduce by making one of the agents unavailable, and then start it again when other agents has claimed some specs

## Environment

- sorry-cypress version: 1.0.3
- cypress version: 7.0.1 (cannot upgrade to 8 due to performance issue which double our test time)
- platform: docker
- service: I'm not sure, probably all?

**Comment by agoldis** [comment]
Please make sure that when Jenkins start running cypress tests all the follow values are similar across the Jenkins machines:

- `ciBuildId` 
- git commit `sha` value
- `projectId`

**Comment by agoldis** [comment]
Another option - please make sure that MongoDB indexes for `runs` collection are present:

`{ runId: 1 }, { unique: true }`

**Comment by agoldis** [comment]
Closing due to lack of interest

**Comment by binhpv** [comment]
Hi @agoldis , sorry I was too busy to follow up with your suggestion. I found out why it is happening: different git sha.
The problem is I don't know how to make it consistent, because when building the Pull request, Jenkins is merging the source to the target branch before building. This create a different SHA value everytime.
If I change Jenkins to build the source revision then it's fine. But then I cannot know if the PR after merge will work correctly or not, since it's only building the source branch and not merging.

Another way is to always keep the source up to date with the target, but this is not always possible :(
