### ISSUE TITLE
Support instance filter in Slack hook

### ISSUE THREAD

**Issue by fsmaia** [sorry-cypress/sorry-cypress#437]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

The slack hook could have an instance filter field, so different suites could be notified to different channels.

## Why is it needed? What is the value? For whom do we build it?

Some large applications are maintained by multiple teams, and eventually, they may share the same Cypress execution.

## High-level feature overview

When the instance filter is filled, then the `instance_finished` event will be triggered only when the filename matches the given field. It could be a regex or even a simple string match (`indexOf`/`includes`).

**Comment by itsthefrits** [comment]
+1 on this. It would be great to send to different channels. Alternatively, it would be very nice to be able to add in the project title as specified in the dashboard to the message posted.

**Comment by ArturMiszkowicz** [comment]
Will this be reopened?

**Comment by fsmaia** [comment]
@agoldis, could this issue be reopened?
