### ISSUE TITLE
Getting => We encountered an unexpected error talking to our servers.

### ISSUE THREAD

**Issue by obula** [sorry-cypress/sorry-cypress#439]
## How to reproduce
STEP 1: 
C:\CypressDashboard\sorry-cypress-master>docker-compose -f docker-compose.minio.yml up
Output=> Success. Able to see dashboard and created projects in localhost:8080.

STEP 2: Unable to run the tests with the below command
C:\CypressDashboard\sorry-cypress-demo-main (1)\sorry-cypress-demo-main>npx cy2 run --record --key XXX --parallel --ci-build-id buildrun-01
[cy2] Running cypress with API URL: "http://localhost:1234/"

We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

RequestError: Error: Invalid URI "/runs"
We encountered an unexpected error talking to our servers.

We will retry 2 more times in 1 minute...

The server's response was:

RequestError: Error: Invalid URI "/runs"
We encountered an unexpected error talking to our servers.

We will retry 1 more time in 2 minutes...

The server's response was:

RequestError: Error: Invalid URI "/runs"
We encountered an unexpected error talking to our servers.

We will retry 0 more times in ...

The server's response was:

RequestError: Error: Invalid URI "/runs"
We encountered an unexpected error talking to our servers.

Because you passed the --parallel flag, this run cannot proceed because it requires a valid response from our servers.

The --ciBuildId flag you passed was: buildrun-01

The server's response was:

RequestError: Error: Invalid URI "/runs"

**Comment by agoldis** [comment]
I was able to run tests from master with unaltered `docker-compose.minio.yml`. Please make sure you're pointing to director service and it is available on `http://localhost:1234`

```sh
docker-compose -f docker-compose.minio.yml up
CYPRESS_API_URL=http://localhost:1234/ npx cy2 run --record --key XXX --parallel --ci-build-id buildrun-01
```

**Comment by manojmohangit** [comment]
I was also facing same issue. The main issue is with the command where CYPRESS_API_URL are modified. There should not be any quotes around http://localhost:1234/ as mentioned in docs.
