### ISSUE TITLE
 MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo

### ISSUE THREAD

**Issue by obula01** [sorry-cypress/sorry-cypress#440]
## Summary
Unable to create projects in localhost:8080 server

## How to reproduce
STEP1: C:\CypressDashboardRD\sorry-cypress-master\sorry-cypress-master>docker-compose -f docker-compose.full.yml up

** Error Log**
director_1   | (node:1) UnhandledPromiseRejectionWarning: MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo
director_1   |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
director_1   |     at listOnTimeout (internal/timers.js:557:17)
director_1   |     at processTimers (internal/timers.js:500:7)
director_1   | (Use `node --trace-warnings ...` to show where the warning was created)
director_1   | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
director_1   | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
api_1        | MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo
api_1        |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
api_1        |     at listOnTimeout (internal/timers.js:557:17)
api_1        |     at processTimers (internal/timers.js:500:7) {
api_1        |   reason: TopologyDescription {
api_1        |     type: 'Single',
api_1        |     setName: null,
api_1        |     maxSetVersion: null,
api_1        |     maxElectionId: null,
api_1        |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
api_1        |     stale: false,
api_1        |     compatible: true,
api_1        |     compatibilityError: null,
api_1        |     logicalSessionTimeoutMinutes: null,
api_1        |     heartbeatFrequencyMS: 10000,
api_1        |     localThresholdMS: 15,
api_1        |     commonWireVersion: null
api_1        |   }
api_1        | }
api_1 exited with code 1

**Comment by agoldis** [comment]
Please reopen with all the details provided as appears in template
