### ISSUE TITLE
Dashboard gives this error : Error: BSONObj size: 20771140 (0x13CF144) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('6131d5e21d8a590019f66947')

### ISSUE THREAD

**Issue by vaibhavi789** [sorry-cypress/sorry-cypress#441]
## Summary

Sorry cypress does X, but should do Y

## Environment

- sorry-cypress version: `<here>`
- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by agoldis** [comment]
Please reopen with all the details provided as mentioned in the template
