### ISSUE TITLE
Screenshots and videos files uploading failed and not showing in dashboard

### ISSUE THREAD

**Issue by obula** [sorry-cypress/sorry-cypress#443]
Screenshots and videos are not showing in dashboard
## How to reproduce
Step 1: Run docker compose - mono.yml
docker-compose -f docker-compose.minio.yml up
Step 2: Run tests
C:\CypressDashboard\sorry-cypress-demo-main (1)\sorry-cypress-demo-main>npx cy2 run --record --key XXX --parallel --ci-build-id buildrun-03
Step 3: Check running logs => Here files are not uploading to server.
Step 4: Check dashboard project test results => here files are not showing

![image](https://user-images.githubusercontent.com/4481519/133139385-f529d060-914a-4c50-b59e-bed27abfa7cd.png)

## Environment
Windows Machine

**Comment by agoldis** [comment]
@obula please stop opening those issues. 
- You're not following the template
- Your setup is wrong, you'd better follow the documentation and make sure it's all set up as described
