### ISSUE TITLE
Dashboard gives this error : Error: BSONObj size: 20771140 (0x13CF144) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('6131d5e21d8a590019f66947')

### ISSUE THREAD

**Issue by vaibhavi789** [sorry-cypress/sorry-cypress#445]
Please note - issues that are not following the template will be closes automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
It was working fine for 8 month but now suddenly we are not able run test to dashboard.
Dashboard gives error  : Error: BSONObj size: 20771140 (0x13CF144) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('6131d5e21d8a590019f66947')

## How to reproduce

1. I have try to run with single cypress test..still nothing I can see on dashboard
2. 

## Relevant logs / screenshots

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`
- Please submit relevant logs from director / api / dahsboard service
- Please submit screenshots if relevant

## Environment

- sorry-cypress version: `<here>`
- cypress version: `
<img width="1166" alt="Screenshot 2021-09-14 at 09 38 20" src="https://user-images.githubusercontent.com/58173901/133224919-b589dedf-22cd-4ceb-898c-c77f7937a87f.png">
`
- platform: `AWS
<img width="126" alt="Screenshot 2021-09-14 at 09 27 22" src="https://user-images.githubusercontent.com/58173901/133223539-5d55be1e-b402-4b13-b50a-c0bf9fbd674b.png">
<img width="1788" alt="Screenshot 2021-09-14 at 09 27 37" src="https://user-images.githubusercontent.com/58173901/133223555-9ecf1627-125f-4d65-ad70-654ac6d91763.png">

**Comment by agoldis** [comment]
Please tell me if v2.0.0-beta.12 solves this issue
