### ISSUE TITLE
API queries regarding run crash with: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Roemer** [sorry-cypress/sorry-cypress#446]
Please note - issues that are not following the template will be closes automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

All queries regarding `runs` from the api seem to crash with the error:
```
{
  "errors": [
    {
      "message": "Cannot read property 'find' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "runs"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'find' of undefined",
            "    at /app/packages/api/dist/datasources/runs.js:21:23",
            "    at Array.map (<anonymous>)",
            "    at mergeRunSpecs (/app/packages/api/dist/datasources/runs.js:20:25)",
            "    at Array.map (<anonymous>)",
            "    at RunsAPI.getAllRuns (/app/packages/api/dist/datasources/runs.js:85:20)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

## How to reproduce

1. Open the API website
2. Run the following query:
```
query runs {
  runs{
    runId
  }
}
```

## Relevant logs / screenshots

See summary.

## Environment

- sorry-cypress version: `v2.0.0-beta.10`
- cypress version: `8.0`
- platform: `docker, kubernetes`
- service: `api`

**Comment by agoldis** [comment]
Fixed in v2.0.0-beta.11 and up

**Comment by Roemer** [comment]
Sorry, will test it asap. I checked the commits but somehow cannot find where or how this is fixed.

**Comment by Roemer** [comment]
I updated to beta.12 and still got the same issue. In addition, when connecting to the API-Website, I cannot get the API-UI anymore and only get `GET query missing.`.

**Comment by agoldis** [comment]
@Roemer sorry, my bad - i think i actually fixed it in beta.13

https://sorry-cypress-demo-api.herokuapp.com/
