### ISSUE TITLE
Hide successful specs hides pending tests

### ISSUE THREAD

**Issue by AsimAM** [sorry-cypress/sorry-cypress#447]
Running sorry cypress `v2.0.0 beta 12` and the hide sucessful spec button is broken.

When pressing the button it also hides pending tests when it should only be hiding completed successful tests.

**Comment by ImanMahmoudinasab** [comment]
more details on #468

**Comment by ImanMahmoudinasab** [comment]
@agoldis oh you are right. I already fixed it to show pending, and in the new pr I'm showing running specs as well.
