### ISSUE TITLE
Failing tests number doesn't match in slack notifications

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [sorry-cypress/sorry-cypress#448]
- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Failing tests number doesn't match in slack notifications

## How to reproduce

I'm not sure, but I think this happens when some tests fail multiple times a then pass on the retry.

## Relevant logs / screenshots

Dashboard:
![2021-09-14 at 4 35 PM](https://user-images.githubusercontent.com/5295554/133347537-bae46ad2-bede-4d25-8c7c-57ff379c44f1.png)
Slack:
![2021-09-14 at 4 37 PM](https://user-images.githubusercontent.com/5295554/133347684-324d37e9-747d-4793-bf79-9b9f90ec15ad.png)

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `8.3.0`
- platform: `docker`
- service: `dashboard`

**Comment by agoldis** [comment]
Fixed in v2 :)
