### ISSUE TITLE
Ability to create projects via REST API calls

### ISSUE THREAD

**Issue by aGRRRo** [sorry-cypress/sorry-cypress#449]
Greetings!
I didn't find any docs regarding if it is implemented or not.
This might be a useful feature for teams with IAC implementation, in case of automatic redeployments.
Thanks.

**Comment by testingJava2** [comment]
@aGRRRo,

Possible workaround(?) might be to directly send results to a project that does not exist, if that would get you covered in your use case.

This will simply create a new project with that name in your dashboard (NB - I did not try this on v2).

Alex

**Comment by aGRRRo** [comment]
@testingJava2 Wow, it worked! Not sure when(or from which version) it started to work. However, this approach will create a project with default parameters so it will be great to get REST API functionality for this.

**Comment by agoldis** [comment]
BTW, you can set `INACTIVITY_TIMEOUT_SECONDS` in director for overriding the default timeout
