### ISSUE TITLE
Sidebar projects overflow breaks the layout

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#453]
Please note - issues that are not following the template will be closes automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sidebar overflow breaks the layout. See https://sorry-cypress-demo.herokuapp.com/

## How to reproduce

Visible on https://sorry-cypress-demo.herokuapp.com/

## Relevant logs / screenshots

n/a

## Environment

- sorry-cypress version: `2.0.0-beta.12`

**Comment by agoldis** [comment]
@ImanMahmoudinasab Any chance you can take a look?

**Comment by agoldis** [comment]
@ImanMahmoudinasab  nvm, fixed in #454

I've had a chance to work with the code you've recently contributed

- thanks a lot for investing your time - very nice effort with a lot of attention to details! 🎉👍🏻
- I would suggest to focus on letting other to contribute easily - e.g. custom margins and padding are quite hard to match for future contributors, whenever we can use default styling without overrides - let's do that!

**Comment by ImanMahmoudinasab** [comment]
> Sidebar overflow breaks the layout.

Oops! I missed it.



> * thanks a lot for investing your time - very nice effort with a lot of attention to details! 🎉👍🏻

Thank you @agoldis . It was my pleasure! 🙏🏻



> * I would suggest to focus on letting other to contribute easily - e.g. custom margins and padding are quite hard to match for future contributors, whenever we can use default styling without overrides - let's do that!

Sure! That was my first round with focus on functionality and not the structure and maintainablity. I would refactor them but first we should talk about the structure that I have in my mind and then apply it to the project.
