### ISSUE TITLE
Doesn't show media when tests pass

### ISSUE THREAD

**Issue by vladkarasyov** [sorry-cypress/sorry-cypress#456]
I ran the docker-compose -f docker-compose.minio.yaml file on my host (Ubuntu18.04)
All containers ran. And I can even go to the UI. I run the tests with cy2 run --record --key Test --parallel --ci-build-id date +% s --browser = chrome.
Everything comes to the UI and everything is fine, but there is a window with media nearby and it does not load. If you look at f12 you can see it. that no request is given from port 9000. if you look at the log, we will see

![image](https://user-images.githubusercontent.com/43986003/134514306-89621a25-06f7-44cf-afe4-098ec7300549.png)

Can you help? What is wrong?

**Comment by agoldis** [comment]
@vladkarasyov 
1. Please use the template when opening an issue
2. By default cypress isn't recording videos for passed tests and from your description it isn't clear why you're expecting to see videos for passed tests
