### ISSUE TITLE
Test run on dashboard for hours

### ISSUE THREAD

**Issue by vaibhavi789** [sorry-cypress/sorry-cypress#458]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
As soon as I run test to dashboard there is no timeout .. Dashboard says its running for 3 to 4 hrs.
There should be time out. After that time test will not run

## How to reproduce

1. Step A
2. Step B

## Relevant logs / screenshots

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`
- Please submit relevant logs from director / api / dahsboard service
- Please submit screenshots i
<img width="96" alt="Screenshot 2021-09-24 at 15 07 53" src="https://user-images.githubusercontent.com/58173901/134688390-9546189b-35ba-41c4-94c6-5716da158d99.png">
f relevant

## Environment

- sorry-cypress version: `<here>`
<img width="146" alt="Screenshot 2021-09-24 at 15 09 30" src="https://user-images.githubusercontent.com/58173901/134688520-bb4bf8a4-b9d2-489e-82cf-7b0c19a1e032.png">
<img width="715" alt="Screenshot 2021-09-24 at 15 07 45" src="https://user-images.githubusercontent.com/58173901/134688387-07cdc4a8-ab1d-45c4-b800-29539ce954ab.png">

- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by vaibhavi789** [comment]
platform: AWS

**Comment by vaibhavi789** [comment]
On the UI delete and reset is there. How I can remove the reset
<img width="222" alt="Screenshot 2021-09-28 at 12 21 32" src="https://user-images.githubusercontent.com/58173901/135077987-123fc35a-8725-443f-95ca-894bf17c58b9.png">
t.

**Comment by agoldis** [comment]
We mark the whole run as timed out, please disregard test duration for timed out run.

**Comment by vaibhavi789** [comment]
Means, I didn't get.
What I have to do? To stop the run on dashboard
