### ISSUE TITLE
Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by guyguy333** [sorry-cypress/sorry-cypress#477]
- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress does X, but should do Y

## How to reproduce

No idea, it's happening randomly.

## Relevant logs / screenshots

Director:

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
    at Object.project (/app/packages/mongo/dist/index.js:2:2204)
    at getProjectById (/app/packages/director/dist/execution/mongo/projects/project.model.js:12:47)
    at Object.createRun (/app/packages/director/dist/execution/mongo/runs/run.controller.js:53:53)
    at handleCreateRun (/app/packages/director/dist/api/runs.js:42:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 65)
>> Machine is joining / creating a run {
  ciBuildId: '45109',
  group: null,
  ci: {
    params: {
      ciPipelineId: '45109',
      ciPipelineUrl: 'https://git.example.com/-/pipelines/45109',
      ciBuildId: '1120752',
      ciJobId: '1120752',
      ciJobUrl: 'https://git.example.com/-/jobs/1120752',
      ciJobName: 'test:app 4/6',
      ciProjectId: '446',
      ciProjectUrl: 'https://git.example.com',
      ciRepositoryUrl: 'https://gitlab-ci-token:aaaaa@git.example.com/project.git',
      ciDefaultBranch: 'master'
    },
    provider: 'gitlab'
  }
}
```

Nothing relevant in API and dashboard

## Environment

- sorry-cypress version: `1.1.1`
- cypress version: `8.6.0`
- platform: `docker`
- service: `all`

**Comment by agoldis** [comment]
Resolved in v2+ would you mind please upgrading to the latest?

**Comment by guyguy333** [comment]
Thanks @agoldis. We're currently using sorry-cypress (and it works very well, thanks !) in production. Is 2.0 beta stable enough ?

**Comment by agoldis** [comment]
It is stable, even though there are some changes that can affect browsing runs created from older versions. It is beta because the UI wasn't fully migrated to new framework.

https://github.com/sorry-cypress/sorry-cypress/pull/427

**Comment by guyguy333** [comment]
Indeed, update was smooth. I will close the issue and reopen if the issue remains. Thanks
