### ISSUE TITLE
Support custom S3 endpoint for services that are fully compatible with aws-sdk S3

### ISSUE THREAD

**Issue by andytson-inviqa** [sorry-cypress/sorry-cypress#482]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Supporting custom S3 endpoint for services that are fully compatible with aws-sdk S3, such as Digital Ocean

## Why is it needed? What is the value? For whom do we build it?

So that it's possible to only use the aws-sdk to use these services

## High-level feature overview

Expose the aws-sdk S3 endpoint setting as an optional setting. 
https://docs.digitalocean.com/products/spaces/resources/s3-sdk-examples/

**Comment by agoldis** [comment]
@andytson-inviqa  Did you consider using minio?

**Comment by andytson** [comment]
aws-sdk s3 endpoint is going to be much better to do it than run an additional service that consumes additional resources @agoldis

**Comment by andytson** [comment]
I've had a look through the code though since I wrote this ticket. It seems sorry-cypress uses signed url to post the uploads, rather than using the sdk to upload. Without the latter, this wont work as signed urls aren't part of Digital Ocean's api

**Comment by andytson** [comment]
that's unless that's what aws-sdk does internally for the upload

**Comment by agoldis** [comment]
I imagine it isn't an just SDK internal thing, the upload request goes
directly to S3, it needs to verify the signatures somehow.

**Comment by andytson** [comment]
I've tested the s3.getSignedUrl() against Digital Ocean Spaces, and curl posted a file to it, and it works correctly so ignore my last two comments.

Just supporting a custom endpoint is enough for this to work.

**Comment by agoldis** [comment]
What variables would you need to have to override the URLs? https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/screenshots/s3/s3.ts
May be you can provide a short snippet of your test - that can help me.

**Comment by andytson** [comment]
```javascript
const AWS = require('aws-sdk');

const spacesEndpoint = new AWS.Endpoint('fra1.digitaloceanspaces.com');
const s3 = new AWS.S3({
    endpoint: spacesEndpoint,
    region: 'fra1', // unnecessary here but it's not optional in sorry-cypress
    signatureVersion: 'v4'
});

s3Params = {
  Bucket: 'example-bucket',
  Key: 'test',
  Expires: 60
};

s3.getSignedUrl(
      'putObject',
      s3Params,
      (error, uploadUrl) => {
        console.log(uploadUrl);
      }
);
```

**Comment by rohit-gohri** [comment]
I tested my PR #546 with GCS and it doesn't work due to this error:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>MalformedSecurityHeader</Code><Message>Your request has a malformed header.</Message><ParameterName>x-amz-content-sha256</ParameterName><Details>Header was included in signedheaders, but not in the request.</Details></Error>
```
Would you be open to adding GCS specific code to support a cloud storage bucket? (related to #46)

**Comment by andytson** [comment]
bump, not stale

**Comment by andytson** [comment]
I tested the linked PR, but it appears DigitalOcean doesn't support the ACL being provided in the presigned upload url, so would require them to update their server to support it (as it does also support 'private' and 'public-read' ACL for `aws s3 cp --endpoint=...`)

**Comment by agoldis** [comment]
Linked PR?

**Comment by andytson** [comment]
https://github.com/sorry-cypress/sorry-cypress/pull/546

**Comment by agoldis** [comment]
Sorry I don't know what to do now - the PR is closed, and you've mentioned the PR it doesn't work with Digital Ocean. Please guide me

**Comment by andytson** [comment]
I've just tried aws-sdk v3 to see if it was any different with it's pre-signed code, but it also doesn't work correctly (seems to upload but ignores the ACL).

So, I don't think we can progress this issue unless for another provider than DigitalOcean which would need endpoint configuration that works.

I'll submit an "idea" to DigitalOcean, but I don't expect it'll be a high priority for them.
