### ISSUE TITLE
Nx Executor

### ISSUE THREAD

**Issue by maxfriedmann** [sorry-cypress/sorry-cypress#484]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
A cypress test executor for Nx (nx.dev, awesome workspace tool) which replaces the default cypress runner.

## Why is it needed? What is the value? For whom do we build it?
Nx adds various features to cypress testing such as "only test projects that were affected by your code changes", "build/test/lint caching" and "nx workspace dev server bootup" etc.pp. While I can use a custom nx executor to integrate well with sorry-cypress, we cannot use those fancy features anymore.

## High-level feature overview
We would need a Custom Executor (https://nx.dev/l/n/executors/creating-custom-builders) that uses the executor from @nrwl/cypress under the hood but starts `cy2` instead of `cypress`.

or

A script that patches the installed cypress dependency to use a different api url, like cy2 does.

## Other
- Our current workaround is to use the custom run commands (https://nx.dev/l/n/executors/run-commands-builder). 
- I guess folks from https://github.com/sorry-cypress/sorry-cypress/issues/362 must have had some success in this direction already.

**Comment by maxfriedmann** [comment]
My current workaround is to manipulate the CYPRESS_API_URL as described here: https://docs.sorry-cypress.dev/cypress-agent/cli-one-liners

**Comment by agoldis** [comment]
Please use https://github.com/currents-dev/currents-nx, with `cypressApiUrl` option like this:
```js
{
// ...
"targets": {
  "currents": {
    "executor": "@currents/nx:currents",
    "options": {
      "cypressExecutor": "e2e" // target name that runs "@nrwl/cypress:cypress",
      "cypressApiUrl": "http://yourserver.com"
    }
  },
 "e2e": {
    "executor": "@nrwl/cypress:cypress",
    "options": {
      // ...
    },
    "configurations": {
      // ...
    }
  }
}
```

**Comment by maxfriedmann** [comment]
Works like a charme!!!
