### ISSUE TITLE
[Cucumber scenario failures] S3 bucket Videos are not displaying in dashboard 

### ISSUE THREAD

**Issue by vinod-demansol** [sorry-cypress/sorry-cypress#497]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [ ] I have searched issues / discussions and found to answer to my problem
- [ ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

S3 bucket Videos are not displaying in dashboard but I see S3 bucket's image in dashboard report

## How to reproduce

1. export CYPRESS_API_URL="http://localhost:1234/"
2. npx cy2 run --parallel --record --key somekey --ci-build-id "build02"

## Relevant logs / screenshots
![image](https://user-images.githubusercontent.com/85981671/143482908-31188974-7478-4b6c-8b1e-fcaaec94b576.png)

![image](https://user-images.githubusercontent.com/85981671/143482486-b5b52475-444e-4420-a162-60d2aa61d072.png)

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`
- Please submit relevant logs from director / api / dahsboard service
- Please submit screenshots if relevant

## Environment

    "browserstack-cypress-cli": "^1.10.1",
    "cucumber-html-reporter": "^5.5.0",
    "cy2": "^1.3.0",
    "cypress": "^8.4.1",
    "cypress-cucumber-attach-screenshots-to-failed-steps": "^1.0.0",
    "cypress-cucumber-preprocessor": "^4.3.0",
    "cypress-xpath": "^1.6.2",
    "multiple-cucumber-html-reporter": "^1.18.0",
    "typescript": "^4.4.3"

**Comment by agoldis** [comment]
@vinod-demansol 
- Are you seeing cypress agents uploading videos?
- Are you seeing errors in browser network tab?
- What's happening when you are trying to access the video file directly in a browser, not via dashboard?
