### ISSUE TITLE
Feature Request: Add a project level setting for how many jobs to maintain before deleting old ones.

### ISSUE THREAD

**Issue by mwamufiya** [sorry-cypress/sorry-cypress#498]
- [ X ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Adding a project settings to control how many jobs to keep before deleting old ones

## Why is it needed? What is the value? For whom do we build it?

- when used in a CI environment, where jobs run every 'x' minutes or hours, the number of jobs in the dashboard starts to pile up.
- currently the dashboard only offers the ability to delete one job at a time
- being able to set a setting that only keeps the last 'x' number of jobs would allow 
  - the list of jobs to be manageable
  - keep the amount of resources consumed to the absolute minimum without requiring manual intervention to periodically prune the list

## High-level feature overview

- Add a setting under Project Settings "Max # of Jobs to keep" 
- When a new new job starts for the current project, 
- **IF** the total number of jobs in the projects greater than or equal to this limit, **THEN** 
  - Delete the oldest job

**Comment by TomaszG** [comment]
That would be useful! As a low hanging fruit dashboard could offer an option to delete run older than X on demand. Currently I'm using the following script to delete everything older than week (I'm not really familiar with MongoDB so there's a chance that there's a better way to achieve the same):

```shell
use sorry-cypress;

print('runs before cleaning up: ' + db.runs.count());
db.runs.remove( { createdAt : { $lte : new Date(new Date().getTime()-7*24*60*60*1000).toISOString() } });
print('runs after cleaning up: ' + db.runs.count());

print('instances before cleaning up: ' + db.instances.count());
var pipeline = [{     "$lookup": {         "from": "runs",         "let": {             "runId": "$runId"         },         "pipeline": [{             "$match": {                 "$expr": {                     "$and": [                         { "$eq": [ "$runId", "$$runId" ] },                     ]                 }             }         }, {             "$limit": 1         }],         "as": "runs"     } }, {     "$match": {        "runs.runId": { "$exists": false }     } }, {     "$project": {         "runs": false     } }];
var instancesCursor = db.instances.aggregate(pipeline);
var instancesIds = instancesCursor.map(function (instance) { return instance._id; });
db.instances.remove({"_id": { "$in": instancesIds }});
print('instances after cleaning up: ' + db.instances.count());

print('runTimeouts before cleaning up: ' + db.runTimeouts.count());
var runTimeoutsCursor = db.runTimeouts.aggregate(pipeline);
var runTimeoutsIds = runTimeoutsCursor.map(function (runTimeout) { return runTimeout._id; });
db.runTimeouts.remove({"_id": { "$in": runTimeoutsIds }});
print('runTimeouts after cleaning up: ' + db.runTimeouts.count());

db.getCollectionNames().forEach(function (collectionName) {
    print('Compacting: ' + collectionName);
    db.runCommand({ compact: collectionName });
});

print('Done!');
```
