### ISSUE TITLE
cy2 runner in github actions, similar to existing cypress one

### ISSUE THREAD

**Issue by YossiSaadi** [sorry-cypress/sorry-cypress#499]
- [X] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Have the same api, and even more powerful, to the one that cypress supply in theirs cypress' github actions' hook

## Why is it needed? What is the value? For whom do we build it?
To be able to run more easily using github actions, maybe also to be able to run multiple instances on same GHA machine, instead of using instances strategy.

## High-level feature overview
Run cypress with sorry cypress more easily.

## Other
https://docs.cypress.io/guides/continuous-integration/github-actions#Basic-Setup

If using the original cypress action is possible I would love to know about it :)
P.S. AMAZING JOB! Loving Sorry-Cypress! ❤️

**Comment by tchiaspko** [comment]
👍

**Comment by agoldis** [comment]
check out https://github.com/currents-dev/gh-actions-example/blob/main/.github/workflows/currents.yml#L23
you can replace `currents` with `cy2`

**Comment by YossiSaadi** [comment]
> check out https://github.com/currents-dev/gh-actions-example/blob/main/.github/workflows/currents.yml#L23
> you can replace `currents` with `cy2`

Awesome! Thanks @agoldis !!
