### ISSUE TITLE
Restricted access 

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#5]
I imagine some users would like to restrict access to the dashboard components for foreigners.

**Comment by StefanS-O** [comment]
I want this too. I think the easiest solution would be using an nginx reverse proxy and basic auth.

**Comment by agoldis** [comment]
@StefanS-O  Yeah, it seems like a good approach!

There're currently other enhancements that have more upvotes, I hope it will be implemented eventually.

**Comment by ismail-codinglab** [comment]
Is there a place where we can see which feature has more upvotes or some sort of central place where we can see features vs number of votes?

**Comment by agoldis** [comment]
@ismail-codinglab no such place :) GitHub issues is the only one I've got

**Comment by AndrewPopenko** [comment]
@agoldis I think it's very important feature for many users... I hope you will be able to deliver this feature ASAP :)

**Comment by bgupta** [comment]
All the documented deployment methods, deploy a public-facing, non-authenticated service. I am a little confused about why this is ok for most users unless it's only being used by open-source projects? Any guidance here would be appreciated.

**Comment by agoldis** [comment]
It's not being used only by open-source project, that I can tell for sure.

Based on my observations:
- at the simplest level one can set up a list of [allowed keys](https://sorry-cypress.dev/director/configuration#configuration)
- people use all kind of a workarounds e.g. https://traefik.io/traefik (@Upgreydd ?)
- deploy on internal cloud so no access restrictions necessary

**Comment by iamkhalidbashir** [comment]
> All the documented deployment methods, deploy a public-facing, non-authenticated service. I am a little confused about why this is ok for most users unless it's only being used by open-source projects? Any guidance here would be appreciated.

I thought the same, why is it ok for everyone?

> It's not being used only by open-source projects, I can tell for sure.
> 
> Based on my observations:
> 
> * at the simplest level one can set up a list of [allowed keys](https://sorry-cypress.dev/director/configuration#configuration)
> * people use all kind of a workarounds e.g. https://traefik.io/traefik (@Upgreydd ?)
> * deploy on internal cloud so no access restrictions necessary

Doesn't matter if it is used for open-sourced project or not, a simple login-register based access is always better than [allowed keys](https://sorry-cypress.dev/director/configuration#configuration)

**Comment by boxofcrates** [comment]
Is there interest in an OIDC integration? Dashboard would do OIDC auth, and the API would require a signed token. Director would stay the same with the allowed keys whitelist. The use-case for this would be exposing the dashboard/API (+ Minio/S3) publicly, but keeping director/Mongo private.

I would be interested in working on this.

**Comment by boxofcrates** [comment]
Just an update here, I had some priority shifts at work and won't be able to take on such an OIDC integration anytime soon. However I did a little poking around, so writing up some thoughts here in case they prove useful to anyone else in the future.

--

I think you're absolutely right about a 'wapping' implementation.

One important consideration is whether the API with GraphQL client credentials is secure 'enough'. If so, this becomes a much simpler task.

**With API protected with GraphQL client credentials (current)**
This scenario can be set up already using a front-end auth proxy ('forward authentication service'): to sit in front of dashboard and provide an OIDC flow before letting the user access the dashboard.

This option secures the dashboard, leaves the API secured via graphql credentials, and leaves S3 assets unsecured.

Historically I've had good experiences with https://github.com/thomseddon/traefik-forward-auth for doing this on k8s clusters with a Traefik ingress controller, https://github.com/oauth2-proxy/oauth2-proxy for k8s clusters with a non-Traefik (nginx) ingress controller, and https://github.com/nokia/kong-oidc for doing this outside a k8s cluster behind a Kong gateway. AWS Cognito is a hosted option, and there are plenty tools out there to do this for any architecture.

**With API protected with JWTs**
This method offers better security for the API endpoint compared to GraphQL client credentials, but would require dashboard code change.

* Dashboard wrapped by forward auth service like before
* Dashboard updated to pass on an auth token to all API requests
* API wrapped by back-end auth proxy (any decent service mesh for k8s, any decent API Gateway, etc)

This can get complicated pretty quickly, depending on factors like e.g., how do we handle auto-refresh if the access token expired? Do we just cause a page refresh (front-end auth proxy will then refresh access token from refresh token and give dashboard the new access token)? What about the edge-case when the access token expires part-way through the page loading? Do we add oidc-specific logic to the dashboard to handle getting a new access token from a refresh token? etc etc

**Other Considerations**
Another consideration is S3 access. Right now, the only real option for restricting read access is an ACL policy on the S3 bucket to restrict to whitelisted IP blocks. However it would be possible to use pre-signed GET urls in the dashboard (similar to the pre-signed PUT urls that director generates) and disable public access to the bucket entirely.

I got this working locally, but it required quite a bit of refactoring to move storage drivers from _director_  to _common_ (so _api_ can access the storage drivers: the signed URLs expire after a few minutes so need to be generated by the API).

---

Anyway, just some thoughts, in case they prove helpful to anyone who does take this work on.

**Comment by StefanS-O** [comment]
I will deploy Sorry Cypress on Kubernetes this week and will look into it, since we need it password protected. I will post my findings here. Maybe it results in a merge request :)

**Comment by albert0815** [comment]
Just leaving this as a hint: Setting graphQlClientCredentials to include didn't work out of the box for me. The reason is that including credentials only works if cors origin is set to something specific. Since cors setting in the api in the apollo server is left in its default (which is origin set to *) setting graphQlClientCredentials to include in the dashboard failed with a cors error. I assume this can only be solved by adjusting the api source.

BTW: Did I understand it correct that the director is writing in the mongodb which is read by the api? Somehow in my above comment I assumed that the director would issue requests to the api to store e.g. execution results. But after quickly checking the source it doesn't look like that.

**Comment by Seraf** [comment]
Hello !
We just deployed sorry-cypress on our K8S cluster, and we'd like to secure it a bit now :)
@StefanS-O did you make some progress on it?

**Comment by Seraf** [comment]
We spent some time trying to secure things a bit, here is what we did:
- API: we added a basic auth on top of it, through the ingress
- Dashboard: we didn't add basic auth here as the first query to the API will trigger a browser popup asking for credentials
- Director: we tried to add a basic auth here, but then Cypress seems to time out. It looks like it opens a socket but doesn't support the HTTP basic auth thing... so we instead used the `ALLOWED_KEYS` attribute to make it a bit more secure.
- The S3 Bucket: the quick win here was to disable the listing on S3 permissions. Therefore, even if a video can be brute-forced by making requests to find the hash, it's quite hard to find it ...

It's not the "most secured" setup but should be enough for the moment until some work is done on this topic ;-)
Any comment? Did I miss something/a component?

**Comment by StefanS-O** [comment]
Hi @Seraf, i hadn't time to look into it, there was other stuff in the way.
Regarding the director timeout: wouldn't it work to skip basic auth for IP / IP ranges from the runner? Not ideal, but might work, as long as the runners do have a fixed ip or range.

**Comment by Seraf** [comment]
Yes, it should probably work, but as the workers machines are containers spawn by the CI, in the cloud, we don't want to be limited with IP Range :sweat_smile: :wink:

**Comment by j-martin** [comment]
For people on GCP, [IAP](https://cloud.google.com/iap) worked pretty well for us (the API needs to use the same host so we put it under `/api/*`).

**Comment by ImanMahmoudinasab** [comment]
@agoldis and others. I can see many people have interest on this feature. I think using [Passport.js](https://github.com/jaredhanson/passport) it is not too hard to implement the feature.

**Comment by YossiSaadi** [comment]
> For people on GCP, [IAP](https://cloud.google.com/iap) worked pretty well for us (the API needs to use the same host so we put it under `/api/*`).

Any chance you can elaborate on what URI you used on Google's OAuth2? I've implemented IAP with load balancer and all other needed configuration, but if I use the URI supplied by Google I get access denied for all the organization, with no email eligible.

**Comment by TomaszG** [comment]
FYI, this can be currently achieved also with an ouath2 proxy, e.g. https://github.com/oauth2-proxy/oauth2-proxy

**Comment by mogusbi-motech** [comment]
Can we reopen this issue as I think it's still an important feature request @agoldis

**Comment by Rohmilchkaese** [comment]
Push for that one :-) OIDC Login would be such a nice addition!

**Comment by scmrus** [comment]
I choose [Cloudflare Access](https://www.cloudflare.com/zero-trust/products/access/) to solve that problem.
