### ISSUE TITLE
Feature Request: Add ability to set default timeout when new projects are created

### ISSUE THREAD

**Issue by KyleThenTR** [sorry-cypress/sorry-cypress#508]
- [ ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Currently, when we upgrade versions of sorry cypress, it takes down the ECS tasks so previous project settings are lost. When the project is created, the timeout is generated automatically at 3 minutes and have to remember to go in and set this to 30 minutes.

## Why is it needed? What is the value? For whom do we build it?
Better configurability and less needed to remember to do if upgrading versions.

## High-level feature overview
Would be able to pass in an environment variable setting the default timeout that is set when a new project is created.

**Comment by MDjhowley** [comment]
Isn't that this: `INACTIVITY_TIMEOUT_SECONDS`?

See: https://docs.sorry-cypress.dev/configuration/director-configuration#common-configuration
