### ISSUE TITLE
Feature Request: Add button to reset all failed spec file at once

### ISSUE THREAD

**Issue by bastienmoulia** [sorry-cypress/sorry-cypress#514]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Adding an option to reset all failed spec file in one click.

## Why is it needed? What is the value? For whom do we build it?

When there is failed test due to memory issue (or other), I would like to reset all test in one click instead of having to reset them one by one.

Maybe with a button on the table header or above or below the table.

**Comment by Baoyuantop** [comment]
Hi is there a corresponding plan for this feature? If not I would be happy to help provide.

**Comment by kltdwrds** [comment]
We are also interested in this!
