### ISSUE TITLE
Need to add more filters

### ISSUE THREAD

**Issue by Arunk28** [sorry-cypress/sorry-cypress#518]
- [ ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
I want to filter out all the failed or passed test run  and date range [today,yest,thiswk,custom .... etc]
currently not possible in currents
## Why is it needed? What is the value? For whom do we build it?
because it is easy to filter out the pass or fail And Date wise filter
## image
![image](https://user-images.githubusercontent.com/7352047/148216597-98444d2d-3119-4770-9158-22664a191b7a.png)

**Comment by agoldis** [comment]
Thanks for your request @Arunk28, this repository is for OSS free, self-hosted version of sorry-cypress, I am closing that issue and moving it into internal workflow for the paid version (currents.dev)
