### ISSUE TITLE
Screenshots uploaded to AWS S3 have wrong Content-Type , hence Chrome downloads image instead of displaying inline

### ISSUE THREAD

**Issue by mmtmohit** [sorry-cypress/sorry-cypress#519]
## Summary

The content type metadata of uploaded screenshot images is 'binary/octet-stream' (as seen in Management Console) while It should be 'image/png' so that when I click on image displayed inline to the failed test on the dashboard , browser can open/display inline in same/new tab instead. of force download.

I checked the logs of director service and can see the upload url has query param Content-Type being sent as 'image/png' , yet when I checked metadata for the S3 object in AWS management console, it shows 'binary/octet-stream' strange enough.
Question is why the s3 sdk is not putting the right content-type of the image.

## How to reproduce

1. Deployed latest docker versions of director, dashboard and api service to herokuapp
2. Added new S3 bucket manually in AWS, new IAM user with below. policy :
    {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:Put*"
            ],
            "Resource": [
                "arn:aws:s3:::xxxxxxbucket-east/*"
            ]
        }
    ]
}
3. Added Cloudfront distribution in front of s3 origin and added OAI policy to S3 bucket
4. Ran tests pointing to director service

## Relevant logs / screenshots
AWS s3 console - object metadata :
<img width="1560" alt="Screen Shot 2022-01-08 at 11 54 09 AM" src="https://user-images.githubusercontent.com/11607818/148634228-04d55c65-be9d-42b2-bdc4-ace1b225b31d.png">

dashboard failed test screenshot :
<img width="1541" alt="Screen Shot 2022-01-08 at 11 59 07 AM" src="https://user-images.githubusercontent.com/11607818/148634401-86a56cd8-cad5-4a78-b0f6-4b4ed8547bd8.png">
Exact Issue - When the above screenshot image is clicked to open in browser, it gets force downloaded in place of. opening inline

- relevant logs from director service:

- 2022-01-07T10:07:23.552259+00:00 app[web.1]: {"level":30,"time":1641550043552,"requestId":"afefe475-ab9b-4593-805f-4ad5ec9431a6","instanceId":"ef5cf9b1-c130-4ce8-9024-dcc75e9993ef","screenshotUploadUrls":[{"readUrl":"https://xxxxxbucket-east.s3.amazonaws.com/184f74672988b160fb4b46fd9b687228.png","**uploadUrl**":"https://xxxxxbucket-east.s3.amazonaws.com/184f74672988b160fb4b46fd9b687228.png?**Content-Type=image%2Fpng**&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxx&X-Amz-Date=20220107T100723Z&X-Amz-Expires=60&X-Amz-Signature=xxxxxx&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read","screenshotId":"53dqz"},{"readUrl":"https://xxxxxbucket-east.s3.amazonaws.com/a1ba2e6fdf1de2de678f093a25a73598.png","uploadUrl":"https://xxxxbucket-east.s3.amazonaws.com/a1ba2e6fdf1de2de678f093a25a73598.png?Content-Type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxx&X-Amz-Date=20220107T100723Z&X-Amz-Expires=60&X-Amz-Signature=xxxxxxx&X-Amz-SignedHeaders=host%3Bx-amz-acl&x-amz-acl=public-read","screenshotId":"bmj00"}],"videoUploadInstructions":null,"msg":"Sending assets upload URLs"}

## Environment

- sorry-cypress version: `latest tagged docker images`
- cypress version: `8.5.2`
- platform: `docker | herokuapp cloud`
- service: ` director `

**Comment by agoldis** [comment]
@mmtmohit Seems like that's an intended behaviour 
@ImanMahmoudinasab what do you think?

**Comment by agoldis** [comment]
Seems like cypress doesn't provide `content-type` when uploading files: https://github.com/cypress-io/cypress/blob/1ff7839a19a5dd4a4891a0e46263183d06d66849/packages/server/lib/upload.js#L9

The singed upload URL contains `content-type` though... any ideas?

**Comment by ImanMahmoudinasab** [comment]
Hi! I'm going to add image preview feature for test screenshots. I'm not sure if it would resolve the issue @mmtmohit have with screenshots.

**Comment by matrunchyk** [comment]
Is it still in progress? If not, I would try to fix it, as this is a very annoying issue for us (though I have never contributed to this repo yet)

**Comment by agoldis** [comment]
@matrunchyk appreciate your help - the issue is still relevant

**Comment by matrunchyk** [comment]
@agoldis cool, so I'll handle the preview functionality then which should fix the original issue

**Comment by matrunchyk** [comment]
Are you guys good with that?

https://user-images.githubusercontent.com/2089828/204060040-77912462-7370-4a4d-8394-4efdb228032d.mp4

**Comment by matrunchyk** [comment]
@agoldis Looking forward to having your feedback on the PR mentioned above!
