### ISSUE TITLE
inactivity timeout functionality

### ISSUE THREAD

**Issue by tbhi** [sorry-cypress/sorry-cypress#533]
- [/] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Bring back https://docs.sorry-cypress.dev/concepts/inactivity-timeout

## Why is it needed? What is the value? For whom do we build it?

The use cases specified in the document still appear valid and the global run timeout does not seem as good, e.g. a failed worker fails the whole test run only after the longer global timeout.  Additionally when a timeout is detected it would be good if sorry cypress tried running the spec on a different worker - not clear to me from the page above whether this happens.

**Comment by agoldis** [comment]
Thanks for opening that issue @tbhi

Inactivity timeout was looking promising, I can't remember what other reason resulted in replacing inactivity timeout, it was some edge case that I cannot remember now.

I am open to bring it back, but I need help with planning and implementing it. 

Specifically, in context of:

- enumerating all the use cases
- consider multiple run groups within a run
- triggering integration events
