### ISSUE TITLE
Failed GH post request crashes director service

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#534]
## How to reproduce

Add non-existing URL as GH integration, create a run
See the director crashing

**Comment by alexniculae** [comment]
@agoldis, did you ever see such a thing happening with GitLab integration as well?

I see some issues memory some times that cause my process to terminate with an error, when I have a high number of tests running, and I am not really sure where it's coming from.

Could it be related in any way, are you able to do some tests on your end with a GitLab to rule this out?

**Comment by agoldis** [comment]
@alexniculae this ticket is about status check updates to github, we don't have such kind of integration with GitLab. 
If you're able to capture those errors and share with I'd be happy to help troubleshooting.

**Comment by alexniculae** [comment]
Thanks @agoldis; seems that this is most likely related to Cypress itself thought, and problems with uploading artifacts to the dashboard and/or issues with Electron and its limitations

- https://github.com/cypress-io/cypress/issues/17627
- https://github.com/cypress-io/cypress/issues/18413

I updated Issue #538, maybe that would allow us to work around this issue by
- relaunching the pipeline and
- resetting the spec 
- when the pipeline fails for such reasons before finishing the run
