### ISSUE TITLE
Sorry Cypress error: "Something went wrong while loading the project list. Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by fhperuchi** [sorry-cypress/sorry-cypress#536]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [ ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress show a error message on main Dashboard screen:

`Something went wrong while loading the project list. Unexpected token < in JSON at position 0`

## How to reproduce

1. Install sorry-cypress via [Helm Chart](https://github.com/sorry-cypress/charts/tree/main/charts/sorry-cypress) on Kubernetes v1.21:
2. Access Dashboard: 
![image](https://user-images.githubusercontent.com/4641123/153978769-df8d11df-108f-4065-b159-443dd73b6d21.png)

I can't create a new project too because of the same error:

![image](https://user-images.githubusercontent.com/4641123/153979128-4fcc1fd4-9f43-42bc-848b-7be05c49e024.png)

## Relevant logs / screenshots

Pods running OK:
![image](https://user-images.githubusercontent.com/4641123/153978977-ed9b5596-1820-4b20-84a9-7692d9b2670d.png)

I don't have any errors on these pods logs.

## Environment

- sorry-cypress version: `2.1.1`
- cypress version: `any`
- platform: `Kubernetes` installed via kOps running on AWS
```
$ kubectl version --short 
Client Version: v1.23.3
Server Version: v1.21.5
```
- service: `dashboard`

**Comment by agoldis** [comment]
Please share the reponses from dashboard's network tab - the response is likely to be corrupted due to API service failure or misconfiguration

**Comment by fhperuchi** [comment]
> Please share the reponses from dashboard's network tab - the response is likely to be corrupted due to API service failure or misconfiguration

I've fixed that setting the `dashboard.environmentVariables.graphQlSchemaUrl`:

![image](https://user-images.githubusercontent.com/4641123/154102305-eaf0a3c1-dee0-4848-a018-c3e203d40172.png)

Thank you @agoldis !
