### ISSUE TITLE
Fullscreen video playback

### ISSUE THREAD

**Issue by Zaista** [sorry-cypress/sorry-cypress#539]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Fullscreen video playback

## Why is it needed? What is the value? For whom do we build it?
Video playback area is quite small, even if you hide both collapsible menus. If you have a lot of content on your website it get's hard to review videos.

## High-level feature overview
Add button for fullscreen video mode

## Other
Sorry-Cypress v2.1.0

**Comment by alexniculae** [comment]
@Zaista, as a workaround until this is delivered (if it even make sense to be delivered)
- right click on the video while playing and
- click **Show all controls** from the options list

This will allow you to interact better with the player, download the video, etc.
