### ISSUE TITLE
sometimes parallel is not working

### ISSUE THREAD

**Issue by raftx24** [sorry-cypress/sorry-cypress#540]
Hey.
I'm using sorry-cypress with 10 parallel machines. sometimes it cannot detect parallel runs and sorry-cypress tries to run them independently(although they have the same ci-build-id!). I checked also the start time, they are very close to each other(about one minute difference)
![image](https://user-images.githubusercontent.com/10864136/155482291-0ef8cbd7-3f6f-41f8-a297-15ca15a261b2.png)

**Comment by agoldis** [comment]
Please use the issues template and provide more details
