### ISSUE TITLE
Parallel is not working

### ISSUE THREAD

**Issue by raftx24** [sorry-cypress/sorry-cypress#541]
Please note - issues that are not following the template will be closed automatically:

- [ x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Hey.
I'm using sorry-cypress with 10 parallel machines. sometimes it cannot detect parallel runs and sorry-cypress tries to run them independently(although they have the same ci-build-id!). 
`CYPRESS_API_URL="http://director" npx cy2 run --parallel --record --key same-key --ci-build-id $BITBUCKET_BUILD_NUMBER`
this should create one test with 10 agents but sometimes it creates 10 runs independently!

## How to reproduce

it happens sometimes.
1. try to run specs in parallel with 10 machines.
2. sometimes you see one run with 10 agents sometimes you see 10 runs and each of them has one agent!

## Relevant logs / screenshots
![image](https://user-images.githubusercontent.com/10864136/155486392-3b671924-5246-4194-951c-fcd043486c39.png)

## Environment

- sorry-cypress version: latest
- cypress version: 9.5
- platform: docker
- service: director

**Comment by agoldis** [comment]
@raftx24 based on past experience, you might not have mongodb indexes initialized can you please make sure the indexes are defined as in https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/mongo/src/db.ts#L73

**Comment by samgreen-spp** [comment]
For anyone that may come across this issue using Bitbucket and AWS we found our solution here https://github.com/sorry-cypress/sorry-cypress/issues/371

Essentially we just had to stop the sorry-cypress task in ECS which created the correct indexes.

Thanks for all of your efforts with sorry-cypress! :)

**Comment by raftx24** [comment]
#542 solved the issue completely.
