### ISSUE TITLE
GraphQL Cannot return null for non-nullable field RunMeta.ciBuildId.

### ISSUE THREAD

**Issue by Upgreydd** [sorry-cypress/sorry-cypress#544]
## Summary

When listing one of projects I'm receiving error `Cannot return null for non-nullable field RunMeta.ciBuildId.` second project is fine.

## Environment

- sorry-cypress version: `2.1`
- platform: `docker`
- service: `all`

**Comment by agoldis** [comment]
There's a corrupted run in your database, that's very uncommon. I suggest just deleting the corrupted run... 

Do you have any idea how a run without `run.meta.ciBuildId` was created ?

**Comment by agoldis** [comment]
@Upgreydd
