### ISSUE TITLE
Cy2 is running on cypress-dashboard not on sorry-cypress dashborad

### ISSUE THREAD

**Issue by SnehithaN** [sorry-cypress/sorry-cypress#548]
Hi, I am new to Sorry-cypress. I set docker image for sorry-cypress then added cy2 to my framework and set CYPRESS_API_URL to http://localhost:1234/" using 'set CYPRESS_API_URL="http://localhost:1234/"' but when I ran the tests they are still pointing to cypress-dashboard. 
![image](https://user-images.githubusercontent.com/8208393/157509153-d028a42b-4772-48e0-8344-85b41e226d93.png).
Can anyone help me resolve this issue? Should I change anything?

**Comment by agoldis** [comment]
The environment variable is not available for some reason, please try running. Also, please follow issue template

```
CYPRESS_API_URL="http://localhost:1234/" npx cy2 ...
```

**Comment by SnehithaN** [comment]
@agoldis , I tried that too, even that is not working, I am getting below error.
![image](https://user-images.githubusercontent.com/8208393/157535420-eb1a87dc-4a5b-407f-bb98-b6b320454d09.png)
