### ISSUE TITLE
Specs on parallel tests not being assigned to any machine

### ISSUE THREAD

**Issue by Fryuni** [sorry-cypress/sorry-cypress#552]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error - *There is no network error that I could find*

## Summary

When running our tests on our CI some of the specs are not being executed by any worker (not even starting).
We run our tests in parallel with two groups, 25 workers running chrome and 25 running firefox, with a total of 114 spec files

This happened 6 out of our last 10 runs, all for the exact same commit and config. There doesn't seem to be any pattern for which spec is left out, every time it was a different spec.

We did the same test using Currents.dev and [got the same problem](https://app.currents.dev/run/a1c2e18918133e99af80e10b1326bff8), 2 specs never executed (not the same as any of the other runs).

I searched for the name of the spec files on the logs of all the workers and even with the debug it is only mentioned when searching for the files at the start, it is not assigned to any of the workers and there are no errors.
On the UI, the specs show up as allocated to a machine, but the exact machine that was supposed to run it has no mention of the file on the logs

The workers are exiting with code 0 as if there was no problem at all and on their own logs they report no failure.

## How to reproduce

1. Open a PR
2. Our CI start the workers
3. Workers connect SC and start claiming spec files to run
4. All workers eventually reach for the 

## Relevant logs / screenshots

- Logs from `DEBUG=cypress:server:api cy2 ....`. There was no network error, but if necessary I can rerun with this and post the log.
- Please submit relevant logs from director / api / dahsboard service

#### Screenshot

![image](https://user-images.githubusercontent.com/11063910/159334524-fce797ef-d83f-4d1f-95a4-0487f6f32dbf.png)
![image](https://user-images.githubusercontent.com/11063910/159334722-636356e7-cea2-4d23-959a-3023a53ed32c.png)
![image](https://user-images.githubusercontent.com/11063910/159334888-6347fbb6-2443-4a17-9490-413f07f6aceb.png)

## Environment

- sorry-cypress version: `2.1.1`
- cypress version: `9.5.0`
- cy2 version: `1.3.0`
- platform: `docker`
- service: `director`

**Comment by Fryuni** [comment]
Any recommendations on how to post the logs? They are too long for GH and for Pastebin (800KiB)

**Comment by agoldis** [comment]
@Fryuni please also take a look here: https://currents.dev/readme/runs/run-timeouts#ci-shows-that-a-run-is-successful-but-it-has-timed-out-in-dashboard-why 

Seems like the spec files started their execution, but never reported the results back.

**Comment by Fryuni** [comment]
We have checked that already, as I mentioned in the description the executable (be it cy2 or currents) is completing successfully, the remainder of our script that runs _after_ those is also executing.

When a worker starts executing a test it logs that and also includes that file on the final report before it executes, no workers reported the result of those files not logged anything about them.

**Comment by agoldis** [comment]
In that case the logs should have a incoming request to update instance results:
- find the instanceId associated with idle spec files
- find the incoming POST request `POST /instance/<id>/results`
- examine the logs for errors / logs / traces

**Comment by Fryuni** [comment]
We found out that there was a very narrow edge case on the combination of our NGINX setup, one of our cypress plugins and cypress itself that caused this problem to happen with no error message.

Thanks for all the help @agoldis
