### ISSUE TITLE
Less or encrypted data in instances collection

### ISSUE THREAD

**Issue by toonvd** [sorry-cypress/sorry-cypress#558]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Less or encrypted data in instances collection for more security.

## Why is it needed? What is the value? For whom do we build it?
When trying to fill for example usernames and passwords in a field or making calls to an API, credentials that belong to this API are exposed (raw) in the instances collection. This risks leaking of sensitive information when the database is compromised. As far as I can tell, this info is not even shown in the dashboard. This is also the same for env variables, they are often used as a source for credentials.

## High-level feature overview
I see 2 possibilities here:

- save less data
- encrypt data

**Comment by agoldis** [comment]
Thanks for open this request @toonvd. The system, in overall is quite open - there's no authentication etc.

The motivation is to keep the setup process as simple as possible - it is already somewhat convoluted. If you have an effective solution for implementing those requirements, please share.

**Comment by toonvd** [comment]
Hi @agoldis 

To be clear, this is a security issue, saving potentially private data without encryption in a DB is always dangerous.
The test payload is a JSON object, one could add logic to alter this object to at least remove the ENV key.
(maybe in the model? https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/execution/mongo/instances/instance.model.ts#L50)
A second step would be to document to always read passwords from the Cypress env file and never use them inline in tests.

That would be the easiest solution but it would not be dummy proof.

Another solution is working with a random crypt key (determined on installation) and using this crypt key to encode and decode instance data.

**Comment by agoldis** [comment]
@toonvd seems like you've figured that out, now we are one step closer to a PR!
