### ISSUE TITLE
Support Slack Apps for webhooks

### ISSUE THREAD

**Issue by PaulLesur** [sorry-cypress/sorry-cypress#560]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Support Slack Apps webhooks.

## Why is it needed? What is the value? For whom do we build it?
Only legacy webhooks are supported to have tests results in Slack. Slack is deprecating these webhooks. You cannot set `icon_url` and `username` when using a Slack app's webhook. 

## High-level feature overview
I think the feature consists of just removing `icon_url` and `username` from the sent json.

**Comment by agoldis** [comment]
@PaulLesur Thanks for reporting that! Are you seeing requests failing because of `icon_url` and `username`? 

Also, that would also require providing creating a custom Slack application for each installation + storing and using its details.

**Comment by MDjhowley** [comment]
I'm not sure this is a problem.  It is true that slack is deprecating incoming webhooks and that this needs to be replaced with a slack app but you can just create a custom slack app for this purpose in your workgroup.

Follow https://api.slack.com/messaging/webhooks (steps 1 and 2)

The app specifies the channel, username and icon but I'm not seeing any problems using v2.0.2 i.e. no requests are failing and the webhook is currently supporting slack apps
