### ISSUE TITLE
When the spec name contains dots the name is trimmed at the first dot.

### ISSUE THREAD

**Issue by REZ-bdoty** [sorry-cypress/sorry-cypress#567]
## Summary

We use dots in our spec names to group them. 
Example:
Group1.data.test_spec.js
Group2.pn.test_spec.js

When the specs are displayed on the dashboard they get the name as either Group1 or Group2. Hovering on the link gives the full name, but it would be nice to have them displayed correctly as well in the table.

## How to reproduce

1. Create two specs Group1.data.test_spec.js and Group2.pn.test_spec.js
2. Execute tests with SC
    Notice: the spec names show as Group1 and Group2 
    Expected: the full spec names to be displayed

## Environment

- sorry-cypress version: `2.1.1`
- cypress version: `9.5.3`
- platform: `Local Docker Desktop`
- service: `all`

**Comment by ImanMahmoudinasab** [comment]
What about the following names for your example?
`Group1.data.test_spec.js` => `Group1 data`
`Group2.pn.test_spec.js` => `Group2 pn`

**Comment by REZ-bdoty** [comment]
Seems odd that SC would arbitrarily decide what part  of the test name to show when this can be different for each team. Personally, I would like to see the full name of the test spec. If that isn't possible then the name of the spec itself. From my example above it would be test_spec.js for both. 
Is it possible to get the full name of the test spec in the UI? If not, would it be possible to have a configuration option on what part of the spec name to show based on a set of rules?

**Comment by ImanMahmoudinasab** [comment]
I fixed the issue, and SC would only remove the file extension. Also, now there is an option to turn off the spec name beautifier completely or see the specs' full address:

<img width="1750" alt="2022-06-18 at 7 33 AM" src="https://user-images.githubusercontent.com/5295554/174443808-ed0ea282-aa9f-4c0f-8f62-8b7fe011f232.png">

<img width="1746" alt="2022-06-18 at 7 31 AM" src="https://user-images.githubusercontent.com/5295554/174443819-e018fded-2ed9-4df4-8d74-41f9cf002c3e.png">

<img width="1749" alt="2022-06-18 at 7 34 AM" src="https://user-images.githubusercontent.com/5295554/174443821-7997a751-3fe9-4aaf-b057-a6672273479f.png">
