### ISSUE TITLE
Support grouping for the same run

### ISSUE THREAD

**Issue by xtroncode** [sorry-cypress/sorry-cypress#57]
Hi,

I am trying to integrate cypress in our jenkins based ci environment.

I have separated tests for mobile and desktop versions of the site using a file naming convention as `*.mobile.spec.js` and `*.desktop.spec.js` and `*.common.spec.js` 

When I run cypress in the following form by passing the same `--ci-build-id` but different `--spec` , two different runs are created in the dashboard.

```groovy
 parallel (
                "cypress mobile tests process 1" : {
                        def returnCode1 = sh returnStatus: true, script: "cypress run --record --key something --parallel --ci-build-id ${env.BUILD_TAG} --env TEST_TAGS=${tags} --config baseUrl=${baseUrl} --config-file cypress.mobile.json --spec 'cypress/integration/**/*.mobile.spec.js' ", label: "Running"
                        returnCodes.add(returnCode1)
                },
                "cypress mobile tests process 2": {
                        def returnCode2 = sh returnStatus: true, script: "cypress run --record --key something --parallel --ci-build-id ${env.BUILD_TAG} --env TEST_TAGS=${tags} --config baseUrl=${baseUrl} --config-file cypress.mobile.json --spec 'cypress/integration/**/*.mobile.spec.js' ", label: "Running"
                        returnCodes.add(returnCode2)
                },
                "cypress common tests process 1": {
                        def returnCode5 = sh returnStatus: true, script: "cypress run --record --key something --parallel --ci-build-id ${env.BUILD_TAG} --env TEST_TAGS=${tags} --config baseUrl=${baseUrl} --config-file cypress.mobile.json --spec 'cypress/integration/**/*.common.spec.js' ", label: "Running"
                        returnCodes.add(returnCode5)                    
                }
)
```

Let me know if any more information is needed.

Thanks.

**Comment by agoldis** [comment]
@xtroncode thanks for bringing that up! 

As far as I remember the original cypress also does not allow having different specs for same run, unless there's some kind of [grouping](https://docs.cypress.io/guides/guides/parallelization.html#Grouping-test-runs) defined.

I am renaming your request to implement supporting grouping.

**Comment by agoldis** [comment]
Also, please note https://github.com/agoldis/sorry-cypress/issues/35 - if you can  eventually share your Jenkins setup, there was an interest in this type of integration

**Comment by xtroncode** [comment]
@agoldis  thanks for considering this. I'll try to share my Jenkins setup at #35 once figure out the entire process.

**Comment by Upgreydd** [comment]
https://github.com/sorry-cypress/sorry-cypress/pull/181 grouping by `--group` parameter.
