### ISSUE TITLE
Multiples rows on the Dashboard when you run the test in different nodes/machines in parallel.

### ISSUE THREAD

**Issue by estefafdez** [sorry-cypress/sorry-cypress#574]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

When you run the tests in parallel on different machines, on the dashboard, there is a row on each node/machine instead that only 1 per build. 

<img width="1788" alt="Screenshot 2022-05-18 at 11 02 14" src="https://user-images.githubusercontent.com/6990209/169002402-55acc9d1-ec22-447b-b3dc-9ff34d164292.png">

Image with 2 rows on the same execution triggered by Jenkins. There are 2 rows only because it was triggered with only 2 machines. 

<img width="1771" alt="Screenshot 2022-05-18 at 11 02 22" src="https://user-images.githubusercontent.com/6990209/169002518-1ff660b5-d01e-4b6d-9c91-adbed13ff5c2.png">
If you check the number of specs, it seems like each node took half of the spec and it's ready to execute it. 

## How to reproduce

1. Update sorry cypress to version 2.1.2
2. Run the cypress tests in parallel 
3. Check the dashboard. 

## Relevant logs / screenshots

No relevant logs because the tool is working as expected.

## Environment

- sorry-cypress version: `2.1.2`
- cypress version: `2.1.2`
- platform: `docker`
- service: `all`

**Comment by agoldis** [comment]
Please see if this helps: https://app.gitbook.com/o/-MT4mUcrnbXWgd1xvl_x/s/-MS6gDAYECuzpKjjzrdc/configuration/faq#cypress-parallelization-is-not-working-i-see-a-separate-build-for-each-machine

**Comment by estefafdez** [comment]
Hello @agoldis , the problem was solved after deleting the completely MongoDB database and then running the test with the new sorry cypress version. We don't know exactly what happened, because we've been updating the tool since version 1 without any problem (and without deleting the DB before the update). 

Now the problem is solved. Thanks again and thanks for such a great tool!
