### ISSUE TITLE
Minio uploads are not accessible from dashboard

### ISSUE THREAD

**Issue by Vaibhav-npc** [sorry-cypress/sorry-cypress#575]
## Summary

Video and image files are uploaded to minio storage bucket, and are accessible from minio.
But the files are not loading on sorry-cypress dashboard. It seems instead of signed URL, only URL with object ID are sent from API.

## How to reproduce

Install cypress with helm chart. Only config change done was minio replicas are set to 1 as I was having multi attach issue on kubernetes. 

## Relevant logs / screenshots

Video not loading on dashboard 

![image](https://user-images.githubusercontent.com/81007240/169278330-8539ac46-f6ed-45e2-934f-bbe74a64ff47.png)

mp4 file URL is with minio object ID. Here I think it should be signed URL which should not require login to minio to view video.

![image](https://user-images.githubusercontent.com/81007240/169278545-23d79d37-feed-422c-97db-2749183c29f1.png)

Below is API response

![image](https://user-images.githubusercontent.com/81007240/169279221-bd55d606-5fa3-4f37-82ec-41d4c8f84029.png)

The file is available on minio

![image](https://user-images.githubusercontent.com/81007240/169278859-97c650da-b3d2-4a2e-823b-7e842b5feebd.png)

## Environment

- sorry-cypress version: `v2.1.2`
- cypress version: `9.6.1`
- platform: `helm chart on azure`
- service: `dashboard`

**Comment by Vaibhav-npc** [comment]
@agoldis The url redirects to minio login page.

**Comment by agoldis** [comment]
There's something wrong with your minio configuration then

**Comment by Vaibhav-npc** [comment]
@agoldis Thanks for your reply, but not sure where I could have gone wrong with the Minio configuration as I am using default helm values, except for host name and number of replicas.
For ingress, as default chart does not support latest ngnix ingress, I have created Kubernetes load balancer to expose the Minio deployment.
I have attached the minio section from helm values.

[helmMinioValues.txt](https://github.com/sorry-cypress/sorry-cypress/files/8736100/helmMinioValues.txt)

**Comment by agoldis** [comment]
@Vaibhav-npc please make sure your minio files are accessible when you are trying to open them in browser. not sure what other changes you did to your deployment, but it's quite hard to troubleshoot. You can also try getting help on our slack channel https://docs.sorry-cypress.dev/support

**Comment by Vaibhav-npc** [comment]
@agoldis What I think happening is, signed URL is only used for uploads and not for get request. 
[Step 5](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration#caveats-of-using-minio)  should be getting signed URL for browser. Here its only fetching URL with object ID which has no auth/signature information.

If get is allowed just with object ID, anyone on internet can access the video/screenshots.

**Comment by Vaibhav-npc** [comment]
When I set minio read only policy to * on the bucket, videos are now loading fine.

Adding to my last comment, to increase the security of uploaded assets, we should think of adding signing function to get requests as well.

**Comment by agoldis** [comment]
@Vaibhav-npc great you've discovered the documentation :) Would be happy to review a PR with implementation
