### ISSUE TITLE
sorry cypress dashboard is not accessible or takes long time to access and we have json parser error

### ISSUE THREAD

**Issue by vaibhavi789** [sorry-cypress/sorry-cypress#582]
Please note - issues that are not following the template will be closed automatically:

- [ ] I have verified that all sorry-cypress services are running and accessible
- [ ] I have read documentation and found no answer to my problem
- [ ] I have searched issues / discussions and found to answer to my problem
- [ ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
sorry cypress dashboard is not accessible or takes long time to access and we have json parser error
Sorry cypress dashboard was accesible in a second , but now not

## How to reproduce

1. Step A
2. Step B

## Relevant logs / screenshots

<img width="1784" alt="Screenshot 2022-06-08 at 14 28 16" src="https://user-images.githubusercontent.com/58173901/172631007-cd4a4214-aa97-404d-9acf-bbb7e36537b3.png">

## Environment

- sorry-cypress version: `v1.1`
- cypress version: `9.6.0`
- platform: `AWS`
- service: `api | director | dashboard | all`

**Comment by vaibhavi789** [comment]
sorry cypress dashboard is not accessible or takes long time to access and we have json parser error
Sorry cypress dashboard was [accessible](url) in a second , but now not
sorry-cypress version: v1.1
cypress version: 9.6.0
platform: AWS

**Comment by agoldis** [comment]
Please update to v2+

**Comment by vaibhavi789** [comment]
Thank you for your response
I have upgraded to v2.
Withing week memory utilisation is very high.
Again dashboard slow down..difficult in loading some of the projects
Please advise what I have to do?
