### ISSUE TITLE
docker-compose.minio.yml out of date

### ISSUE THREAD

**Issue by wyatt89** [sorry-cypress/sorry-cypress#586]
Please note - issues that are not following the template will be closed automatically:

- [x ] I have verified that all sorry-cypress services are running and accessible
- [x ] I have read documentation and found no answer to my problem
- [x ] I have searched issues / discussions and found to answer to my problem
- [x ] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

The sorry-cypress dashboard fails to retrieve failure screen shot from minio

Does the /etc/hosts file needed to be modify when running with docker-compose?
## How to reproduce

1. Run docker-compose up 
2. Start a failing test
3. Go to dashboard and view failing test details. A broken image icon will be displated
4. Clicking image shows the following error xml
5. 

<Error>
   <Code>NoSuchKey</code>
  <Message> The specified key does not exist.</Message>
  <Key>...</Key>
  <BucketName>sorry-cypress</BucketName>
  <Resource>/sorry-cypress/...png<Resource>
  <RequestId>...</RequestId>
  <HostId>...</HostId>
</Error>

## Environment
- Mac OSX
- sorry-cypress version: `2.0.0`
- cypress version: `9.3.1`
- platform: `docker-compose`
- service: `all + minio`

**Comment by agoldis** [comment]
https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration
