### ISSUE TITLE
Feature Request : Way to filter runs in dashboard

### ISSUE THREAD

**Issue by xtroncode** [sorry-cypress/sorry-cypress#59]
I believe that it would be great if we could filter runs by build id in the dashboard.
Let me know if I can help implementing this.

**Comment by agoldis** [comment]
Today the displays paginated runs, the pagination rate is hardcoded and is defined on the API.
The simplest solution would be to have a GraphQL query that would returns results based on a search criteria, and display the results non-paginated. 

The implementation of pagination is cursor-based and I quite sloppy, I am not sure how convenient it would be to work with that code :)

@xtroncode Let me know if you're interested in this task, I will assign to you so other won't be working on it.

**Comment by xtroncode** [comment]
@agoldis  

I have a wip PR #63 . It's very early stage. But I got stuck at the date range query as currently `createdAt` field is stored as string. I am new to mongodb, typescript as well as graphql. 

Can you point me towards what needs to be done to query in a date range when date is stored as string ? As per my research, I could not find a good way (but my mongo know how is very limited) .

Do we need to have migrations to change the data type of the field in existing data to `ISODate` and store date in `ISODate` type going forward ?

https://stackoverflow.com/questions/41117820/inserting-date-value-from-nodejs-to-mongodb

**Comment by dlavrenuek** [comment]
I would like to work on this issue. When I started implementing it, I realized that the same feature should be implemented for projects, so I created a separate issue for it:  #185
