### ISSUE TITLE
Skipped tests show always 0 on quick overview

### ISSUE THREAD

**Issue by tester-at-bmi** [sorry-cypress/sorry-cypress#596]
## Summary

Running test suite that includes tests that are skipped are not correctly displaying the skipped tests in the summary.

## How to reproduce

1. Run a test suite including skipped tests

## Relevant logs / screenshots

![Naamloos](https://user-images.githubusercontent.com/100684771/176382681-ed92bd19-01a7-430f-beb8-0ce1eb60778f.png)

## Environment

- sorry-cypress version: `2.1.2`
- cypress version: `10.3.0`
- platform: `docker`
- service: `all`

**Comment by agoldis** [comment]
Resolved in 2.2.0
