### ISSUE TITLE
Skipped tests make spec file fail

### ISSUE THREAD

**Issue by luischq** [sorry-cypress/sorry-cypress#598]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ ] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary
We are trying sorry cypress with the fix in #580 you included for this but we see some strange behavior. I see in instance.controller.ts lines 88-102 that you are tagging skipped tests by cypress as failed and tests labeled "pending" by cypress to skipped, is that right?.

A skipped tests marks the spec file as "failed". So we have a situation where some tests skipped on purpose with `.skip` are tagged as failed in sorry cypress when actually for cypress all spec files pass.

## How to reproduce
- mark some tests with `.skip` and run the tests
- spec file with "skipped" tests (and no failed test) is marked as passed by cypress but as failed by sorry cypress

## Relevant logs / screenshots
Cypress output with skipped tests and all spec files passed
![cypress2](https://user-images.githubusercontent.com/20433212/176623510-629316f8-f97f-4af5-87a2-4a869aeae909.jpeg)

Dashboard for the same test run with skipped tests that mark the spec file as failed
![sc1](https://user-images.githubusercontent.com/20433212/176623541-56f06ff3-b0b9-46a3-adf1-69d7bb322ce6.jpeg)

## Environment

- sorry-cypress version: `2.1.3`
- cypress version: `9.5.4`
- platform: `docker / heml chart`
- service: `director | dashboard`

**Comment by Aeolun** [comment]
@luischq Apologies, that's was my doing.

Can you give me a sample of the code you use to skip these tests? My own dashboard shows the maximum number of tests as well, and marks them as succeeded:
![image](https://user-images.githubusercontent.com/1116482/179144743-fa989673-b75d-47f8-b334-d957188493ea.png)
![image](https://user-images.githubusercontent.com/1116482/179144674-5591b219-9bf2-4b58-8e75-1962f2619fdd.png)

**Comment by luischq** [comment]
Hi, this tests are skipped for runtime issue. You can reproduce it by throwing an error in a beforeEach() or afterEach(). Cypress will automatically skip all the tests in a spec file after that error happens.

**Comment by agoldis** [comment]
Sorry for the confusion everyone. I am going to stick to following [interpretation](https://currents.dev/readme/tests/test-status#possible-cypress-tests-statuses) of cypress tests statuses

- passed - a tests with a successful last attempt 
- failed - all attempts have failed
- skipped - tests reported by cypress runner as "skipped"
- ignored - "pending" test, i.e. `xit` or `it.skip`
- flaky - passed with a failed attempt

**Comment by luischq** [comment]
Great, thank you!

**Comment by amartinez1558** [comment]
Is there an ETA on a fix for this? I tried to downgrade to 2.1.2, but that led us to face another bug. Thanks!
