### ISSUE TITLE
API Playground is not accessible anymore on sorry-cypress 2.1.4 (ApolloServer 3)

### ISSUE THREAD

**Issue by jesuspajares** [sorry-cypress/sorry-cypress#599]
Please note - issues that are not following the template will be closed automatically:

- [X] I have verified that all sorry-cypress services are running and accessible
- [X] I have read documentation and found no answer to my problem
- [X] I have searched issues / discussions and found to answer to my problem
- [X] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [X] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress API landpage is not showing anymore the GraphQL playground after the migration to Apollo Server 3

## How to reproduce

1. Navigate to your sorry-cypress API URL
2. You'll see the landing page corresponding to the plugin ApolloServerPluginLandingPageProductionDefault (see https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages)

## Relevant logs / screenshots

![image](https://user-images.githubusercontent.com/28257457/177743391-a05eb775-61e5-42ea-b1a4-288572eaa639.png)

## Environment

- sorry-cypress version: `2.1.4`
- cypress version: `N/A`
- platform: `Azure`
- service: `api`

**Comment by tehKapa** [comment]
Is it possible to disable this playground?

**Comment by agoldis** [comment]
@tehKapa it is

**Comment by tehKapa** [comment]
> @tehKapa, it is

Ok.. how? I don't find anything on [doc](https://docs.sorry-cypress.dev/development/changelog#whats-changed-4). Sorry about that silly question

**Comment by agoldis** [comment]
https://github.com/sorry-cypress/sorry-cypress/commit/17674b3dd6c67f4dc63012385d7714a40d4bffd5#diff-650ad1c40e291fd2a0f5ace33dd5e4a957e31f8d397fd4a5e5b75c0b50927f34R40
