### ISSUE TITLE
Feature Request : Way to clean/delete older runs 

### ISSUE THREAD

**Issue by xtroncode** [sorry-cypress/sorry-cypress#60]
It would be great if we can clean up old test runs via api or through the dashboard.
Let me know if I can help implement this.

**Comment by agoldis** [comment]
Sure! The simplest solution would be to implement write query on GraphQL (API). 

The dashboard would the invoke the query based on UI inputs, but having the query  would be a great start. 

Possible query variations would be deleted specific runs or date range based.

**Comment by agoldis** [comment]
@xtroncode If you have time / wish to do that - you are more than welcome!

**Comment by xtroncode** [comment]
@agoldis  does this sound like a good api ? should the `DeleteRunResponse` include the deleted `runs` as well ?

```graphql
type Mutation {
  deleteRun(runId: ID!): DeleteRunResponse!
  deleteRuns(runIds: [ID]!): DeleteRunResponse!
  deleteRunsInDateRange(startDate: DateTime!, endDate: DateTime!): DeleteRunResponse!
}

type DeleteRunResponse {
  success: Boolean!
  message: String
}
```

**Comment by agoldis** [comment]
That looks perfect!

**Comment by xtroncode** [comment]
@agoldis

I have a wip PR #63 . It's very early stage. But I got stuck at the date range query as currently createdAt field is stored as string. I am new to mongodb, typescript as well as graphql.

Can you point me towards what needs to be done to query in a date range when date is stored as string ? As per my research, I could not find a good way (but my mongo know how is very limited) .

Do we need to have migrations to change the data type of the field in existing data to ISODate and store date in ISODate type going forward ?

https://stackoverflow.com/questions/41117820/inserting-date-value-from-nodejs-to-mongodb

**Comment by agoldis** [comment]
@xtroncode

ISO dates are lexicographically sort-consistent, i.e. you can convert a search date range to string and run string search query:

```
db.getCollection('runs').find({ createdAt: {$gt: "2020-03-12T04:17:29:00.000Z" }})
```

**Comment by kubakrzempek** [comment]
Recently I had to remove older runs in a script file and had to look through a source code of sorry cypress on how to implement this.
So if someone wants to delete older runs in a time range here's a snippet (it's JS; should be self-explanatory I hope) -- maybe it will come in handy:

```js
const axios = require('axios')

axios({
  url: SORRY_CYPRESS_API_URL,
  method: 'post',
  data: {
    query: `mutation deleteRunsInDateRange($startDate: DateTime!, $endDate: DateTime!) {
      deleteRunsInDateRange(startDate: $startDate, endDate: $endDate) {
        success
        message
        runIds
        __typename
      }
    }`,
    variables: {
     startDate: '2020-01-01T00:00:00.000Z', // some start point
     endDate:  '2020-01-10T00:00:00.000Z', // some end point
    },
  },
})
```

**Comment by vaibhavi789** [comment]
I have ecs fargate cluster on private subnet and i need to delete the older run How and where i can run the script to delete the older run will work?

**Comment by agoldis** [comment]
@vaibhavi789 spin a new EC2 instance within the subnet

**Comment by vaibhavi789** [comment]
Thank you so much

**Comment by rrauenza** [comment]
Expanding a bit on the example -- this one deletes things older than 90 days.  (not fully tested!)

```
const axios = require('axios');
const moment = require('moment');

const SORRY_CYPRESS_API_URL = "http://localhost:4000";
const startDate = '2000-01-01T00:00:00.000Z';
const endDate = moment().subtract(90, 'days').format("YYYY-MM-DDTHH:mm:ssZ")

console.log("Removing runs from", startDate, "to", endDate)

axios({
  url: SORRY_CYPRESS_API_URL,
  method: 'post',
  data: {
    query: `mutation deleteRunsInDateRange($startDate: DateTime!, $endDate: DateTime!) {
      deleteRunsInDateRange(startDate: $startDate, endDate: $endDate) {
        success
        message
        runIds
        __typename
      }
    }`,
    variables: {
     startDate: startDate,
     endDate: endDate,
    },
  },
})
.then(response => {console.log(response)} )
.catch(error => { console.log(error)} )
```
