### ISSUE TITLE
Archiving and keeping previously reset test instances 

### ISSUE THREAD

**Issue by mattelen** [sorry-cypress/sorry-cypress#614]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Display old test instance results that have been reset.

## Why is it needed? What is the value? For whom do we build it?

When a test is flaky and it can't be retested with the retry feature, the QAs want to know why this test has failed and fix it so it doesn't happen again. This most likely will be a week or two after the feature developer (who are different from QAs) have already built, tested, and got the test to pass. At the moment, if the instance gets reset, the previous data gets deleted.

## High-level feature overview

A way to display old instance results before they got reset. This could be accessed from the test run view, but in a separate section

## Other

Thanks for building such a great product!

**Comment by agoldis** [comment]
@mattelen do you mean this "reset"?
![CleanShot 2022-08-04 at 22 44 33@2x](https://user-images.githubusercontent.com/1637928/183009678-06ea6acc-a0b7-479e-a66e-89e2d0e11e0c.png)

**Comment by mattelen** [comment]
@agoldis yeah that's the reset I mean. What are your thoughts on this idea?

**Comment by agoldis** [comment]
@mattelen  that would be quite an intrusive change - we need to keep the old record but mark it as non-electable + adjust the UI for displaying those "retried" tests correctly. 
As an alternative:
- those "reset" results can be duplicated to a separate collection and exported as a report 
- an HTTP webhook that fires on every "reset" and sends the old result - you'd be free to do anything you want with the hooks' payload

**Comment by mattelen** [comment]
Mmm the webhook idea is a great idea for our situation - I'm going to try with that. Thanks for the suggestion. In the meantime feel free to close this issue if you feel like this idea isn't of much value!

**Comment by mattelen** [comment]
@agoldis just to clarify, were the alternatives ideas to develop, or existing features to try? If they are ideas to be developed, then having an HTTP webhook I would imagine being a simple feature to implement without changing too much in the codebase.

I ask cause I finally got back on this, and I couldn't find a webhook around reset

**Comment by agoldis** [comment]
Oh it is  more complicated that I though. The hooks are implemented in the [director service](https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/director/src/lib/hooks/events.ts), but `reset` is handled by the API service [here](https://github.com/sorry-cypress/sorry-cypress/blob/fb5c4315f8f1aa92978cb160aac51cfb9c2dd65d/packages/api/src/datasources/instances.ts#L31)

The need to communicate somehow, or as an alternative, the hooks implementation should be extracted into a separate package and shared between the services.

**Comment by mattelen** [comment]
Ah I see. Yeah this just got a bit more complicated. I think having the hooks implementation extracted sounds like the best long term. Just out of interest, would it work fine putting them in the common package, or do you think it would work better putting in its own package - as I would imagine common gets imported across the board?

**Comment by agoldis** [comment]
I think own package would work better - it would be only used by backend services
