### ISSUE TITLE
sorry-cypress not stopping run after cancelling runs in CI pipeline

### ISSUE THREAD

**Issue by bjartur20** [sorry-cypress/sorry-cypress#626]
- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found no answer to my problem

## Summary

The Sorry-Cypress Dashboard doesn't complete if the Gitlab CI pipeline is cancelled. It shows as in progress and also many pending tests, though they were probably cancelled.

## How to reproduce

1. Run tests in a GitLab CI pipeline, connected to the sorry-cypress director.
2. Cancel the pipeline run before it finishes.
3. The run's completion status of the run is not updated to "false".

## Relevant logs / screenshots
![image](https://user-images.githubusercontent.com/1508187/184865168-64f0d7c9-e2fa-4986-a3b4-950ed7650984.png)

## Environment

- sorry-cypress version: `v2.3.1`
- cypress version: `10.3.0`
- platform: `AWS`
- CI: `GitLab CI`
- service: `director`

**Comment by agoldis** [comment]
That's not supported, cypress doesn't send any information back when terminated / stopped
