### ISSUE TITLE
Detecting remote origin crashes the director

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#634]
## Summary

Detecting remote origin throws 

## How to reproduce

This code:
https://github.com/sorry-cypress/sorry-cypress/blob/fb5c4315f8f1aa92978cb160aac51cfb9c2dd65d/packages/director/src/execution/mongo/runs/run.controller.ts#L77

is throwing an exception for this string: `git@bitbucket.org:checkfront/booking-manager.git`. Reported in [Slack](https://sorry-cypress.slack.com/archives/C01346MRQBY/p1661535121656459?thread_ts=1661472316.127699&cid=C01346MRQBY)

## Relevant logs / screenshots

```
{
      "level":50,
      "time":1661471794790,
      "requestId":"7ac56b3a-5e5c-4c06-8edb-dc91205ef89a",
      "error":{
         "type":"NodeError",
         "message":"Invalid URL: git@bitbucket.org:checkfront/booking-manager.git",
         "stack":"TypeError [ERR_INVALID_URL]: Invalid URL: git@bitbucket.org:checkfront/booking-manager.git\n    at new NodeError (internal/errors.js:322:7)\n    at onParseError (internal/url.js:270:9)\n    at new URL (internal/url.js:346:5)\n    at getRemoteOrigin (/app/packages/director/src/execution/utils.ts:38:28)\n    at Object.createRun (/app/packages/director/src/execution/mongo/runs/run.controller.ts:77:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handleCreateRun (/app/packages/director/src/api/runs.ts:33:20)\n    at /app/packages/director/src/lib/express.ts:10:5",
         "input":"git@bitbucket.org:checkfront/booking-manager.git",
         "code":"ERR_INVALID_URL"
      }
```

## Environment

- sorry-cypress version: `2.3.1`

**Comment by agoldis** [comment]
@bjartur20 seems like it due to your recent change. Any chance you can take a look?

**Comment by TheWanderingWalnut** [comment]
Thanks for investigating this folks, feel free to reach out if there's any more info I can provide!

**Comment by bjartur20** [comment]
Yep, taking a look
