### ISSUE TITLE
Characters not getting URL encoded in links from dashboard

### ISSUE THREAD

**Issue by dcrlsn** [sorry-cypress/sorry-cypress#642]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress does X, but should do Y

## How to reproduce

1. Step A
2. Step B

## Relevant logs / screenshots

- Please submit relevant logs from `DEBUG=cypress:server:api cy2 ....`
- Please submit relevant logs from director / api / dahsboard service
- Please submit screenshots if relevant

## Environment

- sorry-cypress version: `<here>`
- cypress version: `<here>`
- platform: `docker | cloud provider`
- service: `api | director | dashboard | all`

**Comment by dcrlsn** [comment]
sorry-cypress\packages\dashboard\src\lib\github.ts

`export const getGithubBranchURL = (repo: string, branch: string) =>
    handleSshURL(repo.replace(/.git$/, '') + encodeURIComponent(`/tree/${branch}`));` please thank you <3

**Comment by agoldis** [comment]
@dcrlsn Thanks for the suggestion :) 

- you are 5 clicks away from creating a PR
- the proposed change breaks the links
