### ISSUE TITLE
Add starting test timestamp on the cypress UI

### ISSUE THREAD

**Issue by SoulKyu** [sorry-cypress/sorry-cypress#646]
- [ ] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Just permit to know when the test has started, this would permit us to correlate informations from our server logs.

## Why is it needed? What is the value? For whom do we build it?

I think the information is already available from the test json, so it just need to be added on the UI.
![image](https://user-images.githubusercontent.com/30684712/190658395-6fcc86aa-d743-4aca-8b6a-a092834e8a94.png)

**Comment by agoldis** [comment]
Can be a simple change to the dashboard
