### ISSUE TITLE
Add project indicator to "recent builds view"

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#648]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

Not clear what project an item belongs to

![CleanShot 2022-09-16 at 23 11 15@2x](https://user-images.githubusercontent.com/1637928/190843318-ed332608-c84e-4b77-ad3e-c7e295763d0e.png)

## Why is it needed? What is the value? For whom do we build it?

... to be able to distinguish between different items in context of projects

**Comment by agoldis** [comment]
@mathpaquette

**Comment by ImanMahmoudinasab** [comment]
Do you have any idea about this one?

**Comment by mathpaquette** [comment]
@ImanMahmoudinasab yes I'm managing this one!

**Comment by ImanMahmoudinasab** [comment]
Then would you please share a general description of the solution you have in mind?

**Comment by mathpaquette** [comment]
@ImanMahmoudinasab maybe simple as this. what do you think?
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/4358455/191628272-0d91a3a7-837e-4523-b6da-3988e065b468.png">
