### ISSUE TITLE
Update nodejs image to latest lts release

### ISSUE THREAD

**Issue by solidnerd** [sorry-cypress/sorry-cypress#656]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

- Upgrade Docker Images to use latest nodejs lts release instead of an unmaintained version

## Why is it needed? What is the value? For whom do we build it?

- In order to receive security updates in future.

**Comment by agoldis** [comment]
Closed in https://github.com/sorry-cypress/sorry-cypress/pull/657
