### ISSUE TITLE
Remove pm2 manager from Director in Dockerfile

### ISSUE THREAD

**Issue by solidnerd** [sorry-cypress/sorry-cypress#659]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

- Remove [pm2](https://pm2.keymetrics.io/) from Docker Images to let the Container Orchestrator Manage the processes or replicas

## Why is it needed? What is the value? For whom do we build it?

- In order to run it properly in Container Orchestration it would be more efficient to run proccesses directly without an process manager since the container orchestrator act as manager for them.
- Why are process managers are needed in general ?
 Since node doesn't can scale by it self and its limit to a single core per node proccess typically you would use on a single instance a balancer like pm2.
- When we use a kubernetes as orchestrator we can tell kubernetes to spin multiple node proccess by creating replicas of an instance. So there is no need to spin replicas with a sub balancer in it since it introduces more complexity to handle it from the top.

**Comment by agoldis** [comment]
Thanks @solidnerd, please define "better"

**Comment by solidnerd** [comment]
@agoldis  Done and reshaped it a little bit

**Comment by agoldis** [comment]
Thanks, @solidnerd - it's much clearer now. Keep in mind that there are other considerations for using pm2:
- fast recovery from crashes - crash in one request would still allow processing of other requests after a fast recovery
- it's indented to be used not only in k8s, and other environments do not necessarily have orchestrators

Scaling up the concurrency to multiple processes was never an intent for using pm2. Is there anything specific that makes keeping using pm2 non-feasible?

**Comment by agoldis** [comment]
@solidnerd please let me know what you think, i want to clean up stale PRs

**Comment by solidnerd** [comment]
Hey @agoldis, 

I still would like to have it, but we need to rethink it a little more. Another option that comes into my mind now is to have different director builds from the single Dockerfile to support both options.


In the meantime I closed my PR.
