### ISSUE TITLE
Dashboard shows skipped tests as failed

### ISSUE THREAD

**Issue by stokrattt** [sorry-cypress/sorry-cypress#672]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 

## Summary

Sorry cypress dashboard shows skipped tests as failed

## How to reproduce

1. Run skipped tests and check dashboard (for example, describe.skip or only test skipped for one env and not skipped other)

## Relevant logs / screenshots

- Please submit screenshots if relevant
![2022-10-24_10-33](https://user-images.githubusercontent.com/25851759/197472772-0db298cd-18ab-49d1-8a67-1805794e2a1b.png)
![2022-10-24_10-43](https://user-images.githubusercontent.com/25851759/197473671-4006835c-100e-4fd8-b4e8-55da60a5d094.png)

## Environment

- sorry-cypress version: `<2.4.2>`
- cypress version: `<9.7.0 and 10.9.0>`
- platform: `docker && locally`
- service: `api | director | dashboard | all`

**Comment by agoldis** [comment]
Please see https://github.com/sorry-cypress/sorry-cypress/pull/609

**Comment by agoldis** [comment]
Also https://currents.dev/readme/tests/test-status

**Comment by stokrattt** [comment]
I don't understand, you told me it is proper?
Why? Early it was good. And in start spec file start from onlyOn('stage', () => {...)} or deskribe.skip or only it.skip without before/beforeEach block

**Comment by stokrattt** [comment]
maybe this wrong code in you PR
if (stats.failures > 0 || stats.skipped > 0) {
    return 'failed';
  }
Sometimes in this PR you equal failures for skipped...

**Comment by agoldis** [comment]
Hi @stokrattt 
Skipped means that the tests failed - thus the whole run is marked failed. 
`it.skip` would result in a "pending" state.

If you have a reproducible example of pending tests being marked as "skipped" please share.

**Comment by stokrattt** [comment]
Why skipped is mean failed?)) Skipped != failed
2.4.1 release was skipped and was all good.
Now skipped == failed, it is  wrong

**Comment by stokrattt** [comment]
> Hi @stokrattt Skipped means that the tests failed - thus the whole run is marked failed. `it.skip` would result in a "pending" state.
> 
> If you have a reproducible example of pending tests being marked as "skipped" please share.

see the screenshot, the test status is marked as skipped, but the common status is failed. Why?

**Comment by agoldis** [comment]
Skipped - a test was not excluded by a developer but wasn't run by cypress runner due to an error. The spec that contained the test cannot be marked "passed" because no tests passed and there was an error that prevented the test from running, without a developer explicitly ignoring it.

**Comment by stokrattt** [comment]
> Skipped - a test was not excluded by a developer but wasn't run by cypress runner due to an error. The spec that contained the test cannot be marked "passed" because no tests passed and there was an error that prevented the test from running, without a developer explicitly ignoring it.

Right, this test I excluded by describe.skipe or it.skip  but they don't care marked as failed.
And why did you do it this way and not like before?

**Comment by stokrattt** [comment]
it really spoils the statistics, when you go to see how much has fallen, it's a pain

**Comment by agoldis** [comment]
> > Skipped - a test was not excluded by a developer but wasn't run by cypress runner due to an error. The spec that contained the test cannot be marked "passed" because no tests passed and there was an error that prevented the test from running, without a developer explicitly ignoring it.
> 
> Right, this test I excluded by describe.skipe or it.skip but they don't care marked as failed. And why did you do it this way and not like before?


@stokrattt, please read my previous messages carefully, I am not talking about `it.skip` - I am talking about tests that cypress marked as "skipped". If you believe `it.skip` was marked as "skipped", instead of "pending", then it's a bug - please share a reproducible example.

**Comment by stokrattt** [comment]
why did you do it this way and not like before?

**Comment by agoldis** [comment]
@stokrattt please see the messages above, it has all the information
