### ISSUE TITLE
cy2 picking wrong cypress api url at times

### ISSUE THREAD

**Issue by JeromeGS** [sorry-cypress/sorry-cypress#709]
## Summary

Within the same pipeline I split my Cypress execution in 4 jobs, one or two of them connect to the CYPRESS_API_URL (slxdv005:1234) and the others try to connect to https://api.cypress.io/runs.

I use Gitlab CI parallel keyword, so there is no difference in the config. CYPRESS_API_URL is set directly, not using a variable and same for the npm script launching cy2.

## Relevant logs / screenshots

From both sides I have this config extract repeated the same number of times :
env: { codeCoverageTasksRegistered: true, API_URL: 'http://slxdv005:1234/', CACHE_FOLDER: '/opt/cache/cypress', RECORD_KEY: 'stub-...b-key' }

## Environment

- sorry-cypress version: `package cy2 ^3.2.0`
- cypress version: `package cypress ^9.6.1`
- platform: `docker`
- service: `agoldis/sorry-cypress-director:2.5.1`

**Comment by JeromeGS** [comment]
Issue solved !
The problem is linked to the way cy2 works. The thing is we launch a several projects at a time and we parallel each one in 4 ci jobs. In each job cy2 searches a file in the cypress cache folder and patches it with a function containing a URI pointing to a file in the node_modules of the project. Fine when you run one project in parallel but not when you have several ones with the same Cypress version.
I solved it by having different Cypress caches by project. I don't know if this can be solved with only one shared Cypress cache, maybe by having an identifier in the function ?

**Comment by agoldis** [comment]
@JeromeGS you can try using cy2@beta
