### ISSUE TITLE
docker-compose -f docker-compose.full.yml up fails

### ISSUE THREAD

**Issue by tuckerjt07** [sorry-cypress/sorry-cypress#722]
When running the ```docker-compose -f docker-compose.full.yml up``` command, five of the images start but minio/mc fails with the following error:

2023-01-16 13:43:56 /bin/sh: -c: line 0: syntax error near unexpected token \`<'
2023-01-16 13:43:56 /bin/sh: -c: line 0: \` sleep 3; /usr/bin/mc config host add myminio http://localhost:9000 <minio-user> <minio-pass>; /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress; /usr/bin/mc mb myminio/sorry-cypress; /usr/bin/mc anonymous set download myminio/sorry-cypress; /usr/bin/mc anonymous set public myminio/sorry-cypress; exit 0; '

**Comment by agoldis** [comment]
Not following the template

**Comment by Adrian-Sana** [comment]
> Not following the template

Can you please be more specific, I am having the same issue, the template is just downloaded from github.

**Comment by Adrian-Sana** [comment]
> When running the `docker-compose -f docker-compose.full.yml up` command, five of the images start but minio/mc fails with the following error:
> 
> 2023-01-16 13:43:56 /bin/sh: -c: line 0: syntax error near unexpected token `<' 2023-01-16 13:43:56 /bin/sh: -c: line 0: ` sleep 3; /usr/bin/mc config host add myminio http://localhost:9000 ; /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress; /usr/bin/mc mb myminio/sorry-cypress; /usr/bin/mc anonymous set download myminio/sorry-cypress; /usr/bin/mc anonymous set public myminio/sorry-cypress; exit 0; '

You have to follow this PR Template, this is what @agoldis meant: https://github.com/sorry-cypress/sorry-cypress/blob/master/.github/pull_request_template.md

**Comment by schirrel** [comment]
@Adrian-Sana @tuckerjt07 i am having the same problem, did you guys solved it?
