### ISSUE TITLE
DASHBOARD_URL of cypress run

### ISSUE THREAD

**Issue by vireshshah** [sorry-cypress/sorry-cypress#723]
Please note - issues that are not following the template will be closed automatically:

- [x] I have verified that all sorry-cypress services are running and accessible
- [x] I have read documentation and found no answer to my problem
- [x] I have searched issues / discussions and found to answer to my problem
- [x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Sorry cypress does returns DASHBOARD_URL as null, but should return correct run url

## How to reproduce

I am running cypress tests under docker in Jenkins. When I use `DASHBOARD_URL` to grab run url, it's always null. However I see it correctly when `npm cy2` runs. How can I access that variable correctly in Jenkins?

## Environment

- sorry-cypress version: `2.5.1`
- cypress version: `10.11.0`
- platform: `docker`
- service: `dashboard`

**Comment by agoldis** [comment]
The dashboard url is set in director configuration

**Comment by vireshshah** [comment]
Thanks @agoldis! Actually my question was how to grab cypress dashboard's current run url (e.g. https://amazingsorrycypress.com/run/**102e006c764396756e935eaa055280a8**) in Jenkins? I know there are hooks with github/slack but I want to send this unique url of each job with a notification, so team can click to navigate to specific run in sorry cypress dashboard.
