### ISSUE TITLE
Link of Bitbucket commit is incorrect (/commit vs /commits)

### ISSUE THREAD

**Issue by zadoli** [sorry-cypress/sorry-cypress#724]
## Summary

On the page of a run, the link at commit message for Bitbucket is broken, it has /commit instead of /commits in the URL.

## Environment

- sorry-cypress version: `2.5.1`
- cypress version: `10.9.0`
- platform: `docker`
- service: `dashboardl`

**Comment by agoldis** [comment]
PRs are welcome, should be an easy change

**Comment by mathpaquette** [comment]
I'll have a look
