### ISSUE TITLE
Aws template incorrect with recent changes

### ISSUE THREAD

**Issue by RobbeCl** [sorry-cypress/sorry-cypress#726]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.1`
  - cypress version: `does not matter`
  - cy2 version: `does not matter`
  - platform: `aws cloudformation`
  - service: `api`

```

</details>

### Describe the bug

Recently, the fallback path was changed: https://github.com/sorry-cypress/sorry-cypress/commit/c9e8b6e3da322f5be7ea182a0a29dfdd0b658401. But this leads to the api not being accessible because the graphql server it is no longer listening on / but now on /graphql. 

### Expected behavior

It works :-)

### Reproduction steps

Deploy the aws stack cia cloudformation 

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by C2L2C** [comment]
I was just about to create this issue! +1

**Comment by C2L2C** [comment]
Another probable issue is, the api container health check response is set to 400 whereas the observed status which results in healthy target groups is 404.

**Comment by agoldis** [comment]
@amit-o ?

**Comment by amit-o** [comment]
> @amit-o ?

sorry about that, I believe the issue is the change to the middleware which is mounted on /
I can open a PR soon for that

**Comment by RobbeCl** [comment]
Yeah, i think changing to load balancer rules will do the trick
