### ISSUE TITLE
spec files stuck in the beginning of the testing

### ISSUE THREAD

**Issue by ahmedAtAptus** [sorry-cypress/sorry-cypress#731]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.1`
  - cypress version: `11.2.0`
  - cy2 version: `4.0.1`
  - platform: `docker`
 - chrome version: `106`
 - electron version: `106`
```

</details>

### Describe the bug

I use 3 gitlab runners to run 13 spec test files in parallel, usually 1 or 2 of the runners stuck in the first spec file. they don't run the tests or show any output, and they stay like that until the job timeout while on the dashboard the test is still running or the job passes successfully but it skips all the tests in the spec file while the test is labelled failed on the dashboard

![Screenshot 2023-01-30 at 16 00 34](https://user-images.githubusercontent.com/88034997/215513241-1a110809-3941-4f09-adbc-3ba79df1bb44.png)

<img width="1728" alt="Screenshot 2023-01-30 at 16 03 31" src="https://user-images.githubusercontent.com/88034997/215513709-90f277a3-88fc-4c41-b77f-6b9d1e0d37b1.png">

<img width="1728" alt="Screenshot 2023-01-30 at 16 11 18" src="https://user-images.githubusercontent.com/88034997/215516012-a7b45680-d09f-4ae4-86ad-515e1cf96d39.png">

### Expected behavior

the tests shouldn't stuck and should be label with the right labels on the dashboard

### Reproduction steps

run the e2e tests on 3 gitlab runners in parallel

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
Issue is not follow the template
