### ISSUE TITLE
Multi Architecture Docker Images

### ISSUE THREAD

**Issue by blakeromano** [sorry-cypress/sorry-cypress#734]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

I want to be able to run sorry-cypress on ARM instances and currently only AMD is supported.

## Why is it needed? What is the value? For whom do we build it?

ARM is more performant when running Sorry Cypress on AWS and is cheaper.

## High-level feature overview

Build Docker Images with `docker buildx` with both AMD/ARM types.

**Comment by agoldis** [comment]
Hey @blakeromano, it is still failing https://github.com/sorry-cypress/sorry-cypress/actions/runs/4146429406
:(
