### ISSUE TITLE
Test results are getting upload to "null" project

### ISSUE THREAD

**Issue by USB-05** [sorry-cypress/sorry-cypress#751]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.1`
  - cypress version: `10.8.0`
  - cy2 version: `4.0.6`
  - platform: `k8s`
  - service: `all`

```

</details>

### Describe the bug

After cypress complete running all tests, tests results are not getting uploaded in the mentioned project, rather it is creating a project "null" and uploading test results under that

### Expected behavior

Expected behaviour is that test results should get uploaded under project mentioned in the cypress.config.ts file.

### Reproduction steps

1. Deploy Sorry Cypress Helm Chart version (sorry-cypress-1.9.0) with Minio and Mongo enabled. 
2. Configure API's and Director's BASE_PATH as "/".
3. Create separate LB for all services including minio.
4. Run Command: 
```
npx cy2 run --browser chrome --record --key harness-core-ui --parallel --group chrome --ci-build-id 58 --spec 'integration/70-pipeline/**/*'
```
5. Following is my cypress.config.ts
```
import { defineConfig } from 'cypress'

export default defineConfig({
  e2e: {
    baseUrl: 'https://localhost:8181/',
    specPattern: 'integration/**/*.spec.{ts,tsx}',
    supportFile: 'support/index.ts',
    fixturesFolder: 'fixtures',
    videoUploadOnPasses: false
  },
  projectId: 'harness-core-ui',
  viewportWidth: 1500,
  viewportHeight: 1000,
  retries: {
    runMode: 2,
    openMode: 0
  },
  fixturesFolder: 'fixtures',
  env: {
    // since urls need addHashInCypressURLBasedOnBrowserRouter function to create urls with hash and
    // without hash and inorder to decide if the browserRouterEnabeld  is true or not in app's window object,
    //Cypress does not have access to the app intially so injecting the browserRouterEnabled flag inside cypress env
    browserRouterEnabled: true
  }
})
```

Check in the dashboard that test results will get uploaded under "null" project and not under mentioned "harness-core-ui" project.

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
@USB-05 please provide the debug logs

**Comment by USB-05** [comment]
[cypress.log](https://github.com/sorry-cypress/sorry-cypress/files/10823381/cypress.log)
@agoldis Please find the attached debug logs.

**Comment by USB-05** [comment]
@mathpaquette @agoldis This is solved by defining below variable in the script where cypress run happens
```
export CYPRESS_PROJECT_ID="PROEJCT-ID-IN-SORRY-CYPRESS"
```
