### ISSUE TITLE
broken screenshots in the dashboard with minio storage

### ISSUE THREAD

**Issue by arnoldas-spotos** [sorry-cypress/sorry-cypress#755]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.2`
  - cypress version: `12.7.0`
  - cy2 version: `4.0.6`
  - platform: `k8s`
  - service: `dashboard`

```

</details>

### Describe the bug

We use an external minio server as the storage backend for screenshots, in the cypress run logs, we can see that screenshots are being uploaded successfully, we can also see the same screenshots just fine in the minio bucket, however, when checking the dashboard, there is a broken icon instead of a screenshot:

The same issue persists if we use the same minio version that is supplied with the helm chart.

![Screenshot 2023-03-09 at 09 23 06 AM](https://user-images.githubusercontent.com/120571449/223949793-57bf974b-2a77-45ef-acd6-469afd183b70.png)

![Screenshot 2023-03-09 at 09 27 18 AM](https://user-images.githubusercontent.com/120571449/223950666-bdd62f42-f051-4cce-94e0-ddea53a69a95.png)

When fetching the image from the minio bucket directly we can see a "correct" content type:
```
HTTP/2 200
accept-ranges: bytes
content-length: 1310
content-type: image/png
last-modified: Thu, 09 Mar 2023 07:26:28 GMT
server: MinIO Console
```

However, the content type of the object in the bucket is different, not sure if there is any relevance to the issue.
```
Content-Type
binary/octet-stream
```

### Expected behavior

Screenshots to be visible in the dashboard. 

### Reproduction steps

Use minio as the storage backend for screenshots. 

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
sorry guys, I am totally busy with cypress-cloud release please try investigate yourself

**Comment by TitasGurskis** [comment]
Copy/pasting from Slack's help channel:

So we have finally made it work!
It was a hell to debug, yet such a simple solution.

MINIO_URL has to lead to a public URL, not a private one (as stated in sorry-cypress documentation, our mistake for overlooking that!).

MINIO_READ_URL_PREFIX had to include bucket name, not only storage URL (again, stated in the documentation).

So just adjust the access settings of the minio bucket, put the dashboard under company's VPN + implement an oauth proxy for extra security and it should work just fine.
