### ISSUE TITLE
Failed to uploading the screenshot and videos to Cypress dashboard

### ISSUE THREAD

**Issue by govindd06** [sorry-cypress/sorry-cypress#757]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `<here>`
  - cypress version:  10.3.1
  - cy2 version: `<here>`
  - platform: docker
  - service: dashboard

```

</details>

### Describe the bug

Failed to uploading the screenshot and videos to Cypress dashboard, is there any configuration need to follow to upload the images and videos

### Expected behavior

It has to upload the images and videos after successful/failure test executions

### Reproduction steps

Run the below command
CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --parallel --record true --key somekey --ci-build-id build7 

### Full log and debug output

<details>

```
// Put your logs below this line

CYPRESS_API_URL="http://localhost:1234/" npx cy2 run --parallel --record true --key somekey --ci-build-id build7


```

</details>

**Comment by agoldis** [comment]
Bumped the release to 2.5.3
