### ISSUE TITLE
nginx: [emerg] host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8

### ISSUE THREAD

**Issue by renling-nd** [sorry-cypress/sorry-cypress#760]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `image: latest`
  - cypress version: `7.5.0`
  - cy2 version: `1.3.0`
  - platform: `k8s | docker `
  - service: `dashboard`

```

</details>

### Describe the bug

docker pull agoldis/sorry-cypress-dashboard:latest image file to local and docker run it, there has error "nginx: [emerg] host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8"

How to solve this problem? 

Thanks

### Expected behavior

dashboard normal work

### Reproduction steps

1.docker pull agoldis/sorry-cypress-dashboard:latest
2.docker run agoldis/sorry-cypress-dashboard:latest

### Full log and debug output

<details>

```
// Put your logs below this line

[root@localhost ~]# docker run agoldis/sorry-cypress-dashboard:latest
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/22 03:05:42 [emerg] 1#1: host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8
nginx: [emerg] host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8

```

</details>

**Comment by agoldis** [comment]
You need to provide `PORT` env variable e.g.: https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.full.yml#L44

**Comment by renling-nd** [comment]
sure, I provid the PORT env variable from yaml file, but it still not working
'''
containers:
              - name: {{ requiredEnv "RELEASE_NAME" | lower }}-dashboard
                image: agoldis/sorry-cypress-dashboard:latest
                imagePullPolicy: Always
                env:
                  - name: PORT
                    value: {{ requiredEnv "DIRECTOR_DASHBOARD_PORT" }}
                ports:
                  - containerPort: {{ requiredEnv "DIRECTOR_DASHBOARD_PORT" }}
'''

this is logs when I deploy from k8s
'''
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/22 02:32:30 [emerg] 1#1: host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8
nginx: [emerg] host not found in "${PORT}" of the "listen" directive in /etc/nginx/conf.d/default.conf:8
'''
