### ISSUE TITLE
Getting batched orchestration

### ISSUE THREAD

**Issue by DamienCassou** [sorry-cypress/sorry-cypress#766]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

We are switching to cypress-cloud because we have problems with recent version of Cypress and cy2. Unfortunately, with a lot of component tests and test files, the CI is now very very slow.

It would be good to get [batched orchestration](https://currents.dev/readme/integration-with-cypress/cypress-cloud#batched-orchestration) into sorry-cypress

**Comment by DamienCassou** [comment]
This is still very important for us

**Comment by DamienCassou** [comment]
@agoldis This is still very important to us. If you don't plan on doing this anytime soon, feel free to close the PR.

**Comment by agoldis** [comment]
@DamienCassou Do you have any free resource to allocate for developing this feature? I can provide guidance

**Comment by DamienCassou** [comment]
I have asked management to give me some time to work on this.

**Comment by DamienCassou** [comment]
I won't be able to work on this issue in the foreseeable future. Feel free to close the issue.

**Comment by DamienCassou** [comment]
I would like this issue to be reopened as I have started working on a fix.

**Comment by Rikkun-1** [comment]
Is there any progress on that issue?
