### ISSUE TITLE
it still counting execution time when run timed out

### ISSUE THREAD

**Issue by renling-nd** [sorry-cypress/sorry-cypress#771]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.3`
  - cypress version: `9.7.0`
  - cy2 version: `1.3.0`
  - platform: `k8s`
  - service: `dashboard`

```

</details>

### Describe the bug

hi, I set project time out to 2H, when run case CI machine blocker and director servcie can not receive any information from CI machine, then the duration time will continue to run after the timeout
![2023 04 14_高仁玲 1de71bcbb442759d72c39f774ec24b77](https://user-images.githubusercontent.com/87467252/231935479-f150b22e-f850-433d-b24e-286648c56b98.png)
![2023 04 14_高仁玲 5235cff4ddb39ad2b7c0dbdc5fd2ba93](https://user-images.githubusercontent.com/87467252/231935516-241e8059-8fdb-4385-bb60-5823c0c59bfd.png)

I hope set spec duration max time to runs timeout, and stop to counting time, and status can set to "Untested"

Thanks!

### Expected behavior

set spec duration max time to runs timeout, and stop to counting time, and status can set to "Untested"

### Reproduction steps

none

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by DannyBunny** [comment]
Same thing. Some test files never stop "running" in the dashboard, despite being finished for hours.

![Image](https://github.com/user-attachments/assets/13ad4024-d1fe-4277-a2d4-1d1faba5e51c)
@agoldis
