### ISSUE TITLE
Azure blob storage with cypress-cloud not working

### ISSUE THREAD

**Issue by jsnet-ops** [sorry-cypress/sorry-cypress#780]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.1`
  - cypress version: `12.11.0`
  - cy2 version: `cypress-cloud 1.7.4`
  - platform: `k8s`
  - service: `director`

```

</details>

### Describe the bug

Using cypress-cloud combined with screenshotsDriver: "../screenshots/azure-blob-storage.driver" results in not uploading files to  Azure blobstorage.

**Following prerequisites are met:**
1. Create a connectionstring secret in aks: connexionstring="DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=xxx;EndpointSuffix=core.windows.net
2. blob container created in azure storage
3. correct container name provided in director config
4. director starts normally

**Issue**
When the tests run, the video is created locally, while they should (also) be uploaded to Azure blob storage
The video does not appear in azure blob storage container. The videoplayer appears in dashboard, but obviously can't play the video as the request results in "404 The specified blob does not exist."

**Direcor log**
When running npx cypress-cloud, director logging shows following:
{"level":30,"time":1683877010613,"requestId":"76214ea2-2f50-440e-8e21-35bb3e8ca9f1","instanceId":"798ef708-1563-4e01-934d-36217586072b","screenshotUploadUrls":[],"videoUploadInstructions":{"uploadUrl":"https://xxx.blob.core.windows.net/sorry-cypress/798ef708-1563-4e01-934d-36217586072b.mp4?sv=2021-06-08&st=2023-05-12T07%3A36%3A50Z&se=2023-05-13T07%3A36%3A50Z&sr=b&sp=w&sig=kdn8wQ4DiiKi%2FPG2wxGxlWRBY4febfba5%2FWPAhj4CDk%3D&rsct=video%2Fmp4","readUrl":"https://xxx.blob.core.windows.net/sorry-cypress/798ef708-1563-4e01-934d-36217586072b.mp4?sv=2021-06-08&st=2023-05-12T07%3A36%3A50Z&se=2024-05-11T07%3A36%3A50Z&sr=b&sp=r&sig=w6FRhExAvMWcCM3FyzDcIqqrbdTEgBBS8S6kY5wc7O4%3D&rsct=video%2Fmp4"},"msg":"Sending assets upload URLs"}
{"level":30,"time":1683877010614,"req":{"id":1180,"method":"POST","url":"/instances/798ef708-1563-4e01-934d-36217586072b/results","query":{},"params":{},"headers":{"host":"cypress-director.mydomain.com","x-request-id":"a598cb8fe0504568cfacdb64c6d7f5d6","x-real-ip":"192.168.5.193","x-forwarded-for":"192.168.5.193","x-forwarded-host":"cypress-director.mydomain.com","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"6057","accept":"application/json, text/plain, */*","content-type":"application/json","x-cypress-request-attempt":"0","x-cypress-version":"12.11.0","x-ccy-version":"1.7.4","x-cypress-run-id":"656c0792cdfbc070a2eac21fc7283483","user-agent":"axios/1.4.0","accept-encoding":"gzip, compress, deflate, br"},"remoteAddress":"::ffff:10.1.156.209","remotePort":51736},"res":{"statusCode":200,"headers":{"content-type":"application/json; charset=utf-8","content-length":"302","etag":"W/\"12e-glWV1ixF+o44DEUUiJQVPoz2fjc\""}},"responseTime":9,"msg":"request completed"}

Questions:
1. Is Director responsible for uploading video / screenshots, or should this be done by the cypress agent?
2. Should Minio be used with this configuration, or is azure blob storage just sufficient?

### Expected behavior

The video should appear in Azure blob storage

### Reproduction steps

Run SC director, API and Dashboard with azure storage driver for screenshots
run cypress-cloud with --record option, providing the correct settings in currents.config.js:
module.exports = {
    projectId: 'id',
    recordKey: 'nokey',
    cloudServiceUrl: 'https://cypress-director.mydomain.com',
};

and cypress.config.js
export default defineConfig({
     video: true,
    videoUploadOnPasses: true,
    screenshotOnRunFailure: true,
});

See the video not being uploaded

### Full log and debug output

<details>

```
// Put your logs below this line
Log needed?

```

</details>

**Comment by agoldis** [comment]
@jsnet-ops

re: Is Director responsible for uploading video / screenshots, or should this be done by the cypress agent?
cypress-cloud is responsible for uploading videos and screenshots 

re: Should Minio be used with this configuration, or is azure blob storage just sufficient?

**Comment by jsnet-ops** [comment]
Hi!

Thanks for your reply. What should be tweaked on cypress cloud? What extra arguments could be used?

Regards.

**Comment by agoldis** [comment]
Probably this header should be added: https://github.com/sorry-cypress/cy2-azure/commit/7258aab7968af124e7fe673c5b64d3ce6b8af4c4#diff-b1bed53d3e4d671ff8c7f1e058becf7d6e16b4f3b4c55eacbd9e0dcecc8c5b20R48

Here's the relevant code in cypress-cloud: https://github.com/currents-dev/cypress-cloud/blob/main/packages/cypress-cloud/lib/upload.ts#L16

**Comment by LeMamin** [comment]
Fixed in the last cypress-cloud release : [https://github.com/currents-dev/cypress-cloud/issues/139](https://github.com/currents-dev/cypress-cloud/issues/139)
