### ISSUE TITLE
Dashboard is not working getting error of "Error: Unexpected token '<', "<html> <h"... is not valid JSON"

### ISSUE THREAD

**Issue by amitkpal83** [sorry-cypress/sorry-cypress#785]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: 2.5.4
  - cypress version: 8.5.0
  - cy2 version: 4.0.6
  - platform: `k8s`
  - service: `dashboard`

```

</details>

### Describe the bug

Dashboard is giving the error. Project list not loading. Please see the screenshot below
![image](https://github.com/sorry-cypress/sorry-cypress/assets/6175985/20007589-5bc5-414c-add8-04042e2f9394)

### Expected behavior

Dashboard should work fine.

### Reproduction steps

Installed the sorry cypress through helm chart in kubernetes. Once installed all other service are working fine only dashboard loading is problem. Update the url in director config also but still getting the same error. rest yaml file is same what we have got from repo.

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
most chances the API is not reachable, please examine the network logs in developer tools
