### ISSUE TITLE
How to Resolve this issue DevTools listening on ws:

### ISSUE THREAD

**Issue by prabakaran-yorosis** [sorry-cypress/sorry-cypress#790]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `<here>`
  - cypress version: `<here>`
  - cy2 version: `<here>`
  - platform: `k8s | docker | cloud provider`
  - service: `api | director | dashboard | all`

```

</details>

### Describe the bug

I am facing following issue, starting of every test cases.

DevTools listening on ws://127.0.0.1:44837

### Expected behavior

How to avoid this & want to know what is the root cause for it

### Reproduction steps

a

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
This is cypress issue, not ours
