### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'wallClockStartedAt')

### ISSUE THREAD

**Issue by Capocaccia** [sorry-cypress/sorry-cypress#791]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

The Sorry-Cypress dashboard errors when trying to retrieve a test run that has no attempts. I have provided a sample data structure below. This can occur when the Chromium Renderer process crashes therefore the test never attempts to execute. Initial investigation makes me think that the problem lies in `utils.ts` line 13 where the getTestStartedAt function is trying to read the wallClockStartedAt property off of the attempts array (`attempts[0].wallClockStartedAt`). As you can see in the data structure below, the attempts array is empty.

```
  - sorry-cypress version: `2.5.1`
  - cypress version: `10.11.0`
  - cy2 version: `3.1.3`
  - platform: `k8s | docker | cloud provider`
  - service: `director`
```

`[
  {
    _id: ObjectId("64886d4770e4d000128dd155"),
    spec: 'src/e2e/locations.cy.ts',
    runId: '7bc2f2a81d6d7ead8ff80b111fd7ceb4',
    projectId: 'e2e',
    instanceId: '4a2e1666-efcc-403f-8852-4fb789976f17',
    cypressVersion: '10.11.0',
    groupId: '127871',
    _createTestsPayload: {
      config: {
        chromeWebSecurity: false,
        blockHosts: [],
        retries: { runMode: 2, openMode: 0 },
        pageLoadTimeout: 30000,
        requestTimeout: 10000,
        responseTimeout: 25000,
        defaultCommandTimeout: 90000,
        numTestsKeptInMemory: 0,
        watchForFileChanges: false,
        projectId: 'e2e',
        viewportHeight: 900,
        viewportWidth: 1440,
        videosFolder: '/builds/abc/def/dist/cypress/libs/cypress/src/videos',
        screenshotsFolder: '/builds/abc/def/dist/cypress/libs/cypress/src/screenshots',
        video: false,
        fileServerFolder: '/builds/abc/def/secretRepoName/apps/e2e',
        supportFile: '/builds/abc/def/secretRepoName/apps/e2e/src/support/e2e.ts',
        specPattern: 'src/e2e/**/*.cy.{js,jsx,ts,tsx}',
        fixturesFolder: '/builds/abc/def/secretRepoName/apps/e2e/src/fixtures',
        userAgent: '',
        experimentalSessionAndOrigin: true,
        baseUrl: 'https://www.stg.redacted.com/',
        projectRoot: '/builds/abc/def/secretRepoName/apps/e2e',
        projectName: 'e2e',
        repoRoot: '/builds/abc/def/secretRepoName',
        rawJson: {
          chromeWebSecurity: false,
          blockHosts: [],
          retries: { runMode: 2 },
          pageLoadTimeout: 30000,
          requestTimeout: 10000,
          responseTimeout: 25000,
          defaultCommandTimeout: 90000,
          numTestsKeptInMemory: 0,
          watchForFileChanges: true,
          e2e: {
            videosFolder: '../../../dist/cypress/libs/cypress/src/videos',
            screenshotsFolder: '../../../dist/cypress/libs/cypress/src/screenshots',
            video: false,
            chromeWebSecurity: false,
            fileServerFolder: '.',
            supportFile: 'src/support/e2e.ts',
            specPattern: 'src/e2e/**/*.cy.{js,jsx,ts,tsx}',
            fixturesFolder: 'src/fixtures',
            userAgent: '',
            experimentalSessionAndOrigin: true
          },
          projectId: 'e2e',
          viewportHeight: 900,
          viewportWidth: 1440,
          videosFolder: '../../../dist/cypress/libs/cypress/src/videos',
          screenshotsFolder: '../../../dist/cypress/libs/cypress/src/screenshots',
          video: false,
          fileServerFolder: '.',
          supportFile: 'src/support/e2e.ts',
          specPattern: 'src/e2e/**/*.cy.{js,jsx,ts,tsx}',
          fixturesFolder: 'src/fixtures',
          userAgent: '',
          experimentalSessionAndOrigin: true,
          baseUrl: 'https://www.stg.redacted.com/',
          envFile: {},
          projectRoot: '/builds/abc/def/secretRepoName/apps/e2e',
          projectName: 'e2e',
          repoRoot: '/builds/abc/def/secretRepoName'
        },
        configFile: 'cypress.config.ts',
        morgan: false,
        isTextTerminal: true,
        socketId: '0byvzduwwk',
        report: true,
        animationDistanceThreshold: 5,
        arch: 'x64',
        clientCertificates: [],
        downloadsFolder: '/builds/abc/def/secretRepoName/apps/e2e/cypress/downloads',
        env: {
          CACHE_FOLDER: '/root/.cache/Cypress',
          INSTALL_BINARY: 0,
          API_URL: 'https://sorry-cypress-director.redacted.com'
        },
        execTimeout: 60000,
        experimentalFetchPolyfill: false,
        experimentalInteractiveRunEvents: false,
        experimentalModifyObstructiveThirdPartyCode: false,
        experimentalSourceRewriting: false,
        experimentalSingleTabRunMode: false,
        experimentalStudio: false,
        experimentalWebKitSupport: false,
        excludeSpecPattern: '*.hot-update.js',
        includeShadowDom: false,
        keystrokeDelay: 0,
        modifyObstructiveCode: true,
        platform: 'linux',
        port: 38641,
        redirectionLimit: 20,
        reporter: 'spec',
        reporterOptions: null,
        resolvedNodePath: '/usr/local/bin/node',
        resolvedNodeVersion: '16.16.0',
        screenshotOnRunFailure: true,
        slowTestThreshold: 10000,
        scrollBehavior: 'top',
        supportFolder: '/builds/abc/def/secretRepoName/apps/e2e/src/support',
        taskTimeout: 60000,
        testIsolation: 'on',
        trashAssetsBeforeRuns: true,
        videoCompression: 32,
        videoUploadOnPasses: true,
        waitForAnimations: true,
        additionalIgnorePattern: [],
        autoOpen: false,
        browsers: [
          {
            name: 'chrome',
            family: 'chromium',
            channel: 'stable',
            displayName: 'Chrome',
            version: '105.0.5195.125',
            path: 'google-chrome',
            minSupportedVersion: 64,
            majorVersion: '105'
          },
          {
            name: 'firefox',
            family: 'firefox',
            channel: 'stable',
            displayName: 'Firefox',
            version: '104.0.2',
            path: 'firefox',
            minSupportedVersion: 86,
            majorVersion: '104'
          },
          {
            name: 'edge',
            family: 'chromium',
            channel: 'stable',
            displayName: 'Edge',
            version: '107.0.1375.0',
            path: 'edge',
            minSupportedVersion: 79,
            majorVersion: '107'
          },
          {
            name: 'electron',
            channel: 'stable',
            family: 'chromium',
            displayName: 'Electron',
            version: '106.0.5249.51',
            path: '',
            majorVersion: 106
          }
        ],
        clientRoute: '/__/',
        cypressBinaryRoot: '/root/.cache/Cypress/10.11.0/Cypress/resources/app',
        devServerPublicPathRoute: '/__cypress/src',
        hosts: null,
        isInteractive: true,
        namespace: '__cypress',
        reporterRoute: '/__cypress/reporter',
        socketIoCookie: '__socket',
        socketIoRoute: '/__socket',
        version: '10.11.0',
        xhrRoute: '/xhrs/',
        cypressEnv: 'production',
        resolved: {
          animationDistanceThreshold: { value: 5, from: 'default' },
          arch: { value: 'x64', from: 'default' },
          baseUrl: { value: 'https://www.stg.redacted.com/', from: 'config' },
          blockHosts: {
            value: [],
            from: 'config'
          },
          chromeWebSecurity: { value: false, from: 'config' },
          clientCertificates: { value: [], from: 'default' },
          defaultCommandTimeout: { value: 90000, from: 'config' },
          downloadsFolder: { value: 'cypress/downloads', from: 'default' },
          env: {
            CACHE_FOLDER: { value: '/root/.cache/Cypress', from: 'env' },
            INSTALL_BINARY: { value: 0, from: 'env' },
            API_URL: {
              value: 'https://sorry-cypress-director.redacted.com',
              from: 'env'
            }
          },
          execTimeout: { value: 60000, from: 'default' },
          experimentalFetchPolyfill: { value: false, from: 'default' },
          experimentalInteractiveRunEvents: { value: false, from: 'default' },
          experimentalSessionAndOrigin: { value: true, from: 'config' },
          experimentalModifyObstructiveThirdPartyCode: { value: false, from: 'default' },
          experimentalSourceRewriting: { value: false, from: 'default' },
          experimentalSingleTabRunMode: { value: false, from: 'default' },
          experimentalStudio: { value: false, from: 'default' },
          experimentalWebKitSupport: { value: false, from: 'default' },
          fileServerFolder: { value: '.', from: 'config' },
          fixturesFolder: { value: 'src/fixtures', from: 'config' },
          excludeSpecPattern: { value: '*.hot-update.js', from: 'default' },
          includeShadowDom: { value: false, from: 'default' },
          keystrokeDelay: { value: 0, from: 'default' },
          modifyObstructiveCode: { value: true, from: 'default' },
          nodeVersion: { from: 'default' },
          numTestsKeptInMemory: { value: 0, from: 'config' },
          platform: { value: 'linux', from: 'default' },
          pageLoadTimeout: { value: 30000, from: 'config' },
          port: { value: null, from: 'default' },
          projectId: { value: 'e2e', from: 'config' },
          redirectionLimit: { value: 20, from: 'default' },
          reporter: { value: 'spec', from: 'default' },
          reporterOptions: { value: null, from: 'default' },
          requestTimeout: { value: 10000, from: 'config' },
          resolvedNodePath: { value: null, from: 'default' },
          resolvedNodeVersion: { value: null, from: 'default' },
          responseTimeout: { value: 25000, from: 'config' },
          retries: { value: { runMode: 2, openMode: 0 }, from: 'config' },
          screenshotOnRunFailure: { value: true, from: 'default' },
          screenshotsFolder: {
            value: '../../../dist/cypress/libs/cypress/src/screenshots',
            from: 'config'
          },
          slowTestThreshold: { value: 10000, from: 'default' },
          scrollBehavior: { value: 'top', from: 'default' },
          supportFile: { value: 'src/support/e2e.ts', from: 'config' },
          supportFolder: { value: false, from: 'default' },
          taskTimeout: { value: 60000, from: 'default' },
          testIsolation: { value: 'on', from: 'default' },
          trashAssetsBeforeRuns: { value: true, from: 'default' },
          userAgent: { value: '', from: 'config' },
          video: { value: false, from: 'config' },
          videoCompression: { value: 32, from: 'default' },
          videosFolder: {
            value: '../../../dist/cypress/libs/cypress/src/videos',
            from: 'config'
          },
          videoUploadOnPasses: { value: true, from: 'default' },
          viewportHeight: { value: 900, from: 'config' },
          viewportWidth: { value: 1440, from: 'config' },
          waitForAnimations: { value: true, from: 'default' },
          watchForFileChanges: { value: false, from: 'config' },
          specPattern: { value: 'src/e2e/**/*.cy.{js,jsx,ts,tsx}', from: 'config' },
          browsers: {
            value: [ [Object], [Object], [Object], [Object] ],
            from: 'runtime'
          },
          hosts: { value: null, from: 'default' },
          isInteractive: { value: true, from: 'default' }
        },
        testingType: 'e2e',
        remote: {
          origin: 'https://www.stg.redacted.com',
          strategy: 'http',
          fileServer: null,
          domainName: 'redacted.com',
          props: {
            port: '443',
            protocol: 'https:',
            domain: 'redacted',
            tld: 'com'
          }
        },
        browser: null,
        specs: [],
        proxyUrl: 'http://localhost:38641',
        browserUrl: 'https://www.stg.redacted.com/__/',
        reporterUrl: 'https://www.stg.redacted.com/__cypress/reporter',
        xhrUrl: '__cypress/xhrs/',
        proxyServer: 'http://localhost:38641',
        state: {}
      },
      tests: [
        {
          clientId: 'r3',
          body: '() => {\n' +
            "        cy.intercept('**autocomplete**').as('autocomplete');\n" +
            "        cy.visit({ url: 'en/locations/' });\n" +
            '    }',
          title: [ 'Booking from locations page', 'ABC-5161' ],
          config: {},
          hookIds: [ 'h1', 'h2', 'r3', 'r3-studio' ]
        },
        {
          clientId: 'r5',
          body: '() => {\n' +
            '        [\n' +
            "            'all-inclusive',\n" +
            "            'beach',\n" +
            "            'boutique',\n" +
            "            'casino',\n" +
            "            'golf',\n" +
            "            'hotel-residences',\n" +
            "            'luxury',\n" +
            "            'pet-friendly',\n" +
            "            'resorts',\n" +
            "            'ski',\n" +
            '        ].forEach((feature) => {\n' +
            '            cy.visit({ url: `en/locations/${feature}/` });\n' +
            "            cy.findAllByTestId('hotel-card-content').should('have.length.at.least', 1);\n" +
            '        });\n' +
            '    }',
          title: [
            'Check location pages dependent on daily ETL or configuration',
            'ABC-5505'
          ],
          config: {},
          hookIds: [ 'h3', 'h1', 'h2', 'r5', 'r5-studio' ]
        }
      ],
      hooks: [
        {
          clientId: 'h2',
          type: 'before each',
          title: [ '"before each" hook' ],
          body: "() => {\n    cy.iFrameLogin('e2e');\n}"
        },
        {
          clientId: 'h3',
          type: 'before all',
          title: [ '"before all" hook' ],
          body: "() => {\n        Cypress.config('pageLoadTimeout', 120000);\n    }"
        }
      ]
    },
    results: {
      stats: {
        failures: 1,
        tests: 0,
        passes: 0,
        pending: 0,
        suites: 0,
        skipped: 0,
        wallClockDuration: 0,
        wallClockStartedAt: '2023-06-13T13:27:15.817Z',
        wallClockEndedAt: '2023-06-13T13:27:15.817Z'
      },
      tests: [
        {
          attempts: [],
          hooks: [],
          clientId: 'r3',
          body: '() => {\n' +
            "        cy.visit({ url: 'en/locations/' });\n" +
            '    }',
          title: [ 'Booking from locations page', 'ABC-5161' ],
          config: {},
          hookIds: [ 'h1', 'h2', 'r3', 'r3-studio' ],
          state: 'failed',
          testId: 'r3',
          displayError: 'We detected that the Chromium Renderer process just crashed.\n' +
            '\n' +
            "This is the equivalent to seeing the 'sad face' when Chrome dies.\n" +
            '\n' +
            'This can happen for a number of different reasons:\n' +
            '\n' +
            '- You wrote an endless loop and you must fix your own code\n' +
            '- You are running Docker (there is an easy fix for this: see link below)\n' +
            '- You are running lots of tests on a memory intense application\n' +
            '- You are running in a memory starved VM environment\n' +
            '- There are problems with your GPU / GPU drivers\n' +
            '- There are browser bugs in Chromium\n' +
            '\n' +
            'You can learn more including how to fix Docker here:\n' +
            '\n' +
            'https://on.cypress.io/renderer-process-crashed'
        },
        {
          attempts: [],
          hooks: [],
          clientId: 'r5',
          body: '() => {\n' +
            '        [\n' +
            "            'all-inclusive',\n" +
            "            'beach',\n" +
            "            'boutique',\n" +
            "            'casino',\n" +
            "            'golf',\n" +
            "            'hotel-residences',\n" +
            "            'luxury',\n" +
            "            'pet-friendly',\n" +
            "            'resorts',\n" +
            "            'ski',\n" +
            '        ].forEach((feature) => {\n' +
            '            cy.visit({ url: `en/locations/${feature}/` });\n' +
            "            cy.findAllByTestId('hotel-card-content').should('have.length.at.least', 1);\n" +
            '        });\n' +
            '    }',
          title: [
            'Check location pages dependent on daily ETL or configuration',
            'ABC-5505'
          ],
          config: {},
          hookIds: [ 'h3', 'h1', 'h2', 'r5', 'r5-studio' ],
          state: 'failed',
          testId: 'r5',
          displayError: 'We detected that the Chromium Renderer process just crashed.\n' +
            '\n' +
            "This is the equivalent to seeing the 'sad face' when Chrome dies.\n" +
            '\n' +
            'This can happen for a number of different reasons:\n' +
            '\n' +
            '- You wrote an endless loop and you must fix your own code\n' +
            '- You are running Docker (there is an easy fix for this: see link below)\n' +
            '- You are running lots of tests on a memory intense application\n' +
            '- You are running in a memory starved VM environment\n' +
            '- There are problems with your GPU / GPU drivers\n' +
            '- There are browser bugs in Chromium\n' +
            '\n' +
            'You can learn more including how to fix Docker here:\n' +
            '\n' +
            'https://on.cypress.io/renderer-process-crashed'
        }
      ],
      exception: 'We detected that the Chromium Renderer process just crashed.\n' +
        '\n' +
        "This is the equivalent to seeing the 'sad face' when Chrome dies.\n" +
        '\n' +
        'This can happen for a number of different reasons:\n' +
        '\n' +
        '- You wrote an endless loop and you must fix your own code\n' +
        '- You are running Docker (there is an easy fix for this: see link below)\n' +
        '- You are running lots of tests on a memory intense application\n' +
        '- You are running in a memory starved VM environment\n' +
        '- There are problems with your GPU / GPU drivers\n' +
        '- There are browser bugs in Chromium\n' +
        '\n' +
        'You can learn more including how to fix Docker here:\n' +
        '\n' +
        'https://on.cypress.io/renderer-process-crashed',
      video: false,
      screenshots: [],
      reporterStats: {
        suites: 1,
        tests: 2,
        passes: 0,
        pending: 0,
        failures: 2,
        start: '2023-06-13T13:27:16.075Z',
        end: '2023-06-13T13:27:16.075Z',
        duration: 0
      },
      metadata: { studioCreated: 0, studioExtended: 0 }
    }
  }
]`

### Describe the bug

The Sorry-Cypress dashboard errors when trying to retrieve a test run that has no attempts. I have provided a sample data structure below. This can occur when the Chromium Renderer process crashes therefore the test never attempts to execute. Initial investigation makes me think that the problem lies in `utils.ts` line 13 where the getTestStartedAt function is trying to read the wallClockStartedAt property off of the attempts array (`attempts[0].wallClockStartedAt`). As you can see in the data structure below, the attempts array is empty.

### Expected behavior

I expect the dashboard to continue to render even if there is no wallClockStartedAt property.  Ideally it would display the error returned by Cypress which is contained in the `displayError` property.

### Reproduction steps

This will be a bit tricky but you would have to use the data structure provided to seed a database and then attempt to load that attempt in the dashboard UI.

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by estefafdez** [comment]
We had this problem before, the only solution we found is to delete the mongo-0 database from sorry cypress (usually this happens when there are a lot of tests run there) and start fresh. Then, it's working properly again. Hope it helps!

**Comment by Capocaccia** [comment]
Sure, deleting the bad data will remove the effect the problem has but it doesnt solve why the problem exists in the first place.

**Comment by Capocaccia** [comment]
@agoldis  - Here is the stack trace that the dashboard UI surfaces but im not sure it will be of much use to you.

`
TypeError: Cannot read properties of undefined (reading 'wallClockStartedAt')
    at https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:120:639979
    at Array.forEach (<anonymous>)
    at https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:120:639803
    at Array.forEach (<anonymous>)
    at https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:120:639770
    at Tj (https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:120:640399)
    at ii (https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:147:509576)
    at Wl (https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:147:561625)
    at Rs (https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:147:548899)
    at Ss (https://myDashboard.com/index.mjs?0c92f054ab1ba44e8606:147:548827)
`
