### ISSUE TITLE
"Cannot find absolute spec" error when running "npx cypress-cloud run --parallel --record --key 777 --ci-build-id hello-cypress"

### ISSUE THREAD

**Issue by YerayDP** [sorry-cypress/sorry-cypress#793]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^15.0.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "@shelex/cypress-allure-plugin": "^2.34.0",
    "cypress": "^12.14.0",
    "esbuild": "^0.17.0",
    "multiple-cucumber-html-reporter": "^3.0.1"
  },
  "dependencies": {
    "cypress-cloud": "^1.7.4",
    "cypress-parallel": "^0.13.0"
  }

```

</details>

### Describe the bug

After all is setup like in the basic guide, i get this error when i execute the command to run the tests:

Cypress.config.js:

![Captura de pantalla 2023-06-15 a las 13 37 33](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/a3edde0c-4179-40ff-9ee1-c64f1da8b89b)

Terminal:
Cannot find absolute path for spec. Spec: "undefined"
![Captura de pantalla 2023-06-15 a las 13 31 54](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/db23cc86-e459-4ba5-8138-ec9d6489882b)

And then if the spec is changed to the terminal throws another error:

Cypress.config.js:

![Captura de pantalla 2023-06-15 a las 13 37 20](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/1e496f4a-5657-4c3d-931b-f928d3007b97)

Terminal:
![Captura de pantalla 2023-06-15 a las 13 36 13](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/1af829dd-b3ea-45af-976f-c816805472f6)

### Expected behavior

Run the tests in a correct way, like is supposed to do i guess

### Reproduction steps

To Reproduce:

- Download [cypress-boilerplate](https://github.com/JoanEsquivel/cypress-cucumber-boilerplate)
- Follow the guide to setup sorry-cypress in https://docs.sorry-cypress.dev/guide/get-started and https://docs.sorry-cypress.dev/guide/dashboard-and-api
- run the command "docker-compose -f ./docker-compose.minio.yml up" and "npx cypress-cloud run --parallel --record --key 777 --ci-build-id hello-cypress" in terminal

### Full log and debug output

<details>

```
// Put your logs below this line


Discovered 2 spec files
Tags: false; Group: false; Parallel: true; Batch Size: 3
Connecting to cloud orchestration service...
🎥 Run URL: undefined

====================================================================================================

Running:  (NaN/NaN)
 WARNING  Cannot find absolute path for spec. Spec: "undefined", candidates: [
  {
    fileExtension: '.feature',
    baseName: 'login.feature',
    fileName: 'login',
    specFileExtension: '.feature',
    relativeToCommonRoot: 'login.feature',
    specType: 'integration',
    name: 'cypress/e2e/features/login.feature',
    relative: 'cypress/e2e/features/login.feature',
    absolute: '/Users/YerayDominguezPavon/Desktop/CyThreaded/cypress/e2e/features/login.feature'
  },
  {
    fileExtension: '.feature',
    baseName: 'tags.feature',
    fileName: 'tags',
    specFileExtension: '.feature',
    relativeToCommonRoot: 'tags.feature',
    specType: 'integration',
    name: 'cypress/e2e/features/tags.feature',
    relative: 'cypress/e2e/features/tags.feature',
    absolute: '/Users/YerayDominguezPavon/Desktop/CyThreaded/cypress/e2e/features/tags.feature'
  },
  [length]: 2
]
Error: Cannot find absolute path for spec
    at getSpecAbsolutePath (/Users/YerayDominguezPavon/Desktop/CyThreaded/node_modules/lib/runner/runner.ts:179:11)
    at /Users/YerayDominguezPavon/Desktop/CyThreaded/node_modules/lib/runner/runner.ts:130:22
    at Array.map (<anonymous>)
    at runBatch (/Users/YerayDominguezPavon/Desktop/CyThreaded/node_modules/lib/runner/runner.ts:130:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runTillDone (/Users/YerayDominguezPavon/Desktop/CyThreaded/node_modules/lib/runner/runner.ts:46:22)


--2 (case if I put ../cypress/e2e/features/*.feature in specPattern)

 WARNING  Found no spec files. Was looking for spec files that match both configSpecPattern and specPattern relative to projectRoot. Configuration: {
  projectRoot: '/Users/YerayDominguezPavon/Desktop/CyThreaded',
  specPattern: '../cypress/e2e/features/*.feature',
  configSpecPattern: '../cypress/e2e/features/*.feature',
  excludeSpecPattern: [ '*.hot-update.js' ],
  testingType: 'e2e'
}

</details>

**Comment by agoldis** [comment]
@YerayDP please submit the full log with DEBUG enabled

**Comment by YerayDP** [comment]
![Captura de pantalla 2023-06-15 a las 20 09 40](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/7ce358ae-5a8a-4b9c-9963-3c33457daf9e)

**Comment by agoldis** [comment]
@YerayDP `DEBUG=currents*,cypress*`

**Comment by YerayDP** [comment]
![Captura de pantalla 2023-06-15 a las 20 30 21](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/4fe1f92f-7af9-44e7-9f73-c7e012e47ff7)
![Captura de pantalla 2023-06-15 a las 20 30 39](https://github.com/sorry-cypress/sorry-cypress/assets/73529878/ec3fed73-5167-4506-8327-466eeb3f27be)

**Comment by agoldis** [comment]
@YerayDP
Your configuration is wrong  - the cloudServiceURL should point to director service URL, you've configured minio instead
