### ISSUE TITLE
X-Amz-Expires=NaN

### ISSUE THREAD

**Issue by steepdevs** [sorry-cypress/sorry-cypress#797]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: latest
  - cypress version: latest
  - platform: `docker compose`
  - service: `director `

```

</details>

### Describe the bug

Cypress cannot upload artifacts to minio, no errors in logs, 15 June it worked with tags latest, but 16 June, when I deployed it to another environment it already broken
reason: director is generating uploadUrl with X-Amz-Expires=NaN

when I called upload with curl inside container, I saw reason:
`
curl "http://storage:9000/sorry-cypress/e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXX%2F20230620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230620T082334Z&X-Amz-Expires=NaN&X-Amz-SignedHeaders=host&X-Amz-Signature=EXAMPLE"
`

`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationQueryParametersError</Code><Message>X-Amz-Expires should be a number</Message><Key>e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4</Key><BucketName>sorry-cypress</BucketName><Resource>/sorry-cypress/e68efbf1-5a74-44f0-ba60-55403c01da2d.mp4</Resource><RequestId>176A5B419C3D6F47</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
`

fix: I change director's image tag to agoldis/sorry-cypress-director:2.5.4
and it started work

### Expected behavior

artifacts uploaded to minio

### Reproduction steps

1. clone sorry-cypress
2. start environment with minio

### Full log and debug output

<details>

```
director  | {"level":30,"time":1687251773346,"requestId":"c65d54fa-d6e1-4764-8cd9-9c8532592807","instanceId":"e71eb671-865f-4b35-93ad-19f4aa56983d","runId":"ab21ad9e9d5d42969aae11afe9e42907","groupId":"Tue Jun 20 09:02:27 UTC 2023","msg":"Setting instance results"}
director  | {"level":30,"time":1687251773349,"requestId":"c65d54fa-d6e1-4764-8cd9-9c8532592807","instanceId":"e71eb671-865f-4b35-93ad-19f4aa56983d","screenshotUploadUrls":[],"videoUploadInstructions":{"readUrl":"https://storage/minio/sorry-cypress/e71eb671-865f-4b35-93ad-19f4aa56983d.mp4","uploadUrl":"http://storage:9000/sorry-cypress/e71eb671-865f-4b35-93ad-19f4aa56983d.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXX%2F20230620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230620T090253Z&X-Amz-Expires=NaN&X-Amz-SignedHeaders=host&X-Amz-Signature=XXX"},"msg":"Sending assets upload URLs"}
director  | {"level":30,"time":1687251773350,"req":{"id":11,"method":"POST","url":"/instances/e71eb671-865f-4b35-93ad-19f4aa56983d/results","query":{},"params":{},"headers":{"accept":"application/json, text/plain, */*","content-type":"application/json","x-cypress-request-attempt":"0","x-cypress-version":"12.14.0","x-ccy-version":"1.7.4","x-cypress-run-id":"ab21ad9e9d5d42969aae11afe9e42907","user-agent":"axios/1.4.0","content-length":"1595","accept-encoding":"gzip, compress, deflate, br","host":"director:1234","connection":"close"},"remoteAddress":"::ffff:172.27.0.3","remotePort":36248},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"413","etag":"W/\"19d-T8Vf4BjO5ytffFUYt6oulIFsPYQ\""}},"responseTime":6,"msg":"request completed"}
director  | {"level":30,"time":1687251773353,"requestId":"ad50bba6-6650-4a9f-b7e4-1856a7541685","instanceId":"e71eb671-865f-4b35-93ad-19f4aa56983d","msg":"[not implemented] Received stdout for instance"}

</details>

**Comment by qpuolet** [comment]
Same problem

**Comment by agoldis** [comment]
Should be fixed in the latest release
