### ISSUE TITLE
Not able to set the dashboard url as internal load balancer

### ISSUE THREAD

**Issue by amitkpal83** [sorry-cypress/sorry-cypress#798]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: 2.5.4
  - cypress version: 8.5.0
  - cy2 version: 4.0.6
  - platform: `k8s`
  - service: `dashboard`


```

</details>

### Describe the bug

Trying to set the dashboard service as internal loadbalancer: 

 service:
    annotations: {
    service.beta.kubernetes.io/azure-load-balancer-internal: "true",
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "xxxx"
    }
    type: LoadBalancer

But somehow this is not getting applied in annotations. Tried lot of things but still not able to figure out. Checked below documentation and saw annotation property is not mentioned in the service section.

https://artifacthub.io/packages/helm/sorry-cypress/sorry-cypress

Is i am missing something? 

### Expected behavior

Annotation should set properly in kubernetes.

### Reproduction steps

Just do apply after making above changes in the yaml file.

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
https://github.com/sorry-cypress/charts
