### ISSUE TITLE
[PLEASE HELP] Implement cypress wrapper

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#8]
Today it might be scary and inconvenient to change cypress configuration to use the dashboard. 
Having a wrapper that gets API endpoint URL as a CLI argument / configuration would simplify the use.

🚨 UPDATE:
Please upvote the ticket by @csvan: overriding core config vars here: cypress-io/cypress#7164

**Comment by agoldis** [comment]
Possible solution would be an ugly monkey-patching - replacing `konfig/index.js` with a patched version that replaces `api_url` with value of an environment variable

**Comment by danielvianna** [comment]
I need this feature!
How can I help?

**Comment by agoldis** [comment]
@danielvianna Sure! I see few options:

- open a request on the original cypress project to allow overwriting API server configuration

- create a standalone wrapper that would inject the configurations when `cypress` runs. One approach would be the monkey-patching that I have mentioned in the comment above, but it's a fragile solution. 

- explore other options that I am not aware of

**Comment by redaxmedia** [comment]
What about temporary changing the domain resolution? I did not test this but looks more elegant to me rather than finding and tricking config files in the userspace.

```
ServerName api.cypress.com
ServerAlias http://localhost:1234
```

**Comment by redaxmedia** [comment]
@agoldis We got the wrapper working in our company. Are you open for an PR with this approach?

**Comment by danielvianna** [comment]
I'm interested in the solution: danielribas1984@gmail.com if you care to share

**Comment by agoldis** [comment]
Sure more than welcome!

**Comment by redaxmedia** [comment]
@danielvianna Well, the solution is similar to the one non-working concept I posted here

@agoldis Fine, the student who is under my mentoring will send a PR at the beginning of the week.

**Comment by agoldis** [comment]
@redaxmedia `SORRY_CYPRESS_` sounds good. Can I borrow the student for other task?  😃

**Comment by csvan** [comment]
Opened a ticket for overriding core config vars here: https://github.com/cypress-io/cypress/issues/7164

**Comment by danielvianna** [comment]
I have this patch here.
It works on windows. I tested on CI/CD / Gitlab but I had some issues and still working on it:

```
# Step 1: get installed cypress version, store as variable

cypress_version=$($PWD/cypress-cast/node_modules/.bin/cypress --version ls -l | tail -1 | awk '{print $NF}')
echo cypress version is "$cypress_version"

# Step 2: get binary path, store as variable

cypress_cache_path=$(npx print-cachedir Cypress)
echo cypress cache patch is "$cypress_cache_path"

# Step 4: define config path ending

cypress_server_config_path_ending='Cypress\resources\app\packages\server\config\'
echo config path ending is "${cypress_server_config_path_ending}"

# Step 5: concatenate all parts of the path into one, then transform into variable

cypress_server_config_fullpath="$cypress_cache_path"'\'"${cypress_version}"'\'"${cypress_server_config_path_ending}"

echo full path is $cypress_server_config_fullpath

tput setaf 4; echo current app.yml content is
cat "$cypress_server_config_fullpath/app.yml"

# Step 6: Copy new app.yml config and Replace the old cypress's app.yml

cp -f "$PWD/app.yml" "$cypress_server_config_fullpath/app.yml"
tput setaf 2; echo modified app.yml content is
cat "$cypress_server_config_fullpath/app.yml"

:End
cmd /k
```

**Comment by agoldis** [comment]
@danielvianna thanks for sharing the script, I have added it to https://github.com/agoldis/sorry-cypress/wiki/Configuring-cypress-agents#overriding-cypress-config-file-with-a-script-windows-only

**Comment by redaxmedia** [comment]
@csvan Not sure if linking the issue to a project that will cut of their earnings is such a smart thing!?

**Comment by csvan** [comment]
@redaxmedia I don't see it cutting off their earnings. Cypress have a vested interest in making their product more popular, and open source alternatives to their own dashboard actually helps with that. Enterprise customers will always be likely to go for the commercial option, which is their offering.

**Comment by redaxmedia** [comment]
@csvan I'm 100% sure they have another opinion when it comes to their business.

**Comment by csvan** [comment]
@redaxmedia ok.

**Comment by danielvianna** [comment]
Maybe we should ask them how they feel. There should be a way to do a coordinated effort so their bigger clients are not taking advantage.
I am in debt with their help, not just the platform but free advice and training. What they have done basically saved a project. However, the company I work (almost the size of a startup) for was put on pause after COVID, so we really can't afford until entertainment business is back (everyone was furlough).

**Comment by agoldis** [comment]
I've reached to the leadership team of cypress, will try to establish relationship. Will keep you posted.

**Comment by MeStrak** [comment]
@agoldis  I just created suggestion #76 before finding this thread. It's basically a one line command which will edit the cypress config, without the need to touch the hosts file.

I agree that the suggested change to core Cypress is the best option to either provide this as a command line switch or env var. Meanwhile, I'm not really sure if editing the hosts file is really a nicer option that changing the config.

What do you think?

**Comment by agoldis** [comment]
@MeStrak thank for sharing the one liner, that's quite handy! I will add it to the project.

I would leave it to users to decide what better works for them, one option can work better for some ppl, but not for all :) 
Make sense?

**Comment by MeStrak** [comment]
Yep, makes total sense :)

**Comment by nickcox** [comment]
Here's an equivalent one-liner for PowerShell on Windows:

```powershell
ls $env:LOCALAPPDATA/Cypress/Cache -Recurse -Filter app.yml |
% { (Get-Content $_ -Raw) -replace "https://api.cypress.io/", "https://sorry-cypress-demo-director.herokuapp.com/" | Out-File $_ }
```

**Comment by agoldis** [comment]
@nickcox Updated the readme https://github.com/agoldis/sorry-cypress/blob/master/README.md#Using-one-liner. Thank you!

**Comment by agoldis** [comment]
**Update**

After an introduction / conversation with cypress leadership, it seems unlikely that they would accept contributions directly associated with `sorry-cypress`. 

That was a delicate topic to discuss. Cypress is trying to balance between commercial approach and supporting the community. Good news is that they are keen to improve their offerings / product to make the original cypress better / more affordable / flexible.

If you want to learn more please reach me directly online.

**Comment by ChristianIvicevic** [comment]
Btw for testing purposes I noticed that it's possible to set `CYPRESS_INTERNAL_ENV=development` on the command line that forces the server package to route automatically to `http://localhost:1234` without any hosts rules etc. as it is registered for development purposes:

https://github.com/cypress-io/cypress/blob/aa6470d349237234e551f83cb3abbac5bb0eda98/packages/server/config/app.yml#L8-9

This is abusing some internal variables and causing a warning to unset that variable, thus not reliable and prone to change.

**Comment by agoldis** [comment]
One idea I've been tossing around is to have some kind of automation that forks the original cypress on every release, applies some patch that allows overriding `api_url` by an env variable from CLI and builds / releases a new binary, i.e. `not-cypress` npm package that's complete clone of `cypress` but with this small extra feature

**Comment by agoldis** [comment]
Here we go: https://www.npmjs.com/package/cy2
