### ISSUE TITLE
Add on the project item, the number of tests run. And add the total of all tests running on the summary page.

### ISSUE THREAD

**Issue by samixchoumi** [sorry-cypress/sorry-cypress#804]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Allow to see easily on the projects list the total test of a project (without entering on the project) (like a summary)

## Why is it needed? What is the value? For whom do we build it?
It's good to have a summary of all the tests done directly from the project page instead of looking at each project to know how many tests are run. 
The value is that it's easier to have a summary to make some KPI. (and we can add the failing test of the last pipeline directly from the project list page).

EDIT : New value, we can know which project have failing test directly without checking manually each project.

## Other
Actually we have that : 
![image](https://github.com/sorry-cypress/sorry-cypress/assets/22171928/2ae84ff3-3e8c-4730-a7f4-fa2f3c2c6be8)
It should be nice to have something like that, using the last run : 
![image](https://github.com/sorry-cypress/sorry-cypress/assets/22171928/9f8711d4-0f33-4592-bf7f-f4f196fc708b)

Maybe add the total test number of all projects like that 
![image](https://github.com/sorry-cypress/sorry-cypress/assets/22171928/5a1abd39-861a-4721-b909-06e9fd60c54f)

**Comment by samixchoumi** [comment]
@agoldis any news about that feature request ?

**Comment by samixchoumi** [comment]
Hello @agoldis, I wanted to make a PR but I don't have access, can you do something or do you prefer I fork your project ?

**Comment by agoldis** [comment]
Yes, please fork and open a PR

**Comment by samixchoumi** [comment]
@agoldis Do you know when this feature could be merged ?

**Comment by agoldis** [comment]
It'd be available in 2.5.9 and latest
