### ISSUE TITLE
Make director/screenshots/s3 package compatible with other providers

### ISSUE THREAD

**Issue by p-8-z** [sorry-cypress/sorry-cypress#805]
- [x] I have searched issues for similar feature requests

## Why is it needed? What is the value? For whom do we build it?

Make director/screenshots/s3 package compatible with other providers.
Make non-public Buckets accessible even for downloading (pre-signed download urls). 

## High-level feature overview

- updated AWS library (fix AWS warnings)
- url signing for upload and download
- make director/screenshots/s3 package compatible with other providers (tested with Oracle OCI S3)

**Comment by p-8-z** [comment]
Implemented:
#806

**Comment by actuallymentor** [comment]
Is this a good place to chime in and ask for file storage on the director's server? Or is that beyond the scope of this issue?

**Comment by agoldis** [comment]
That's beyond I am afraid

**Comment by Rohmilchkaese** [comment]
Sorry, but that doesn't seem true according to: [sorry-cypress/packages/director/src/screenshots/s3/s3.ts](https://github.com/sorry-cypress/sorry-cypress/blob/87e8f814e1c48132ad8620f3338007d8fea1ffe0/packages/director/src/screenshots/s3/s3.ts#L17)

```
import { AssetUploadInstruction } from '@sorry-cypress/common';
import aws from 'aws-sdk';
import { sanitizeS3KeyPrefix } from '../utils/';
import {
  S3_ACL,
  S3_BUCKET,
  S3_FORCE_PATH_STYLE,
  S3_IMAGE_KEY_PREFIX,
  S3_READ_URL_PREFIX,
  S3_REGION,
  S3_VIDEO_KEY_PREFIX,
  UPLOAD_EXPIRY_SECONDS,
} from './config';
import { S3SignedUploadResult } from './types';

const BUCKET_URL = S3_FORCE_PATH_STYLE
  ? `https://s3.amazonaws.com/${S3_BUCKET}`
  : `https://${S3_BUCKET}.s3.amazonaws.com`;

```

I'm not a coder, but I dont see a possibility to set different URL from AWS here, am I right?

**Comment by Rohmilchkaese** [comment]
@agoldis Any Updates to https://github.com/sorry-cypress/sorry-cypress/pull/806 ?

**Comment by Rohmilchkaese** [comment]
Is there something we can do as company to push this? We love sorry cypress and would love to have the capability to push to an self hosted s3 for eg.

**Comment by agoldis** [comment]
@Rohmilchkaese you can use self-hosted s3 via minio driver:
https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration

**Comment by Rohmilchkaese** [comment]
@agoldis thanks mate! Didn't see that to be honest :)
