### ISSUE TITLE
Self-hosted docker-compose docs (request/offer for help)

### ISSUE THREAD

**Issue by actuallymentor** [sorry-cypress/sorry-cypress#825]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Running the `sorry-cypress` stack on a VPS using `docker-compose`.

## Why is it needed? What is the value? For whom do we build it?
Make running `sorry-cypress` more turnkey for casual Github Actions users that do not want to set up more complex cloud services.

## Other

I made a [sorry cypress provisioning script](https://github.com/actuallymentor/sorry-cypress-server-provisioning/) and am happy to write up some docs if you'd like.

**Comment by agoldis** [comment]
@actuallymentor that's a great idea! It would help to add an example at https://github.com/sorry-cypress/gitbook - I will publish it on twitter / Slack to promote

**Comment by actuallymentor** [comment]
Awesome. I'll add it to my todo list. Eta 1 day - 2 weeks.

**Comment by actuallymentor** [comment]
Hey @agoldis!

I'm running into the issue that putting the API behind a basic-auth makes it throw errors (it specifically says "api cannot be accessed with an authenticated url".

I have two questions:

1. Is it possible to change the API to support basic auth?
2. Alternatively, is there any other sort of authentication? The dashboard is behind basic-auth, so embedding an API key in the frontend would not even be that much of a security hazard.

The reason for the auth is that I do not think it is wise to leave anything public to the world without authentication.

**Comment by agoldis** [comment]
@actuallymentor it is possible to implement auth, there were successful implementations of protecting the deployment on the network level or by using a reverse proxy. Check out the issues' history. 

I am not sure what is implementation you're referring to, but I guess if you put any kind of restriction that requires an authentication, you need to support providing the credentials to the corresponding client requests.

**Comment by actuallymentor** [comment]
The implementation is at the above link, which is a reverse proxy.

The dashboard however connects to the sorry-Cypress API from it's webpage. Meaning container-to-container traffic is not sufficient.

The dashboard is already in a reverse proxied authenticated setup in my case.

The issue is that the API specifically says it doesn't support basic auth.

Since the containers do not (yet) have in depth docs I'm asking here if either there is a setting I don't know about to make the API container use an authentication mechanism (api key?) or whether implementing basic auth support is something that is easy to do on your end.

I can provide a "broken" environment if you'd like.

**Comment by agoldis** [comment]
This can help: https://www.apollographql.com/docs/apollo-server/security/authentication/
