### ISSUE TITLE
Bypass Gateway-connector in latest cypress versions

### ISSUE THREAD

**Issue by mesudip** [sorry-cypress/sorry-cypress#840]
### Command 
```
CYPRESS_API_URL="https://cypress.example.com" yarn  cy2 run  ...
```
### Error Log
https://go.cypress.io/continue-recording-with-gateway-connector

<img width="1294" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/11131298/0bec3d2c-db3d-41e2-a961-e2c93c3976bc">

**Comment by agoldis** [comment]
https://github.com/currents-dev/cypress-cloud

**Comment by mesudip** [comment]
does that mean cy2 should no longer be used?

**Comment by agoldis** [comment]
> Does that mean cy2 should no longer be used?

yes, the issue has been around since Feb 2023
