### ISSUE TITLE
MongoDB driver update

### ISSUE THREAD

**Issue by wolfmah** [sorry-cypress/sorry-cypress#845]
- [x] I have searched issues for similar feature requests
There was one that I opened 2 months ago that got auto-closed pretty quickly: #795

## What is this feature about (1 sentence)
Updating the MongoDB driver dependency to a more recent one, so newer MongoDB version can officially be supported instead of being "forward compatible".

## Why is it needed? What is the value? For whom do we build it?
The MongoDB driver used in the project (and by extension, the Helm chart dependency) are now old. As stated by Mongo [1], the driver version in use is now incompatible with the latest MongoDB version.

The Mongo drivers always offered forward compatibility, up to a point. But, I think that relying on future compatibility offers no guaranty with newer version, while keeping the driver up to date actually guaranty compatibility with newer versions, as well as older versions.

[1] Compatibility matrix of the MongoDB driver to MongoDB version: https://www.mongodb.com/docs/drivers/node/current/compatibility/

As of now, sorry-cypress is at 3.6.8:
* [packages/mongo/package.json](https://github.com/sorry-cypress/sorry-cypress/blob/master/packages/mongo/package.json#L31)
* [yarn.lock](https://github.com/sorry-cypress/sorry-cypress/blob/master/yarn.lock#L10905-L10906)

Why I bring it up?
My team inherited a bunch of old stuff at work and we're in the midst of upgrading MongoDB across the board for stuff that is no longer supported. While doing so, we make sure to bump the driver dependency found in our applications.

All our applications make use of the cloud version of MongoDB Atlas. On Atlas, when a version comes to an end of life (EOL) support, the DB are auto upgraded to the oldest supported one.

As we stumbled on our installation of sorry-cypress, we found that the official support of the MongoDB driver 3.6.8 stops at MongoDB version 4.4. Looking into the future of [end of life versions](https://www.mongodb.com/support-policy/lifecycles), we can see that MongoDB 4.4 will end support in February 2024.

As of now, forward compatibility offer us to use version 5.0 and 6.0, but not the newly released 7.0. So, this is more of a heads-up that it might be time to update that dependency.

Is it something that is open for a pull request?
Are there any implication that I am not seeing by just bumping that dependency?

**Comment by agoldis** [comment]
@wolfmah a PR would be appreciated
