### ISSUE TITLE
Something wrong about the useGetTestsFromProject() method when using --group command line parameter.

### ISSUE THREAD

**Issue by samixchoumi** [sorry-cypress/sorry-cypress#849]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.9`
  - platform: `k8s`
  - service: `dashboard`

```
</details>

### Describe the bug

When using the method on different view, it seem to show different data. On the summary project page it show : 
<img width="400" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/22171928/4b8e5965-48f2-4d73-a412-f1da334a3787">
But when I go into the project page, it show correct data : 
<img width="1165" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/22171928/16b151b0-1f3e-4245-bf2e-6550bcf8dd95">
But when using the `--group` command, for the first group, I get :
<img width="1176" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/22171928/1d0ff682-3f88-47ab-84ed-bbd20ca47c5f">
And I think that the command `useGetTestsFromProject()` just keep the first group executed instead of both group.

All other project doesn't have the problem when i'm not using `--group`.

### Expected behavior

`useGetTestsFromProject()` command keep all the tests data from different group when using `--group` so instead of : 
<img width="379" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/22171928/2bc574f8-71d4-400a-8243-246d22bbee9f">
I should have this on the project summary page : 
<img width="385" alt="image" src="https://github.com/sorry-cypress/sorry-cypress/assets/22171928/5d6da534-206d-4d05-abf9-2be93683de50">

### Reproduction steps

Use `--group` command using the same `--ci-build-id` for both commands with different number of test for each ci jobs and see that it only show the first `--group` test data value.

### Full log and debug output

<details>

```
No usefull logs found.

```

</details>

**Comment by samixchoumi** [comment]
Hello @agoldis, do you have any time to check what's wrong or explain to me what I should change, I don't understand what's wrong regarding the method, tried different way to get the wanted behavior but each time I got the problem with `--group` usage ...

**Comment by agoldis** [comment]
Hey @samixchoumi 
Check out https://github.com/sorry-cypress/sorry-cypress/pull/852/files

**Comment by samixchoumi** [comment]
Thanks @agoldis !
