### ISSUE TITLE
With Cypress 13.2.0 error on run page: Cannot return null for non-nullable field InstanceStats.wallClockDuration

### ISSUE THREAD

**Issue by zadoli** [sorry-cypress/sorry-cypress#853]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.9`
  - cypress version: `13.2.0`
  - cypress-cloud version: `1.9.3`
  - platform: `docker`
  - service: `dashboard`

```

</details>

### Describe the bug

Tests run with Cypress 13.2.0 can not be displayed on Dashboard because of the following error:
getRun Graphql call responses with the following:

```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field InstanceStats.wallClockDuration.",
            "locations": [
                {
                    "line": 72,
                    "column": 3
                }
            ],
            "path": [
                "run",
                "specs",
                0,
                "results",
                "stats",
                "wallClockDuration"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
}
```

### Expected behavior

Runs page should be displayed as usual.

### Reproduction steps

Run and upload tests with Cypress 13.X

**Comment by agoldis** [comment]
See https://github.com/currents-dev/cypress-cloud/issues/179

**Comment by anilpujaraofficial** [comment]
![Screenshot from 2023-09-29 14-59-11](https://github.com/sorry-cypress/sorry-cypress/assets/65593381/50fedc15-ff56-488f-a9c0-8d045f68bf74)

how can solve this error

**Comment by DamienCassou** [comment]
Also see https://currents.dev/posts/v13-blocking.

**Comment by zadoli** [comment]
> See [currents-dev/cypress-cloud#179](https://github.com/currents-dev/cypress-cloud/issues/179)
> Also see https://currents.dev/posts/v13-blocking.
