### ISSUE TITLE
AWS DocumentDB connections broken when using retryable writes

### ISSUE THREAD

**Issue by crux-capacitor** [sorry-cypress/sorry-cypress#854]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `latest`
  - cypress version: `10.11.0`
  - cy2 version: `<here>`
  - platform: `aws` advanced deployment using DocumentDB
  - service: `director`

```

</details>

### Describe the bug

Since getting the recent `latest` images, I'm getting errors in the director logs about retryable writes not being supported (example in debug logs section)

Currently, AWS DocDB does not support retryable writes on any version.

[Functional Differences: Amazon DocumentDB and MongoDB - Amazon DocumentDB](https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.retryable-writes)

### Expected behavior

One approach may be to disable retryable writes for DocDB connections.

The `MONGO_DB_URI` looks like this when using DocDB

`mongodb://sorrycypress:******@dbcluster-trioqjrywsqg.cluster-cdctwfh5obwj.us-east-2.docdb.amazonaws.com:27017`

When `docdb` is found, disable.  Some details here: https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.retryable-writes

### Reproduction steps

- deploy the advanced template using latest images and a remote DB
- configure a cypress run to point to it using the parallel flag

### Full log and debug output

<details>

```
{
  "level": 50,
  "time": 1694630200239,
  "requestId": "ee3fe87c-6116-4621-9ae6-7610ecbd8a33",
  "error": {
    "type": "MongoError",
    "message": "Retryable writes are not supported",
    "stack": "MongoError: Retryable writes are not supported\n at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:272:20)\n at MessageStream.emit (node:events:513:28)\n at MessageStream.emit (node:domain:489:12)\n at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n at writeOrBuffer (node:internal/streams/writable:391:12)\n at _write (node:internal/streams/writable:332:10)\n at MessageStream.Writable.write (node:internal/streams/writable:336:10)\n at Socket.ondata (node:internal/streams/readable:754:22)\n at Socket.emit (node:events:513:28)",
    "ok": 0,
    "code": 301,
    "operationTime": "7278381287813939201",
    "name": "MongoError"
  }
}
```

</details>

**Comment by cmiller96** [comment]
Is there any workaround for this? Its still an issue with the latest images
