### ISSUE TITLE
UI overhaul and other such improvements?

### ISSUE THREAD

**Issue by jhicken** [sorry-cypress/sorry-cypress#87]
First... you rock man thanks for your hard work on this project.

I dont know if you have a list of features anywhere that you would like to implement.
But here is my swing at it.

 Total run time
1. Individual spec runtimes
2. Automatic data refreshes (So you dont have to click refresh a bunch until its done)
3. Heuristics for specs on this projectid to guess how long each spec will run for
4. Date and time all specs and individual specs started running
5. Number of passed and failed tests on a spec level at the overview of a "run"
6. And probably a lot a bit of design love with some major css sprinkles. (If I did not have a crap load of side projects I would totally do this.)

Not ui but good nun the less.
7. Github hooks connection or some sort of programmable hook equivalent (this may exsist already and I missed it)
8. A hook of some sort on run creation to report run url. (So you can list the url on a github pr)

**Comment by agoldis** [comment]
Hi @jhicken!
Thanks for those suggestions you've pointed out. If you were to choose 3 most important, what would it be?

**Comment by jhicken** [comment]
Yeah absolutely. 

I would say most important things for me would 1, 5, and 7.

7 is probably the most important. Hooking up jenkins and or github up to report that tests are complete is pretty huge.

Also if you had 1 it should be pretty easy to calculate a total runtime.

**Comment by ismail-codinglab** [comment]
I would say 1,4 and 5

7/8 are too much bound to github, we all use different providers for our git solutions

**Comment by jhicken** [comment]
@ismail-codinglab Yeah I mean a github app could be written for the github specific use case. Due too popularity of github that hits a vast audience.
However, my recommendation was not entirely github specific. I was mostly asking for something generic to connect to. That would push events that you would use to manually trigger your own actions from. 

Such as perhaps there is a sorry-cypress websocket server that you can connect your ci service to that would send an event on `run/job` starts and `run/job` stops. This may require another service?... maybe.. I haven't done much with apollo. It might be doable with the current apollo api server if we switch it to use websockets instead of REST.

Also, I dug though the code yesterday and did 1,2,4,and 5 Ill try and submit it tomorrow.

3 would be awesome but I think It will require a new table/object in the DB for the project to store the last 5 or so successful run times for specs related to the project. (This table might be helpful in the future for many other reasons aswell)

6 just needs some dedicated time to think through the UX.

**Comment by agoldis** [comment]
@jhicken @ismail-codinglab great discussion here, I am on vacation currently, will be back next week and be able to contribute

**Comment by agoldis** [comment]
Summarizing what was done in #89 

- [x] Individual spec runtimes
- [x] Automatic data refreshes (So you dont have to click refresh a bunch until its done)
- [x] Date and time all specs and individual specs started running
- [x] Number of passed and failed tests on a spec level at the overview of a "run"

Good ideas yet to implement:

- [ ] Heuristics for specs on this projectid to guess how long each spec will run for
- [ ] Design love with some major css sprinkles.
- [ ]  Github hooks connection or some sort of programmable hook equivalent (this may exsist already and I missed it)
- [ ] A hook of some sort on run creation to report run url. (So you can list the url on a github pr)

**Comment by agoldis** [comment]
https://github.com/agoldis/sorry-cypress/releases/tag/v0.5.0

**Comment by jhicken** [comment]
I have a couple more things to add to my to-do list.

- [ ] `hide passing tests` should persist with local storage
- [ ] Live test results and stdout from test runner machines
- [ ] Add URL that assertions failed at to the spec results page (this might be debatable but I think its super useful)

Also I started on the heuristics.

**Comment by agoldis** [comment]
@jhicken What should we do with that issue? 
- break down to smaller issues?
- close altogether?
- turn into a project?

**Comment by jhicken** [comment]
Yeah good question. I think depends on where we want the prioritised backlog of work to live. I think projects is a great place to put this stuff. Then we can show our work in progress as well. And If we find that we need to break them down further we can do in on the project board.

Thoughts?

**Comment by agoldis** [comment]
Great, works for me

**Comment by agoldis** [comment]
@jhicken I have create individual issues for the items / ideas you listed. I've mentioned you in a few that weren't clear to me. Let's try to close this issue when and  create smaller issues if I missed something.

**Comment by jhicken** [comment]
@agoldis I think you got it all.

 I would love to do the design work to spuce the ui up and i have a lot of cool thoughts around it but actual functionality features are just going to win out for now.

I'm going to close this. 

Thanks for keeping us organized.
