### ISSUE TITLE
Result not displayed on sorry cypress always failed

### ISSUE THREAD

**Issue by FediSboui** [sorry-cypress/sorry-cypress#870]
TypeError: Cannot read properties of undefined (reading 'wallClockStartedAt')
    at http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:120:639978
    at Array.forEach (<anonymous>)
    at http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:120:639802
    at Array.forEach (<anonymous>)
    at http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:120:639769
    at Rj (http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:120:640398)
    at ii (http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:2:239508)
    at Wl (http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:2:291557)
    at Rs (http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:2:278831)
    at Ss (http://cypress01.in.karavel.com:8081/index.mjs?3d9a48ee540b4b7e87da:2:278759)
Please report at [Github Issues](https://github.com/agoldis/sorry-cypress/issues/new)

**Comment by samixchoumi** [comment]
Can you add more information please ?

**Comment by abhirajmt** [comment]
<img width="1476" alt="Screenshot 2023-10-23 at 2 59 13 PM" src="https://github.com/sorry-cypress/sorry-cypress/assets/79457217/08c920fe-206a-4cc7-94ce-8bfbe44aad4c">
Whenever we get into details of a cypress test, error mentioning **Cannot return null for non-nullable field InstanceStats.wallClockDuration** is displayed on the screen. Looks from the grapqhl response that the results node is getting empty. 
<img width="854" alt="Screenshot 2023-10-23 at 3 01 11 PM" src="https://github.com/sorry-cypress/sorry-cypress/assets/79457217/239f51cf-d861-4150-84a1-9b7a00123506">
What can be the possible cause behind this? @FediSboui were you able to resolve this?

Config:
"cypress": "12.17.4",
"cypress-cloud": "1.9.6",

node: 18.0.0

**Comment by grbaran** [comment]
Howdy ! I just decided to try sorry cypress today - simply followed to docs for some basic setup and I'm getting the same results in dashboard:
![image](https://github.com/sorry-cypress/sorry-cypress/assets/98872216/d00d9145-19ac-412b-914a-7f103e9575c7)
![image](https://github.com/sorry-cypress/sorry-cypress/assets/98872216/b634a2a0-0450-4010-b614-6db5f71df65b)

**Comment by agoldis** [comment]
Please use Cypress 12 - the error you're seeing are due to incompatibility
