### ISSUE TITLE
Publish via post processing

### ISSUE THREAD

**Issue by rrauenza** [sorry-cypress/sorry-cypress#878]
I'm wondering if the team has considered building a post processing script, like in Python, that would take json results from cypress (using one of the existing json reporters) and allow publishing the results and videos to sorry-cypress.

I myself don't really need real time reporting.  It's for troubleshooting runs later.

I could see some advantages with this kind of integration...

(I also may be able to help, but haven't found a documented API yet - but also haven't looked that hard.)

**Comment by rrauenza** [comment]
Is there a place where updates are being posted on working around Cypress's blocking of 3rd party dashboards?

**Comment by agoldis** [comment]
@rrauenza our Slack channel is the best place, there're no updates so far though
