### ISSUE TITLE
Uploading screenshots to azure blob storage

### ISSUE THREAD

**Issue by paveltyan** [sorry-cypress/sorry-cypress#879]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `v2.5.10`
  - cypress version: `^12.5.1`
  - cy2 version: `^4.0.6`
  - platform: `AKS`
  - service: `all`

```

We're trying to upload screenshots to azure blob storage. Director service is able to create signed urls, however the screenshots fail to upload with:
<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\\nRequestId:6010b544-b01e-004c-0739-13fccf000000\\nTime:2023-1109T18:18:21.4443402Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>
 

we do see that cy2-azure provides the correct header, however it's currently deprecated. What is currently the recommended way to work around this issue?

https://docs.sorry-cypress.dev/configuration/director-configuration/azure-blob-storage-configuration

### Describe the bug

We're trying to upload screenshots to azure blob storage. Director service is able to create signed urls, however the screenshots fail to upload with:
<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\\nRequestId:6010b544-b01e-004c-0739-13fccf000000\\nTime:2023-1109T18:18:21.4443402Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>
 

we do see that cy2-azure provides the correct header, however it's currently deprecated. What is currently the recommended way to work around this issue?

https://docs.sorry-cypress.dev/configuration/director-configuration/azure-blob-storage-configuration

### Expected behavior

upload to azure blob successfuly

### Reproduction steps

following docs from https://docs.sorry-cypress.dev/configuration/director-configuration/azure-blob-storage-configuration

### Full log and debug output

<details>

```
// Put your logs below this line

cypress: server: cloud: api response {
    screenshotUploadUrls: [{
            uploadUrl: 'http
            s://test.blob.core.windows.net/sorry-cypress-sandbox/576df93b2013
            149b35893c1b17f97b84.png?sv=2021-12-02&st=2023-11-09T18%3A18%3A21Z&se=2023-11-10
            T18%3A18%3A21Z&sr=b&sp=w&sig=cTXN6jEjODuVaNgrRV%2FOec57paYg%2BDzXsh7gM%2BbWsqw%3
            D&rsct=image%2Fpng',
            readUrl: 'https://test.blob.core.windows.net
            /sorry-cypress-sandbox/576df93b2013149b35893c1b17f97b84.png?sv=2021-12-02&st=202
            3-11-09T18%3A18%3A21Z&se=2024-11-08T18%3A18%3A21Z&sr=b&sp=r&sig=Xwio%2BLvAJSw1pI
            N4PHZxwYiKOeFpWXBtL9yqdi3uPX0%3D&rsct=image%2Fpng',
            screenshotId: 'f2r75'
        }
    ]
}
+228ms
cypress: server: record failed to upload artifact {
    file: 'C:\\Users\\Do
    cuments\\GitHub2\\genchi\\GenchiFrontend\\packages\\apps\\report\\cypress\\scree
    nshots\\login.spec.cy.js\\login spec -- log into genchi report (failed).png',
    st
    ack: 'StatusCodeError: 400 - "﻿<?xml version=\\"1.0\\" encoding=\\"utf-8\\"?>\\n
    <Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s man
    datory for this request is not specified.\\nRequestId:6010b544-b01e-004c-0739-13fccf000000\\nTime:2023-11-09T18:18:21.4443402Z</Message><HeaderName>x-ms-blob-ty
    pe</HeaderName></Error>"\n' + '    at new a (<embedded>:1737:501351)\n' + '    a
    t ee.callback (<embedded>:1737:507521)\n' + '    at e.callback.s.callback [as _c
    allback] (<embedded>:1737:506569)\n' + '    at s._callback.s.callback.s.callback
    (<embedded>:1955:65115)\n' + '    at ee.emit (node:events:527:28)\n' + '    at
    ee.<anonymous> (<embedded>:1955:77950)\n' + '    at ee.emit (node:events:527:28)
    \n' + '    at IncomingMessage.<anonymous> (<embedded>:1955:76687)\n' + '    at O
    bject.onceWrapper (node:events:641:28)\n' + '    at IncomingMessage.emit (node:e
    vents:539:35)\n' + '    at endReadableNT (node:internal/streams/readable:1345:12
    )\n' + '    at process.processTicksAndRejections (node:internal/process/task_que
    ues:83:21)'
}
+557ms

```

</details>

**Comment by meelisd** [comment]
I ran into the same issue, after analyzing how the uploads work my conclusion is that this cannot be fixed in the sorry-cypress director. It can only provide the upload urls for the client, the client needs to add the header when it actually uploads the artifacts. I've opened a PR on the cy2 repo that fixes the uploads to Azure storage accounts: sorry-cypress/cy2#82

**Comment by MarcelRoozekrans** [comment]
@agoldis Why is this issue closed ? There is an associated PR and we are actuelly using the proposed solution. 
It fixes the upload of scronshots to azure blob storage and runs find for over more then 2 months now. 

I would apreciate that this PR gets merged so we can get rid of the custom build we are using now.
