### ISSUE TITLE
Support Playwright

### ISSUE THREAD

**Issue by danielalmeidagoncalves** [sorry-cypress/sorry-cypress#883]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Sorry cypress supporting and integrating with Playwright tests
## Why is it needed? What is the value? For whom do we build it?
With the current block of third party tools by Cypress and the support of Playwright on Currents.dev, it would make sense to have sorry cypress also supporting Playwright tests.
## High-level feature overview
Sorry cypress supporting and integrating with Playwright tests

**Comment by mathpaquette** [comment]
@agoldis are you aiming to support playwright from sorry cypress ? If so, any draft plan in mind ?

**Comment by agoldis** [comment]
@mathpaquette 
Yes, we are adding Playwright support to sorry-cypress. That's a big effort because the project is quite outdated and needs major rehaul. No ETA right now, unfortunately.

**Comment by danielalmeidagoncalves** [comment]
Cool! this is very important news, lets make it a reality :)

**Comment by Gardosen** [comment]
I honestly would love to see this happening. 
my team and me just started using sorry-cypress for our on premise setup and we love it. 

as we have a longterm plan to migrate from cypress to playwright, this would be a huge gift :D

**Comment by mrtkrcm** [comment]
@agoldis happy to provide support if you consider a public PR

**Comment by sefaltay** [comment]
Actively following this!

**Comment by mbegerau** [comment]
We're also migrating from Cypress to Playwright and would love to stick with sorry cypress. Is there a roadmap or something? I see that it's already supported by currents, but our clients require a self-hosted solution.

**Comment by agoldis** [comment]
@dloop-mb please join the waitlist here: https://forms.gle/UY96L2YKEraPm3iK6

**Comment by samixchoumi** [comment]
Hello, do you have any update regarding the playwright integration to sorry-cypress ?
Or maybe, do you know if it's possible to adapt https://www.npmjs.com/package/@currents/playwright configuration to sorry-cypress ?

**Comment by MattFellows** [comment]
The waitlist form is gone, and there's been no update on this for over a year now.  Could we get a steer on if this is ever going to happen?

**Comment by agoldis** [comment]
@MattFellows 
May 2025 update: we have a paid beta version of https://currents.dev/on-premises available. No ETA for a free community version yet. If all goes well and we can fund it, we'll have a free community version.

**Comment by estefafdez** [comment]
happy to help build the open source/ free community version on pw!

**Comment by popuguytheparrot** [comment]
why it closed?

**Comment by samixchoumi** [comment]
Because they won’t do it
