### ISSUE TITLE
cypress-cloud does not run tests in parallel

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sorry-cypress/sorry-cypress#894]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `latest`
  - cypress version: `13.0.6`
  - platform: `docker`
  - service: `all`

```

</details>

### Describe the bug

Although it reports batch size and parallel, no tests are run in parallel all sequentially.

```
Discovered 38 spec files
Tags: false; Group: 4x-electron; Parallel: true; Batch Size: 5
Connecting to cloud orchestration service...
```

### Expected behavior

Tests should run in batches of 5 on each 4 instances of electron.

### Reproduction steps

`npx cypress-cloud run --parallel  --component --record --group 4x-electron --ci-build-id 'run:0'  `

### Full log and debug output

<details>
to much to redact

```
// Put your logs below this line


```

</details>

**Comment by Roemer** [comment]
Sorry Cypress does not work with Cypress 13 (yet). Also if Cypress 13 is used, you need to run it without cy2 or cypress-cloud and buy the Cypress Gateway Connector Licence from Cypress themselves.

**Comment by agoldis** [comment]
https://currents.dev/posts/v13-blocking
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries

**Comment by sschneider-ihre-pvs** [comment]
> Sorry Cypress does not work with Cypress 13 (yet). Also if Cypress 13 is used, you need to run it without cy2 or cypress-cloud and buy the Cypress Gateway Connector Licence from Cypress themselves.

It does kinda work with the exception of the details view

![grafik](https://github.com/sorry-cypress/sorry-cypress/assets/86342787/74672c7e-5fba-4079-8300-37bb132d171b)

in the overview it works

![grafik](https://github.com/sorry-cypress/sorry-cypress/assets/86342787/d4b9f2fb-cd06-421e-abe3-7e24efcbf4c7)
