### ISSUE TITLE
All results show cypress crashed

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sorry-cypress/sorry-cypress#895]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
same as  #894

```

</details>

### Describe the bug

All test results show this in dashboard, even the successful passing tests.

`No results detected for the spec file. That usually happens because of cypress crash. See the console output for details.`

### Expected behavior

Show failed as failed and passed as passed

### Reproduction steps

 same as #894

### Full log and debug output

 same as #894
<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
https://currents.dev/posts/v13-blocking
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries
