### ISSUE TITLE
Unable to open detail view for run

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sorry-cypress/sorry-cypress#896]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
same as #895 

```

</details>

### Describe the bug

Unable to open the run overview for a specific run, in the overview of all runs I see the failing and passing tests.

![grafik](https://github.com/sorry-cypress/sorry-cypress/assets/86342787/33d9fc14-8cc2-461e-a421-f7419efc8c0e)

### Expected behavior

The detail view for a run should be shown correctly

### Reproduction steps

same as #895

### Full log and debug output

same as #895 
<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
https://currents.dev/posts/v13-blocking
https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries
