### ISSUE TITLE
dashaboard issue

### ISSUE THREAD

**Issue by alenocera** [sorry-cypress/sorry-cypress#921]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: 2.6.0
  - cypress version: 13.3.2
  - cy2 version: not installed
  - platform: docker
  - service: all
```

</details>

### Describe the bug

Im starting to implement the kit as explained here: https://docs.sorry-cypress.dev/guide/dashboard-and-api#persisting-test-results

I'm able to reach the dashboard but this error is shown:
`Error: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://<graphql-ip-address>:4000` 

I'm hosting all in my machine of course (I followed the guide above as I told) but the initial config seems not works as expected.
I've created the `currents.config.js` like this:
```
module.exports = {
  projectId: 'yyy', // the projectId, can be any values for sorry-cypress users
  recordKey: 'xxx', // the record key, can be any value for sorry-cypress users
  cloudServiceUrl: 'http://localhost:1234', // Sorry Cypress users - set the director service URL
};
```
and also added into the `setupNodeEvents` the plugin:
```
async setupNodeEvents(on, config) {
      cloudPlugin(on, config);
      // other stuff below but not impact sorry-cypress I guess
}
```
What I'm wrong?

### Expected behavior

Dashboard up&running fine

### Reproduction steps

Just follow the https://docs.sorry-cypress.dev/guide/dashboard-and-api 

### Full log and debug output

<details>

```
WARN[0000] /Users/alessandro.nocera/Documents/Automation/sgrunt/docker-compose.minio.yml: `version` is obsolete 
WARN[0000] Found orphan containers ([nginx frontend backend cydb]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 4/0
 ✔ Container sgrunt-mongo-1      Created                                                                                                                                     0.0s 
 ✔ Container sgrunt-api-1        Running                                                                                                                                     0.0s 
 ✔ Container sgrunt-director-1   Running                                                                                                                                     0.0s 
 ✔ Container sgrunt-dashboard-1  Running                                                                                                                                     0.0s 
Attaching to api-1, createbuckets-1, dashboard-1, director-1, mongo-1, storage-1
mongo-1          | chown: changing ownership of '/data/db': Permission denied
mongo-1 exited with code 1
createbuckets-1  | /bin/sh: -c: line 1: syntax error near unexpected token `<'
createbuckets-1  | /bin/sh: -c: line 1: ` sleep 3; /usr/bin/mc config host add myminio http://localhost:9000 <minio-user> <minio-pass>; /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress; /usr/bin/mc mb myminio/sorry-cypress; /usr/bin/mc anonymous set download myminio/sorry-cypress; /usr/bin/mc anonymous set public myminio/sorry-cypress; exit 0; '
createbuckets-1 exited with code 2
storage-1        | INFO: Formatting 1st pool, 1 set(s), 1 drives per set.
storage-1        | INFO: WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
storage-1        | MinIO Object Storage Server
storage-1        | Copyright: 2015-2024 MinIO, Inc.
storage-1        | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
storage-1        | Version: RELEASE.2024-08-03T04-33-23Z (go1.22.5 linux/amd64)
storage-1        | 
storage-1        | API: http://192.168.32.3:9000  http://127.0.0.1:9000 
storage-1        | WebUI: http://192.168.32.3:9090 http://127.0.0.1:9090 
storage-1        | 
storage-1        | Docs: https://min.io/docs/minio/linux/index.html
api-1            | MongoServerSelectionError: getaddrinfo EAI_AGAIN mongo
api-1            |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
api-1            |     at listOnTimeout (node:internal/timers:559:17)
api-1            |     at processTimers (node:internal/timers:502:7) {
api-1            |   reason: TopologyDescription {
api-1            |     type: 'Single',
api-1            |     setName: null,
api-1            |     maxSetVersion: null,
api-1            |     maxElectionId: null,
api-1            |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
api-1            |     stale: false,
api-1            |     compatible: true,
api-1            |     compatibilityError: null,
api-1            |     logicalSessionTimeoutMinutes: null,
api-1            |     heartbeatFrequencyMS: 10000,
api-1            |     localThresholdMS: 15,
api-1            |     commonWireVersion: null
api-1            |   }
api-1            | }
api-1 exited with code 1


```

</details>

**Comment by ibrahimsTailorMed** [comment]
I'm having similar issue when I try to set it up with docker. 
This is the output for minio/mc 
`2024-08-22 06:19:50 /bin/sh: -c: line 1: syntax error near unexpected token `<'
2024-08-22 06:19:50 /bin/sh: -c: line 1: ` sleep 3; /usr/bin/mc config host add myminio http://localhost:9000 <minio-user> <minio-pass>; /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress; /usr/bin/mc mb myminio/sorry-cypress; /usr/bin/mc anonymous set download myminio/sorry-cypress; /usr/bin/mc anonymous set public myminio/sorry-cypress; exit 0; '
`

**Comment by ibrahimsTailorMed** [comment]
I performed the following modifications to the yml file and I was able to access the dashboard. 
Change the entry point for the createbucket to the value below, this will keep createbuckets-1 running, it will not exit with code 2.
`    entrypoint: >
      /bin/sh -c "
          until (/usr/bin/mc config host add myminio http://minio:9000 minio minio123) do echo '...waiting...' &&
      sleep 1;
      done;
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc admin user add myminio/ $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc admin policy set myminio/ readwrite user=$${MINIO_ACCESS_KEY};
      /usr/bin/mc mb myminio/$${MINIO_MEDIA_FILES_BUCKET};
      /usr/bin/mc policy set public myminio/$${MINIO_MEDIA_FILES_BUCKET};
      exec sleep inf;
      "
`
set graphqol to local host 
`GRAPHQL_SCHEMA_URL: http://localhost:4000`

Set MINIO_ENDPOINT and MINIO_URL to be localhost.
`MINIO_ENDPOINT: "localhost"
      MINIO_URL: "http://localhost"`


You will be able to access the dashboard and the project is created, but still the following issues are encountered. 
when running/executing the tests. 
It will run them one by one like below 
`Running:  verify-patient-boxes.spec.js                                                    (1 of 1)`
even we have multiple specs within the same directory. 
the other problem is, when trying to access the dashboard and open the execution details. You'll get the error below 
`
Error: Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration. Cannot return null for non-nullable field InstanceStats.wallClockDuration.`
<img width="1680" alt="Screenshot 2024-09-01 at 9 32 36 AM" src="https://github.com/user-attachments/assets/7c2e6ec5-bb9c-4078-914f-571861008d47">
